-- Comprehensive DSQL-compatible migration using every supported data type.
-- This file MUST lint with zero errors. If a new rule causes a false positive
-- on any supported type, this fixture will catch it.

-- Numeric types
CREATE TABLE numeric_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    col_smallint    SMALLINT,
    col_int2        INT2,
    col_integer     INTEGER,
    col_int         INT,
    col_int4        INT4,
    col_bigint      BIGINT,
    col_int8        INT8,
    col_real        REAL,
    col_float4      FLOAT4,
    col_double      DOUBLE PRECISION,
    col_float8      FLOAT8,
    col_numeric     NUMERIC(10,2),
    col_decimal     DECIMAL(18,6),
    col_dec         DEC(5,2)
);

-- Character types
CREATE TABLE character_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    col_char        CHAR(10),
    col_character   CHARACTER(20),
    col_varchar     VARCHAR(255),
    col_charvar     CHARACTER VARYING(100),
    col_text        TEXT,
    col_bpchar      BPCHAR(50)
);

-- Date/time types
CREATE TABLE datetime_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    col_date        DATE,
    col_time        TIME,
    col_timetz      TIME WITH TIME ZONE,
    col_timestamp   TIMESTAMP,
    col_timestamptz TIMESTAMP WITH TIME ZONE,
    col_interval    INTERVAL
);

-- Miscellaneous types
CREATE TABLE misc_types (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    col_boolean     BOOLEAN,
    col_bool        BOOL,
    col_bytea       BYTEA,
    col_uuid        UUID
);

-- Identity columns (both flavors)
CREATE TABLE identity_always (
    id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 1) PRIMARY KEY,
    name TEXT
);

CREATE TABLE identity_by_default (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) PRIMARY KEY,
    name TEXT
);

-- Constraints: PRIMARY KEY, UNIQUE, NOT NULL, CHECK, DEFAULT
CREATE TABLE all_constraints (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    age INTEGER CHECK (age >= 0),
    status VARCHAR(20) DEFAULT 'active'
);

-- Valid DML (should never trigger errors)
INSERT INTO numeric_types (id, col_integer) VALUES (gen_random_uuid(), 42);
SELECT * FROM character_types WHERE col_text = 'hello';
UPDATE misc_types SET col_boolean = true WHERE col_uuid = gen_random_uuid();
DELETE FROM datetime_types WHERE col_date < CURRENT_DATE;

-- Valid DDL operations
ALTER TABLE numeric_types ADD COLUMN extra TEXT;
CREATE INDEX ASYNC idx_char_text ON character_types(col_text);
CREATE UNIQUE INDEX ASYNC idx_constraints_email ON all_constraints(email);

-- CREATE VIEW is fine
CREATE VIEW active_items AS SELECT * FROM all_constraints WHERE status = 'active';

-- LANGUAGE SQL function is allowed
CREATE FUNCTION add_nums(a INT, b INT) RETURNS INT AS $$ SELECT a + b; $$ LANGUAGE SQL;

-- CREATE SEQUENCE with BIGINT and valid CACHE
CREATE SEQUENCE seq_test AS BIGINT CACHE 65536;

-- ALTER TABLE with supported operations
ALTER TABLE numeric_types RENAME COLUMN extra TO extra_col;
ALTER TABLE numeric_types OWNER TO CURRENT_USER;
