use sqlparser::ast::{
    AlterColumnOperation, AlterFunctionKind, AlterFunctionOperation, AlterRoleOperation,
    AlterTableOperation, ColumnDef, ColumnOption, ColumnOptionDef, CopyTarget, CreateTableOptions,
    DataType, DeclareType, Expr, GeneratedAs, IndexOption, ObjectType, RoleOption, SequenceOptions,
    Set, SqlOption, Statement, TableConstraint, TransactionIsolationLevel, TransactionMode,
    UnaryOperator, Value, ValueWithSpan,
};
use sqlparser::tokenizer::Span;

use crate::lint::{Diagnostic, FixResult, LintRule};

use super::{find_line, find_line_any};

/// Construct a `CACHE 1` sequence option — the safe default for DSQL.
pub(crate) fn cache_1_option() -> SequenceOptions {
    SequenceOptions::Cache(Expr::Value(ValueWithSpan {
        value: Value::Number("1".to_string(), false),
        span: Span::empty(),
    }))
}

/// Construct a `GENERATED BY DEFAULT AS IDENTITY (CACHE 1)` column option — the
/// canonical DSQL replacement for `SERIAL`. Shared between the inline-`SERIAL`
/// rule and the pg_dump SERIAL-idiom collapse so both paths emit identical
/// shape and any future change to the option lands in one place.
pub(crate) fn identity_by_default_cache_1() -> ColumnOptionDef {
    ColumnOptionDef {
        name: None,
        option: ColumnOption::Generated {
            generated_as: GeneratedAs::ByDefault,
            sequence_options: Some(vec![cache_1_option()]),
            generation_expr: None,
            generation_expr_mode: None,
            generated_keyword: false,
        },
    }
}

fn error(
    rule: LintRule,
    line: usize,
    message: impl Into<String>,
    suggestion: impl Into<String>,
    fix_result: FixResult,
) -> Diagnostic {
    Diagnostic {
        rule,
        line,
        statement: String::new(),
        message: message.into(),
        suggestion: suggestion.into(),
        fix_result,
    }
}

/// Check a single column definition for unsupported types and constraints.
/// `in_alter_table`: true when called from ALTER TABLE ADD COLUMN context.
/// DSQL does not allow constraints on ALTER TABLE ADD COLUMN, so fixes that
/// add constraints (e.g. SERIAL → IDENTITY) must be Unfixable there.
fn check_column(
    col: &mut ColumnDef,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
    in_alter_table: bool,
) {
    let col_name_lower = col.name.to_string().to_lowercase();

    // SERIAL variants
    if let DataType::Custom(name, _) = &col.data_type {
        let type_str = name.to_string().to_uppercase();
        if matches!(
            type_str.as_str(),
            "SERIAL" | "SERIAL4" | "BIGSERIAL" | "SERIAL8" | "SMALLSERIAL" | "SERIAL2"
        ) {
            if in_alter_table {
                diagnostics.push(error(
                    LintRule::SerialType,
                    find_line(raw_sql, &type_str.to_lowercase()),
                    format!(
                        "Column `{}` uses {type_str}, which is not supported in DSQL.",
                        col.name
                    ),
                    "DSQL does not support ALTER TABLE ADD COLUMN with constraints. Define identity columns at table creation time.",
                    FixResult::Unfixable,
                ));
            } else {
                col.data_type = DataType::BigInt(None);
                col.options.push(identity_by_default_cache_1());
                diagnostics.push(error(
                    LintRule::SerialType,
                    find_line(raw_sql, &type_str.to_lowercase()),
                    format!(
                        "Column `{}` uses {type_str}, which is not supported in DSQL.",
                        col.name
                    ),
                    "Use `BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)` instead.",
                    FixResult::FixedWithWarning(format!("Replaced {} with BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1) on column `{}` — verify application code handles the wider type range; the implicit identity sequence is no longer addressable by name, so any nextval()/setval()/currval() calls against the old SERIAL sequence will break", type_str, col.name)),
                ));
            }
        }
    }

    // Array types
    if matches!(&col.data_type, DataType::Array(_)) {
        diagnostics.push(error(
            LintRule::ArrayType,
            find_line(raw_sql, &col_name_lower),
            format!(
                "Column `{}` uses an array type, which is not supported in DSQL.",
                col.name
            ),
            "Use a join table for relational data, or store as JSON text.",
            FixResult::Unfixable,
        ));
    }

    // Identity checks — type and CACHE fixes.
    // Note: after the SERIAL→IDENTITY mutation above, this loop sees the newly-added
    // Generated option. It's a safe no-op because SERIAL already sets BigInt + CACHE 1.
    for opt_def in &mut col.options {
        if let ColumnOption::Generated {
            generated_as: GeneratedAs::Always | GeneratedAs::ByDefault,
            sequence_options,
            ..
        } = &mut opt_def.option
        {
            if in_alter_table {
                diagnostics.push(error(
                    LintRule::IdentityType,
                    find_line(raw_sql, &col_name_lower),
                    format!(
                        "Column `{}` uses GENERATED AS IDENTITY, which is not supported in ALTER TABLE ADD COLUMN in DSQL.",
                        col.name
                    ),
                    "DSQL does not support ALTER TABLE ADD COLUMN with constraints. Define identity columns at table creation time.",
                    FixResult::Unfixable,
                ));
                break;
            }
            if !matches!(&col.data_type, DataType::BigInt(_) | DataType::Int8(_)) {
                let old_type = col.data_type.to_string();
                col.data_type = DataType::BigInt(None);
                diagnostics.push(error(
                    LintRule::IdentityType,
                    find_line(raw_sql, &col_name_lower),
                    format!(
                        "Identity column `{}` must use BIGINT type in DSQL. Found: {old_type}.",
                        col.name
                    ),
                    "Use BIGINT GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY (CACHE ...).",
                    FixResult::FixedWithWarning(format!("Changed identity column `{}` type from {old_type} to BIGINT — verify application code handles the wider 8-byte range", col.name)),
                ));
            }
            if let Some(seq_opts) = sequence_options {
                validate_cache_options(LintRule::IdentityCache, seq_opts, raw_sql, diagnostics);
            }
        }
    }

    // FK removal — retain everything that's NOT a foreign key
    let col_name = col.name.to_string();
    col.options.retain(|opt_def| {
        if matches!(opt_def.option, ColumnOption::ForeignKey(_)) {
            diagnostics.push(error(
                LintRule::ForeignKey,
                find_line(raw_sql, &col_name_lower),
                format!("Column `{}` has a FOREIGN KEY (REFERENCES) constraint, which is not supported in DSQL.", col_name),
                "Remove the REFERENCES clause. Enforce referential integrity in application code.",
                FixResult::FixedWithWarning(format!("Removed FOREIGN KEY constraint from column `{}`", col_name)),
            ));
            false
        } else {
            true
        }
    });

    // COLLATE clause — DSQL rejects per-column COLLATE entirely (the database
    // collation is C). Strip the clause. C/POSIX are byte-order equivalents
    // of the database default, so removal is a pure no-op (`Fixed`); every
    // other collation (including `"default"`, which on the source DB is
    // typically locale-aware) loses ordering semantics on DSQL, so we
    // surface a `FixedWithWarning`.
    col.options.retain(|opt_def| {
        if let ColumnOption::Collation(name) = &opt_def.option {
            let collation = name.to_string();
            // Compare the last identifier part (handles `pg_catalog."C"` from
            // pg_dump as well as plain `"C"` / unquoted `C`).
            let is_c_equivalent = name
                .0
                .last()
                .and_then(|p| p.as_ident())
                .is_some_and(|ident| {
                    matches!(
                        ident.value.to_ascii_uppercase().as_str(),
                        "C" | "POSIX"
                    )
                });
            let fix_result = if is_c_equivalent {
                FixResult::Fixed(format!(
                    "Removed COLLATE {collation} from column `{col_name}`"
                ))
            } else {
                FixResult::FixedWithWarning(format!(
                    "Removed COLLATE {collation} from column `{col_name}` — DSQL uses C collation; ORDER BY and LIKE semantics may differ from the source database"
                ))
            };
            diagnostics.push(error(
                LintRule::Collation,
                find_line(raw_sql, &col_name_lower),
                format!(
                    "Column `{col_name}` uses a COLLATE clause, which is not supported in DSQL."
                ),
                "Remove the COLLATE clause. DSQL's database collation is C (byte-order); locale-aware ordering and comparison are not available.",
                fix_result,
            ));
            false
        } else {
            true
        }
    });
}

pub(crate) fn check(stmt: &mut Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::CreateTable(ct) = stmt {
        for col in &mut ct.columns {
            check_column(col, raw_sql, diagnostics, false);
        }

        ct.constraints.retain(|constraint| {
            if matches!(constraint, TableConstraint::ForeignKey(_)) {
                diagnostics.push(error(
                    LintRule::ForeignKey,
                    find_line(raw_sql, "foreign key"),
                    "Table-level FOREIGN KEY constraint is not supported in DSQL.",
                    "Remove the FOREIGN KEY constraint. Enforce referential integrity in application code.",
                    FixResult::FixedWithWarning("Removed table-level FOREIGN KEY constraint".into()),
                ));
                false
            } else {
                true
            }
        });

        if ct.temporary {
            ct.temporary = false;
            diagnostics.push(error(
                LintRule::TempTable,
                find_line_any(raw_sql, &["temporary", "temp"]),
                "TEMPORARY tables are not supported in DSQL.",
                "Use regular tables or application-level caching.",
                FixResult::FixedWithWarning("Removed TEMPORARY keyword — the table is now persistent, shares one fixed name across all sessions (concurrent sessions will collide), and is not auto-dropped. Give it a unique name and drop it explicitly, or rewrite as a CTE/subquery.".into()),
            ));
        }

        if ct.partition_by.is_some() {
            ct.partition_by = None;
            diagnostics.push(error(
                LintRule::PartitionBy,
                find_line(raw_sql, "partition by"),
                "PARTITION BY is not supported in DSQL.",
                "Omit — DSQL manages distribution automatically.",
                FixResult::FixedWithWarning("Removed PARTITION BY clause".into()),
            ));
        }

        // INHERITS clause
        if ct.inherits.as_ref().is_some_and(|v| !v.is_empty()) {
            ct.inherits = None;
            diagnostics.push(error(
                LintRule::Inherits,
                find_line(raw_sql, "inherits"),
                "INHERITS clause is not supported in DSQL.",
                "Flatten the table hierarchy or use application-layer inheritance patterns.",
                FixResult::FixedWithWarning("Removed INHERITS clause — columns inherited from the parent table are NOT copied; declare every inherited column explicitly or the table will be missing them".into()),
            ));
        }

        // CREATE TABLE AS / SELECT INTO
        if ct.query.is_some() {
            diagnostics.push(error(
                LintRule::CreateTableAs,
                find_line_any(raw_sql, &["as select", "as\n", "as"]),
                "CREATE TABLE AS (SELECT ...) is not supported in DSQL.",
                "Create the table with explicit column definitions, then INSERT INTO ... SELECT ....",
                FixResult::Unfixable,
            ));
        }

        // TABLESPACE clause
        match &mut ct.table_options {
            CreateTableOptions::With(opts)
            | CreateTableOptions::Options(opts)
            | CreateTableOptions::Plain(opts)
            | CreateTableOptions::TableProperties(opts) => {
                let len_before = opts.len();
                opts.retain(|o| !matches!(o, SqlOption::TableSpace(_)));
                if opts.len() < len_before {
                    diagnostics.push(error(
                        LintRule::Tablespace,
                        find_line(raw_sql, "tablespace"),
                        "TABLESPACE clause is not supported in DSQL.",
                        "Remove the TABLESPACE clause. DSQL manages storage automatically.",
                        FixResult::FixedWithWarning("Removed TABLESPACE clause".into()),
                    ));
                }
            }
            CreateTableOptions::None => {}
        }

        // Reported after Tablespace removal above so a TABLESPACE-only
        // CREATE TABLE doesn't double-flag. Storage parameters are PG-internal
        // tuning hints (autovacuum_enabled, fillfactor, …) that DSQL doesn't
        // honor — stripping them is the same shape as stripping TABLESPACE.
        let storage_params_remaining = match &ct.table_options {
            CreateTableOptions::With(opts)
            | CreateTableOptions::Options(opts)
            | CreateTableOptions::Plain(opts)
            | CreateTableOptions::TableProperties(opts) => !opts.is_empty(),
            CreateTableOptions::None => false,
        };
        if storage_params_remaining {
            ct.table_options = CreateTableOptions::None;
            diagnostics.push(error(
                LintRule::UnsupportedCreateTableWithStorageParameters,
                find_line(raw_sql, "with"),
                "CREATE TABLE WITH (...) storage parameters are not supported in DSQL.",
                "Remove the WITH clause. DSQL manages storage parameters automatically.",
                FixResult::FixedWithWarning(
                    "Removed WITH (...) storage parameters — DSQL manages storage automatically"
                        .into(),
                ),
            ));
        }

        if ct.partition_of.is_some() {
            diagnostics.push(error(
                LintRule::UnsupportedPartitionOf,
                find_line(raw_sql, "partition of"),
                "CREATE TABLE ... PARTITION OF is not supported in DSQL.",
                "DSQL manages distribution automatically; create the table without PARTITION OF.",
                FixResult::Unfixable,
            ));
        }

        // ON COMMIT is only meaningful on TEMP tables in PostgreSQL. The
        // TempTable rule above strips TEMPORARY, so leaving ON COMMIT in
        // place would produce invalid SQL (ON COMMIT on a persistent table).
        if ct.on_commit.is_some() {
            ct.on_commit = None;
            diagnostics.push(error(
                LintRule::UnsupportedOnCommit,
                find_line(raw_sql, "on commit"),
                "CREATE TABLE ... ON COMMIT is not supported in DSQL.",
                "Remove the ON COMMIT clause.",
                FixResult::FixedWithWarning(
                    "Removed ON COMMIT clause — temporary-table semantics are not preserved".into(),
                ),
            ));
        }
    }

    check_alter_table(stmt, raw_sql, diagnostics);
    check_truncate(stmt, raw_sql, diagnostics);
    check_create_index(stmt, raw_sql, diagnostics);
    check_create_sequence(stmt, raw_sql, diagnostics);
    check_unsupported_statements(stmt, raw_sql, diagnostics);
    check_add_column_constraints(stmt, raw_sql, diagnostics);
    check_transaction_isolation(stmt, raw_sql, diagnostics);
    check_sequence_cache_missing(stmt, raw_sql, diagnostics);
    check_identity_cache_missing(stmt, raw_sql, diagnostics);
    check_alter_table_operations(stmt, raw_sql, diagnostics);
}

fn check_alter_table(stmt: &mut Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    let Statement::AlterTable(alter_table) = stmt else {
        return;
    };

    // Mutable pass: remove FK constraints
    alter_table.operations.retain(|op| {
        match op {
            AlterTableOperation::AddConstraint {
                constraint: TableConstraint::ForeignKey(_),
                ..
            } => {
                diagnostics.push(error(
                    LintRule::ForeignKey,
                    find_line(raw_sql, "foreign key"),
                    "ALTER TABLE ADD CONSTRAINT with FOREIGN KEY is not supported in DSQL.",
                    "Remove the FOREIGN KEY constraint. Enforce referential integrity in application code.",
                    FixResult::FixedWithWarning(
                        "Removed ALTER TABLE ADD FOREIGN KEY constraint".into(),
                    ),
                ));
                false
            }
            _ => true,
        }
    });

    // Mutable pass: check columns (needs &mut for fix mutations) and
    // read-only checks for everything else.
    for op in &mut alter_table.operations {
        match op {
            AlterTableOperation::AddColumn { column_def, .. } => {
                check_column(column_def, raw_sql, diagnostics, true);
            }
            AlterTableOperation::AddConstraint {
                constraint: TableConstraint::PrimaryKeyUsingIndex { .. },
                ..
            } => {
                diagnostics.push(error(
                    LintRule::AtUnsupportedPrimaryKeyUsingIndex,
                    find_line(raw_sql, "using index"),
                    "PRIMARY KEY USING INDEX is not supported in DSQL.",
                    "Create a PRIMARY KEY constraint directly instead of promoting an index.",
                    FixResult::Unfixable,
                ));
            }
            AlterTableOperation::AddConstraint {
                constraint: TableConstraint::UniqueUsingIndex { .. },
                ..
            } => {
                diagnostics.push(error(
                    LintRule::AtUnsupportedUniqueUsingIndex,
                    find_line(raw_sql, "using index"),
                    "UNIQUE USING INDEX is not supported in DSQL.",
                    "Create a UNIQUE constraint directly instead of promoting an index.",
                    FixResult::Unfixable,
                ));
            }
            // Row-Level Security
            AlterTableOperation::EnableRowLevelSecurity
            | AlterTableOperation::DisableRowLevelSecurity
            | AlterTableOperation::ForceRowLevelSecurity
            | AlterTableOperation::NoForceRowLevelSecurity => {
                diagnostics.push(error(
                    LintRule::AtUnsupportedRowLevelSecurity,
                    find_line(raw_sql, "row level security"),
                    format!("ALTER TABLE {op} is not supported in DSQL."),
                    "Implement row-level access control in the application layer.",
                    FixResult::Unfixable,
                ));
            }
            // Replica identity
            AlterTableOperation::ReplicaIdentity { .. } => {
                diagnostics.push(error(
                    LintRule::AtUnsupportedReplicaIdentity,
                    find_line(raw_sql, "replica identity"),
                    "ALTER TABLE REPLICA IDENTITY is not supported in DSQL.",
                    "DSQL does not support logical replication. Remove this statement.",
                    FixResult::Unfixable,
                ));
            }
            // VALIDATE CONSTRAINT
            AlterTableOperation::ValidateConstraint { name } => {
                diagnostics.push(error(
                    LintRule::AtUnsupportedValidateConstraint,
                    find_line(raw_sql, "validate constraint"),
                    format!("ALTER TABLE VALIDATE CONSTRAINT '{name}' is not supported in DSQL."),
                    "Add constraints as valid at creation time.",
                    FixResult::Unfixable,
                ));
            }
            // Rewrite rules
            AlterTableOperation::EnableRule { .. }
            | AlterTableOperation::DisableRule { .. }
            | AlterTableOperation::EnableAlwaysRule { .. }
            | AlterTableOperation::EnableReplicaRule { .. } => {
                diagnostics.push(error(
                    LintRule::AtUnsupportedRewriteRule,
                    find_line(raw_sql, "rule"),
                    format!("ALTER TABLE {op} is not supported in DSQL."),
                    "Remove rewrite rules. Implement logic in the application layer.",
                    FixResult::Unfixable,
                ));
            }
            _ => {}
        }
    }
}

/// ALTER TABLE ADD COLUMN with inline DEFAULT or NOT NULL.
fn check_add_column_constraints(
    stmt: &mut Statement,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let Statement::AlterTable(alter_table) = stmt else {
        return;
    };

    for op in &alter_table.operations {
        if let AlterTableOperation::AddColumn { column_def, .. } = op {
            let has_default_or_not_null = column_def
                .options
                .iter()
                .any(|opt| matches!(opt.option, ColumnOption::Default(_) | ColumnOption::NotNull));
            if has_default_or_not_null {
                diagnostics.push(error(
                    LintRule::AddColumnConstraint,
                    find_line(raw_sql, &column_def.name.value.to_lowercase()),
                    format!(
                        "ADD COLUMN '{}' with inline DEFAULT or NOT NULL constraint is not supported in DSQL.",
                        column_def.name.value
                    ),
                    "Split into steps: CREATE TABLE with the column, or ADD COLUMN without constraints then backfill.",
                    FixResult::Unfixable,
                ));
            }
        }
    }
}

struct UnsupportedOp {
    rule: LintRule,
    msg: String,
    suggestion: &'static str,
    needle: &'static str,
}

/// Unsupported ALTER TABLE operations. Each arm names its own `LintRule` so
/// the per-rule fixture map can drive coverage tests exhaustively.
fn check_alter_table_operations(
    stmt: &mut Statement,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let Statement::AlterTable(alter_table) = stmt else {
        return;
    };

    for op in &alter_table.operations {
        let UnsupportedOp {
            rule,
            msg,
            suggestion,
            needle,
        } = match op {
            AlterTableOperation::DropColumn { column_names, .. } => {
                let names: Vec<_> = column_names.iter().map(|n| n.to_string()).collect();
                UnsupportedOp {
                    rule: LintRule::AtUnsupportedDropColumn,
                    msg: format!(
                        "ALTER TABLE DROP COLUMN ({}) is not supported in DSQL.",
                        names.join(", ")
                    ),
                    suggestion: "Recreate the table without the column, then migrate data.",
                    needle: "drop column",
                }
            }
            AlterTableOperation::AlterColumn {
                column_name,
                op: alter_op,
            } => match alter_op {
                AlterColumnOperation::SetDataType { .. } => UnsupportedOp {
                    rule: LintRule::AtUnsupportedAlterColumnSetType,
                    msg: format!("ALTER COLUMN '{column_name}' TYPE is not supported in DSQL."),
                    suggestion: "Recreate the table with the desired column type.",
                    needle: "alter column",
                },
                AlterColumnOperation::SetNotNull => UnsupportedOp {
                    rule: LintRule::AtUnsupportedAlterColumnSetNotNull,
                    msg: format!(
                        "ALTER COLUMN '{column_name}' SET NOT NULL is not supported in DSQL."
                    ),
                    suggestion: "Add NOT NULL at table creation time.",
                    needle: "not null",
                },
                AlterColumnOperation::DropNotNull => UnsupportedOp {
                    rule: LintRule::AtUnsupportedAlterColumnDropNotNull,
                    msg: format!(
                        "ALTER COLUMN '{column_name}' DROP NOT NULL is not supported in DSQL."
                    ),
                    suggestion: "Recreate the table if needed.",
                    needle: "not null",
                },
                AlterColumnOperation::SetDefault { .. } => UnsupportedOp {
                    rule: LintRule::AtUnsupportedAlterColumnSetDefault,
                    msg: format!(
                        "ALTER COLUMN '{column_name}' SET DEFAULT is not supported in DSQL."
                    ),
                    suggestion: "Set default at table creation time.",
                    needle: "set default",
                },
                AlterColumnOperation::DropDefault => UnsupportedOp {
                    rule: LintRule::AtUnsupportedAlterColumnDropDefault,
                    msg: format!(
                        "ALTER COLUMN '{column_name}' DROP DEFAULT is not supported in DSQL."
                    ),
                    suggestion: "Recreate the table if needed.",
                    needle: "drop default",
                },
                AlterColumnOperation::AddGenerated { .. } => UnsupportedOp {
                    rule: LintRule::AtUnsupportedAlterColumnAddGenerated,
                    msg: format!(
                        "ALTER COLUMN '{column_name}' ADD GENERATED AS IDENTITY is not supported in DSQL."
                    ),
                    suggestion: "Define identity columns at table creation time.",
                    needle: "identity",
                },
            },
            AlterTableOperation::AddConstraint { constraint, .. } => match constraint {
                TableConstraint::Check(_) => UnsupportedOp {
                    rule: LintRule::AtUnsupportedAddCheck,
                    msg: "ALTER TABLE ADD CHECK constraint is not supported in DSQL.".to_string(),
                    suggestion: "Add CHECK constraints at table creation time.",
                    needle: "add constraint",
                },
                TableConstraint::Unique(_) => UnsupportedOp {
                    rule: LintRule::AtUnsupportedAddUnique,
                    msg: "ALTER TABLE ADD UNIQUE constraint is not supported in DSQL.".to_string(),
                    suggestion: "Add UNIQUE constraints at table creation time.",
                    needle: "add constraint",
                },
                TableConstraint::PrimaryKey(_) => UnsupportedOp {
                    rule: LintRule::AtUnsupportedAddPrimaryKey,
                    msg: "ALTER TABLE ADD PRIMARY KEY constraint is not supported in DSQL."
                        .to_string(),
                    suggestion: "Add PRIMARY KEY constraints at table creation time.",
                    needle: "add constraint",
                },
                // ForeignKey handled by check_alter_table; other variants skipped.
                _ => continue,
            },
            AlterTableOperation::DropConstraint { name, .. } => UnsupportedOp {
                rule: LintRule::AtUnsupportedDropConstraint,
                msg: format!("ALTER TABLE DROP CONSTRAINT '{name}' is not supported in DSQL."),
                suggestion: "Recreate the table without the constraint.",
                needle: "drop constraint",
            },
            _ => continue,
        };
        diagnostics.push(error(
            rule,
            find_line(raw_sql, needle),
            msg,
            suggestion,
            FixResult::Unfixable,
        ));
    }
}

fn check_create_index(stmt: &mut Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    let Statement::CreateIndex(ci) = stmt else {
        return;
    };

    if ci.concurrently {
        ci.concurrently = false;
        ci.r#async = true;
        diagnostics.push(error(
            LintRule::IndexConcurrently,
            find_line(raw_sql, "concurrently"),
            "CREATE INDEX CONCURRENTLY is not supported in DSQL.",
            "Use CREATE INDEX ASYNC instead of CONCURRENTLY.",
            FixResult::FixedWithWarning("Replaced CONCURRENTLY with ASYNC — the index builds in the background and is NOT ready when the statement returns; wait via sys.jobs before relying on it, and a UNIQUE build can still fail later on a duplicate".to_string()),
        ));
    } else if !ci.r#async {
        ci.r#async = true;
        let idx_name = ci.name.as_ref().map(|n| n.to_string()).unwrap_or_default();
        diagnostics.push(error(
            LintRule::IndexAsync,
            find_line(raw_sql, "index"),
            format!(
                "CREATE INDEX without ASYNC is not supported in DSQL.{}",
                if !idx_name.is_empty() {
                    format!(" Index: {idx_name}")
                } else {
                    String::new()
                }
            ),
            "Use `CREATE INDEX ASYNC ...` instead.",
            FixResult::FixedWithWarning("Added ASYNC keyword to CREATE INDEX — the index builds in the background and is NOT ready when the statement returns; wait via sys.jobs before relying on it, and a UNIQUE build can still fail later on a duplicate".to_string()),
        ));
    }

    let using_type = ci.using.take().or_else(|| {
        ci.index_options.iter().find_map(|opt| {
            if let IndexOption::Using(idx_type) = opt {
                Some(idx_type.clone())
            } else {
                None
            }
        })
    });
    if using_type.is_some() {
        ci.index_options
            .retain(|opt| !matches!(opt, IndexOption::Using(_)));
    }
    if let Some(index_type) = using_type {
        let index_type_str = index_type.to_string();
        let is_btree = index_type_str.eq_ignore_ascii_case("btree");
        let fix_result = if is_btree {
            FixResult::Fixed(format!(
                "Removed USING {index_type_str} clause (btree is the default)"
            ))
        } else {
            FixResult::FixedWithWarning(format!(
                "Removed USING {index_type_str} clause — DSQL only supports btree indexes"
            ))
        };
        diagnostics.push(error(
            LintRule::IndexUsing,
            find_line(raw_sql, "using"),
            format!("DSQL does not support the USING clause in CREATE INDEX (found USING {index_type_str}). Remove it — btree is used automatically."),
            "Remove the USING clause. DSQL uses btree indexes by default.",
            fix_result,
        ));
    }

    // Expression indexes — Unfixable
    for col in &ci.columns {
        if !matches!(&col.column.expr, Expr::Identifier(_)) {
            diagnostics.push(error(
                LintRule::IndexExpression,
                find_line(raw_sql, "index"),
                "Expression indexes are not supported in DSQL. Only simple column references are allowed.",
                "Add a stored computed column and index that instead, or handle in application layer.",
                FixResult::Unfixable,
            ));
            break;
        }
    }

    // Partial indexes — Unfixable
    if ci.predicate.is_some() {
        diagnostics.push(error(
            LintRule::IndexPartial,
            find_line(raw_sql, "where"),
            "Partial indexes (CREATE INDEX ... WHERE) are not supported in DSQL.",
            "Create a full index instead, or filter in queries.",
            FixResult::Unfixable,
        ));
    }
}

fn check_truncate(stmt: &mut Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if matches!(stmt, Statement::Truncate(_)) {
        diagnostics.push(error(
            LintRule::Truncate,
            find_line(raw_sql, "truncate"),
            "TRUNCATE is not supported in DSQL.",
            "Use DELETE FROM table_name instead.",
            FixResult::Unfixable,
        ));
    }
}

/// Validate CACHE values in sequence options. Shared between standalone CREATE SEQUENCE
/// and identity column definitions.
fn validate_cache_options(
    cache_rule: LintRule,
    opts: &mut [SequenceOptions],
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    for opt in opts.iter_mut() {
        let cache_expr = match opt {
            SequenceOptions::Cache(expr) => expr,
            _ => continue,
        };

        // Extract the numeric value, handling both positive literals and unary +/- signs
        let cache_val = match cache_expr {
            Expr::Value(ValueWithSpan {
                value: Value::Number(n, _),
                ..
            }) => n.parse::<i64>().ok(),
            Expr::UnaryOp {
                op: UnaryOperator::Minus,
                expr,
            } => {
                if let Expr::Value(ValueWithSpan {
                    value: Value::Number(n, _),
                    ..
                }) = expr.as_ref()
                {
                    n.parse::<i64>().ok().map(|v| -v)
                } else {
                    None
                }
            }
            Expr::UnaryOp {
                op: UnaryOperator::Plus,
                expr,
            } => {
                if let Expr::Value(ValueWithSpan {
                    value: Value::Number(n, _),
                    ..
                }) = expr.as_ref()
                {
                    n.parse::<i64>().ok()
                } else {
                    None
                }
            }
            _ => None,
        };

        match cache_val {
            Some(v) if v == 1 || v >= 65536 => {} // valid
            Some(v) => {
                *opt = cache_1_option();
                diagnostics.push(error(
                    cache_rule,
                    find_line(raw_sql, "cache"),
                    format!(
                        "CACHE value {v} is invalid in DSQL. Only CACHE 1 or CACHE >= 65536 are allowed."
                    ),
                    "Use CACHE 1 for sequential behavior or CACHE 65536+ for high-throughput.",
                    FixResult::FixedWithWarning(format!("Changed CACHE {v} to CACHE 1 — consider CACHE 65536 for high-throughput workloads")),
                ));
            }
            None => {
                diagnostics.push(error(
                    cache_rule,
                    find_line(raw_sql, "cache"),
                    format!(
                        "CACHE value '{cache_expr}' could not be validated for DSQL. Only CACHE 1 or CACHE >= 65536 are allowed."
                    ),
                    "Use CACHE 1 for sequential behavior or CACHE 65536+ for high-throughput.",
                    FixResult::Unfixable,
                ));
            }
        }
    }
}

fn check_create_sequence(stmt: &mut Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    let Statement::CreateSequence {
        data_type,
        sequence_options,
        ..
    } = stmt
    else {
        return;
    };

    // Non-BIGINT type
    if let Some(dt) = data_type {
        let is_bigint = matches!(dt, DataType::BigInt(_) | DataType::Int8(_));
        if !is_bigint {
            let old_type = dt.to_string();
            *dt = DataType::BigInt(None);
            diagnostics.push(error(
                LintRule::SequenceType,
                find_line(raw_sql, "create sequence"),
                format!(
                    "CREATE SEQUENCE with type {old_type} is not supported in DSQL. Only BIGINT is supported."
                ),
                "Use AS BIGINT or omit the type clause (defaults to BIGINT).",
                FixResult::FixedWithWarning(format!("Changed sequence type from {old_type} to BIGINT — verify application code consuming this sequence handles the wider 8-byte range")),
            ));
        }
    }

    // Invalid CACHE value
    validate_cache_options(
        LintRule::SequenceCache,
        sequence_options,
        raw_sql,
        diagnostics,
    );
}

fn check_unsupported_statements(
    stmt: &mut Statement,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    match stmt {
        // CREATE TEMPORARY VIEW
        Statement::CreateView(cv) if cv.temporary => {
            cv.temporary = false;
            diagnostics.push(error(
                LintRule::UnsupportedTempView,
                find_line_any(raw_sql, &["temporary view", "temp view"]),
                "CREATE TEMPORARY VIEW is not supported in DSQL.",
                "Use a regular CREATE VIEW instead.",
                FixResult::FixedWithWarning("Removed TEMPORARY keyword from view".into()),
            ));
        }

        // CREATE MATERIALIZED VIEW
        Statement::CreateView(cv) if cv.materialized => {
            diagnostics.push(error(
                LintRule::UnsupportedMaterializedView,
                find_line(raw_sql, "materialized view"),
                "CREATE MATERIALIZED VIEW is not supported in DSQL.",
                "Use a regular CREATE VIEW instead.",
                FixResult::Unfixable,
            ));
        }

        Statement::CreateTrigger(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedCreateTrigger,
                find_line(raw_sql, "create trigger"),
                "CREATE TRIGGER is not supported in DSQL.",
                "Implement trigger logic in application layer.",
                FixResult::Unfixable,
            ));
        }
        Statement::CreateExtension(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedCreateExtension,
                find_line(raw_sql, "create extension"),
                "CREATE EXTENSION is not supported in DSQL.",
                "Extensions not available in DSQL.",
                FixResult::Unfixable,
            ));
        }
        Statement::CreateFunction(cf) => {
            let is_sql_language = cf
                .language
                .as_ref()
                .map(|l| l.value.eq_ignore_ascii_case("sql"))
                .unwrap_or(true);
            if !is_sql_language {
                let lang_info = cf
                    .language
                    .as_ref()
                    .map(|l| format!(" (LANGUAGE {})", l.value))
                    .unwrap_or_default();
                diagnostics.push(error(
                    LintRule::UnsupportedCreateFunctionNonSql,
                    find_line(raw_sql, "create function"),
                    format!(
                        "CREATE FUNCTION{lang_info} is not supported in DSQL. Only LANGUAGE SQL is allowed."
                    ),
                    "Use LANGUAGE SQL or implement in application layer.",
                    FixResult::Unfixable,
                ));
            }
        }
        Statement::CreateProcedure { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedCreateProcedure,
                find_line(raw_sql, "create procedure"),
                "CREATE PROCEDURE is not supported in DSQL.",
                "Implement in application layer.",
                FixResult::Unfixable,
            ));
        }

        // CREATE DATABASE
        Statement::CreateDatabase { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedCreateDatabase,
                find_line(raw_sql, "create database"),
                "CREATE DATABASE is not supported in DSQL. Each cluster provides a single 'postgres' database.",
                "Use separate DSQL clusters for logical separation, or use schemas within a single cluster.",
                FixResult::Unfixable,
            ));
        }

        // CREATE POLICY / Row-Level Security
        Statement::CreatePolicy(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedCreatePolicy,
                find_line(raw_sql, "create policy"),
                "CREATE POLICY (Row-Level Security) is not supported in DSQL.",
                "Implement row-level access control in the application layer.",
                FixResult::Unfixable,
            ));
        }

        // SAVEPOINT
        Statement::Savepoint { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedSavepoint,
                find_line(raw_sql, "savepoint"),
                "SAVEPOINT is not supported in DSQL.",
                "Restructure logic to use separate transactions instead of partial rollbacks.",
                FixResult::Unfixable,
            ));
        }

        // RELEASE SAVEPOINT
        Statement::ReleaseSavepoint { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedReleaseSavepoint,
                find_line(raw_sql, "release savepoint"),
                "RELEASE SAVEPOINT is not supported in DSQL.",
                "Restructure logic to use separate transactions instead of partial rollbacks.",
                FixResult::Unfixable,
            ));
        }

        // ROLLBACK TO SAVEPOINT
        Statement::Rollback {
            savepoint: Some(_), ..
        } => {
            diagnostics.push(error(
                LintRule::UnsupportedRollbackToSavepoint,
                find_line(raw_sql, "savepoint"),
                "ROLLBACK TO SAVEPOINT is not supported in DSQL.",
                "Restructure logic to use separate transactions instead of partial rollbacks.",
                FixResult::Unfixable,
            ));
        }

        // DECLARE CURSOR
        Statement::Declare { stmts } => {
            for d in stmts {
                if matches!(d.declare_type, Some(DeclareType::Cursor)) {
                    diagnostics.push(error(
                        LintRule::UnsupportedDeclareCursor,
                        find_line(raw_sql, "cursor"),
                        "DECLARE CURSOR is not supported in DSQL.",
                        "Use LIMIT/OFFSET pagination or application-side cursoring.",
                        FixResult::Unfixable,
                    ));
                    break;
                }
            }
        }

        // CREATE TYPE
        Statement::CreateType { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedCreateType,
                find_line(raw_sql, "create type"),
                "CREATE TYPE is not supported in DSQL.",
                "Use CHECK constraints for enum-like validation, or TEXT with application-layer validation.",
                FixResult::Unfixable,
            ));
        }

        // CREATE SERVER (FDW)
        Statement::CreateServer(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedCreateServer,
                find_line(raw_sql, "create server"),
                "CREATE SERVER is not supported in DSQL.",
                "Access external data sources from the application layer.",
                FixResult::Unfixable,
            ));
        }

        // VACUUM
        Statement::Vacuum(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedVacuum,
                find_line(raw_sql, "vacuum"),
                "VACUUM is not supported in DSQL.",
                "Remove VACUUM commands. DSQL manages maintenance automatically.",
                FixResult::Unfixable,
            ));
        }

        // ALTER INDEX
        Statement::AlterIndex { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedAlterIndex,
                find_line(raw_sql, "alter index"),
                "ALTER INDEX is not supported in DSQL.",
                "Drop and recreate the index with the desired properties.",
                FixResult::Unfixable,
            ));
        }

        // COPY — only STDIN/STDOUT variants work in DSQL (used by \copy and drivers).
        // Server-side file paths and program pipes are not supported.
        Statement::Copy {
            target: target @ (CopyTarget::File { .. } | CopyTarget::Program { .. }),
            ..
        } => {
            diagnostics.push(error(
                LintRule::UnsupportedCopyFromFile,
                find_line(raw_sql, "copy"),
                format!("COPY with {target} is not supported in DSQL. Only STDIN/STDOUT are allowed."),
                "Use COPY ... FROM STDIN / COPY ... TO STDOUT, or load data from the application layer.",
                FixResult::Unfixable,
            ));
        }

        Statement::Lock { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedLockTable,
                find_line(raw_sql, "lock"),
                "LOCK TABLE is not supported in DSQL.",
                "Remove LOCK TABLE statements. DSQL uses optimistic concurrency control.",
                FixResult::Unfixable,
            ));
        }

        // ALTER AGGREGATE — entire family rejected.
        // ALTER FUNCTION — only property changes (Actions: IMMUTABLE/STRICT/COST/SET/...)
        // are rejected; RENAME TO, OWNER TO, SET SCHEMA, DEPENDS ON EXTENSION run on DSQL.
        Statement::AlterFunction(af) => match (&af.kind, &af.operation) {
            (AlterFunctionKind::Aggregate, _) => {
                diagnostics.push(error(
                    LintRule::UnsupportedAlterAggregate,
                    find_line(raw_sql, "alter aggregate"),
                    "ALTER AGGREGATE is not supported in DSQL.",
                    "Drop and recreate the aggregate, or manage it from the application layer.",
                    FixResult::Unfixable,
                ));
            }
            (AlterFunctionKind::Function, AlterFunctionOperation::Actions { .. }) => {
                diagnostics.push(error(
                    LintRule::UnsupportedAlterFunctionProperty,
                    find_line(raw_sql, "alter function"),
                    "ALTER FUNCTION property changes (IMMUTABLE/STRICT/COST/SET/...) are not supported in DSQL.",
                    "Drop and recreate the function with the desired properties.",
                    FixResult::Unfixable,
                ));
            }
            _ => {}
        },

        Statement::AlterPolicy(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedAlterPolicy,
                find_line(raw_sql, "alter policy"),
                "ALTER POLICY is not supported in DSQL.",
                "Row-Level Security is not supported. Implement access control in the application layer.",
                FixResult::Unfixable,
            ));
        }

        Statement::AlterType(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedAlterType,
                find_line(raw_sql, "alter type"),
                "ALTER TYPE is not supported in DSQL.",
                "DSQL does not support user-defined types. Use CHECK constraints or application-layer validation.",
                FixResult::Unfixable,
            ));
        }

        // ALTER ROLE — only WithOptions (PASSWORD/VALID UNTIL/SUPERUSER/CREATEROLE/...)
        // and Set (config parameters) are rejected. RenameRole and Reset execute on DSQL.
        Statement::AlterRole {
            operation: AlterRoleOperation::WithOptions { options },
            ..
        } => {
            let names: Vec<&'static str> = options
                .iter()
                .map(|opt| match opt {
                    RoleOption::Password(_) => "PASSWORD",
                    RoleOption::ValidUntil(_) => "VALID UNTIL",
                    RoleOption::SuperUser(_) => "SUPERUSER",
                    RoleOption::CreateRole(_) => "CREATEROLE",
                    RoleOption::CreateDB(_) => "CREATEDB",
                    RoleOption::Inherit(_) => "INHERIT",
                    RoleOption::Login(_) => "LOGIN",
                    RoleOption::Replication(_) => "REPLICATION",
                    RoleOption::BypassRLS(_) => "BYPASSRLS",
                    RoleOption::ConnectionLimit(_) => "CONNECTION LIMIT",
                })
                .collect();
            let opt_list = if names.is_empty() {
                "options".to_string()
            } else {
                names.join(", ")
            };
            diagnostics.push(error(
                LintRule::UnsupportedAlterRoleProperty,
                find_line(raw_sql, "alter role"),
                format!(
                    "ALTER ROLE with {opt_list} is not supported in DSQL."
                ),
                "DSQL does not honor these role attributes; remove them. Use IAM (aws_iam_authorize) for authentication and GRANT for privileges.",
                FixResult::Unfixable,
            ));
        }
        Statement::AlterRole {
            operation: AlterRoleOperation::Set { .. },
            ..
        } => {
            diagnostics.push(error(
                LintRule::UnsupportedAlterRoleSet,
                find_line(raw_sql, "alter role"),
                "ALTER ROLE ... SET <config> is not supported in DSQL.",
                "Set session parameters via SET at connection time instead.",
                FixResult::Unfixable,
            ));
        }

        // ALTER USER — entire statement rejected by DSQL.
        Statement::AlterUser(_) => {
            diagnostics.push(error(
                LintRule::UnsupportedAlterUser,
                find_line(raw_sql, "alter user"),
                "ALTER USER is not supported in DSQL.",
                "Recreate the role with the desired attributes, or set session parameters via SET at connection time.",
                FixResult::Unfixable,
            ));
        }

        // DROP MATERIALIZED VIEW / DROP TYPE — DSQL rejects with "unsupported object in DROP".
        Statement::Drop {
            object_type: ObjectType::MaterializedView,
            names,
            ..
        } => {
            let label = names.first().map(|n| format!(" '{n}'")).unwrap_or_default();
            diagnostics.push(error(
                LintRule::UnsupportedDropMaterializedView,
                find_line_any(raw_sql, &["drop materialized view", "materialized view"]),
                format!("DROP MATERIALIZED VIEW{label} is not supported in DSQL."),
                "Materialized views are not supported; use a regular VIEW instead.",
                FixResult::Unfixable,
            ));
        }
        Statement::Drop {
            object_type: ObjectType::Type,
            names,
            ..
        } => {
            let label = names.first().map(|n| format!(" '{n}'")).unwrap_or_default();
            diagnostics.push(error(
                LintRule::UnsupportedDropType,
                find_line(raw_sql, "drop type"),
                format!("DROP TYPE{label} is not supported in DSQL."),
                "User-defined types are not supported in DSQL.",
                FixResult::Unfixable,
            ));
        }

        Statement::LISTEN { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedListen,
                find_line(raw_sql, "listen"),
                "LISTEN is not supported in DSQL.",
                "DSQL does not support the LISTEN/NOTIFY subsystem; use an external message bus.",
                FixResult::Unfixable,
            ));
        }
        Statement::UNLISTEN { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedUnlisten,
                find_line(raw_sql, "unlisten"),
                "UNLISTEN is not supported in DSQL.",
                "DSQL does not support the LISTEN/NOTIFY subsystem; use an external message bus.",
                FixResult::Unfixable,
            ));
        }
        Statement::NOTIFY { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedNotify,
                find_line(raw_sql, "notify"),
                "NOTIFY is not supported in DSQL.",
                "DSQL does not support the LISTEN/NOTIFY subsystem; use an external message bus.",
                FixResult::Unfixable,
            ));
        }

        Statement::Load { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedLoad,
                find_line(raw_sql, "load"),
                "LOAD is not supported in DSQL.",
                "DSQL does not allow loading extensions; remove LOAD statements.",
                FixResult::Unfixable,
            ));
        }

        // SQL-level PREPARE is rejected; driver-level prepared statements
        // over the wire still work.
        Statement::Prepare { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedPrepare,
                find_line(raw_sql, "prepare"),
                "PREPARE is not supported in DSQL.",
                "Use driver-level prepared statements instead of SQL-level PREPARE/EXECUTE.",
                FixResult::Unfixable,
            ));
        }

        // DEALLOCATE ALL is accepted by DSQL; named DEALLOCATE is not.
        Statement::Deallocate { name, .. } if !name.value.eq_ignore_ascii_case("ALL") => {
            diagnostics.push(error(
                LintRule::UnsupportedDeallocate,
                find_line(raw_sql, "deallocate"),
                format!(
                    "DEALLOCATE '{name}' is not supported in DSQL. Only DEALLOCATE ALL is allowed."
                ),
                "Use DEALLOCATE ALL, or rely on driver-level prepared statement management.",
                FixResult::Unfixable,
            ));
        }

        Statement::Discard { .. } => {
            diagnostics.push(error(
                LintRule::UnsupportedDiscard,
                find_line(raw_sql, "discard"),
                "DISCARD is not supported in DSQL.",
                "Open a fresh connection if you need a clean session state.",
                FixResult::Unfixable,
            ));
        }

        Statement::DropTrigger(t) => {
            let label = format!(" '{}'", t.trigger_name);
            diagnostics.push(error(
                LintRule::UnsupportedDropTrigger,
                find_line(raw_sql, "drop trigger"),
                format!("DROP TRIGGER{label} is not supported in DSQL."),
                "Triggers are not supported in DSQL; remove trigger management from migrations.",
                FixResult::Unfixable,
            ));
        }
        Statement::DropPolicy(p) => {
            let label = format!(" '{}'", p.name);
            diagnostics.push(error(
                LintRule::UnsupportedDropPolicy,
                find_line(raw_sql, "drop policy"),
                format!("DROP POLICY{label} is not supported in DSQL."),
                "Row-Level Security policies are not supported; remove policy management from migrations.",
                FixResult::Unfixable,
            ));
        }

        _ => {}
    }
}

/// Transaction isolation level — only REPEATABLE READ is supported.
/// BEGIN ISOLATION LEVEL can be fixed; SET TRANSACTION is entirely unsupported by DSQL.
fn check_transaction_isolation(
    stmt: &mut Statement,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let (modes, is_set_transaction) = match stmt {
        Statement::StartTransaction { modes, .. } => (modes, false),
        Statement::Set(Set::SetTransaction { modes, .. }) => (modes, true),
        _ => return,
    };

    if is_set_transaction {
        diagnostics.push(error(
            LintRule::SetTransaction,
            find_line(raw_sql, "set transaction"),
            "SET TRANSACTION is not supported in DSQL.",
            "Use `BEGIN ISOLATION LEVEL REPEATABLE READ` instead.",
            FixResult::Unfixable,
        ));
        return;
    }

    for mode in modes.iter_mut() {
        if let TransactionMode::IsolationLevel(level) = mode {
            if !matches!(level, TransactionIsolationLevel::RepeatableRead) {
                let old_level = level.to_string();
                *level = TransactionIsolationLevel::RepeatableRead;
                diagnostics.push(error(
                    LintRule::TransactionIsolation,
                    find_line(raw_sql, "isolation"),
                    format!(
                        "Transaction isolation level {old_level} is not supported in DSQL. Only REPEATABLE READ is supported."
                    ),
                    "Remove the isolation level clause, or use ISOLATION LEVEL REPEATABLE READ.",
                    FixResult::FixedWithWarning(format!("Changed isolation level from {old_level} to REPEATABLE READ — this changes the transaction's concurrency semantics (e.g. SERIALIZABLE no longer prevents the anomalies it guarded against; READ COMMITTED now sees a frozen snapshot and may hit more OCC aborts); verify the application's correctness assumptions still hold")),
                ));
            }
        }
    }
}

/// CREATE SEQUENCE without explicit CACHE clause.
fn check_sequence_cache_missing(
    stmt: &mut Statement,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let Statement::CreateSequence {
        sequence_options, ..
    } = stmt
    else {
        return;
    };
    let has_cache = sequence_options
        .iter()
        .any(|o| matches!(o, SequenceOptions::Cache(_)));
    if !has_cache {
        sequence_options.push(cache_1_option());
        diagnostics.push(error(
            LintRule::SequenceCacheMissing,
            find_line(raw_sql, "create sequence"),
            "CREATE SEQUENCE without explicit CACHE clause is not supported in DSQL.",
            "Add an explicit CACHE 1 or CACHE 65536 clause.",
            FixResult::Fixed("Added CACHE 1 to CREATE SEQUENCE".to_string()),
        ));
    }
}

/// Identity column without explicit CACHE clause.
/// Only processes CREATE TABLE — ALTER TABLE ADD COLUMN identity is handled
/// as Unfixable in check_column (DSQL rejects any constraints there).
fn check_identity_cache_missing(
    stmt: &mut Statement,
    raw_sql: &str,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let columns: Vec<&mut ColumnDef> = match stmt {
        Statement::CreateTable(ct) => ct.columns.iter_mut().collect(),
        _ => return,
    };
    for col in columns {
        for opt_def in &mut col.options {
            if let ColumnOption::Generated {
                generated_as: GeneratedAs::Always | GeneratedAs::ByDefault,
                sequence_options,
                ..
            } = &mut opt_def.option
            {
                let has_cache = sequence_options.as_ref().is_some_and(|opts| {
                    opts.iter().any(|o| matches!(o, SequenceOptions::Cache(_)))
                });
                if !has_cache {
                    let cache_opt = cache_1_option();
                    match sequence_options {
                        Some(opts) => opts.push(cache_opt),
                        None => *sequence_options = Some(vec![cache_opt]),
                    }
                    diagnostics.push(error(
                        LintRule::IdentityCacheMissing,
                        find_line(raw_sql, &col.name.to_string().to_lowercase()),
                        format!(
                            "Identity column `{}` without explicit CACHE clause is not supported in DSQL.",
                            col.name
                        ),
                        "Add an explicit CACHE 1 or CACHE 65536 clause to the identity definition.",
                        FixResult::Fixed(format!("Added CACHE 1 to identity column `{}`", col.name)),
                    ));
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sqlparser::dialect::PostgreSqlDialect;
    use sqlparser::parser::Parser;

    fn parse_and_check(sql: &str) -> Vec<Diagnostic> {
        let dialect = PostgreSqlDialect {};
        let mut stmts = Parser::parse_sql(&dialect, sql).expect("SQL should parse");
        let mut diags = Vec::new();
        for stmt in &mut stmts {
            check(stmt, sql, &mut diags);
        }
        diags
    }

    // ── Suggestion validity ─────────────────────────────────────────────
    // These tests need internal access (parse_and_check, backtick extraction)
    // so they live here rather than in integration tests.

    const VALIDATED_SUGGESTIONS: &[&str] = &[
        "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
        "CREATE INDEX ASYNC ...",
    ];

    #[test]
    fn suggested_replacements_are_dsql_valid() {
        for suggestion in VALIDATED_SUGGESTIONS {
            if suggestion.starts_with("CREATE") {
                let sql = "CREATE INDEX ASYNC idx_test ON t(col);";
                let diags = crate::lint::lint_sql(sql);
                assert!(
                    !diags.iter().any(|d| d.message.contains("not supported")),
                    "Suggested command triggers lint errors!\n  Suggestion: {suggestion}\n  Errors: {diags:?}"
                );
            } else {
                let sql = format!("CREATE TABLE _test (id {suggestion} PRIMARY KEY);");
                let diags = crate::lint::lint_sql(&sql);
                let errors: Vec<_> = diags
                    .iter()
                    .filter(|d| d.message.contains("not supported"))
                    .collect();
                assert!(
                    errors.is_empty(),
                    "Suggested type is not DSQL-valid!\n  Type: {suggestion}\n  Errors: {errors:?}"
                );
            }
        }
    }

    /// Guard: every backtick-wrapped suggestion the linter emits must appear
    /// in VALIDATED_SUGGESTIONS. Uses the integration-level ERROR_CASES
    /// indirectly by running all detectable patterns through lint_sql.
    #[test]
    fn all_suggested_replacements_are_covered() {
        // Collect suggestions from every pattern that lint_sql can handle
        let inputs = &[
            "CREATE TABLE t (id SERIAL PRIMARY KEY);",
            "CREATE TABLE t (id BIGSERIAL PRIMARY KEY);",
            "CREATE TABLE t (id SMALLSERIAL PRIMARY KEY);",
            "CREATE INDEX idx ON t(col);",
        ];
        let mut found: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
        for sql in inputs {
            for d in crate::lint::lint_sql(sql) {
                if let (Some(a), Some(b)) = (d.suggestion.find('`'), d.suggestion.rfind('`')) {
                    if a < b {
                        found.insert(d.suggestion[a + 1..b].to_string());
                    }
                }
            }
        }
        for replacement in &found {
            assert!(
                VALIDATED_SUGGESTIONS.iter().any(|s| {
                    s == replacement
                        || (s.ends_with("...") && replacement.starts_with(&s[..s.len() - 3]))
                }),
                "Suggestion `{replacement}` emitted by linter but not in VALIDATED_SUGGESTIONS"
            );
        }
    }

    // ── Edge cases needing parse_and_check ──────────────────────────────
    // These bypass lint_sql's statement splitter, which can't handle $$ or
    // needs raw SQL matching that only works at the single-statement level.

    #[test]
    fn plpgsql_detected_and_includes_language_name() {
        let sql = "CREATE FUNCTION inc(v INT) RETURNS INT AS $$ BEGIN RETURN v+1; END; $$ LANGUAGE plpgsql;";
        let diags = parse_and_check(sql);
        assert!(diags.iter().any(|d| d.message.contains("LANGUAGE plpgsql")));
    }

    #[test]
    fn sql_function_not_flagged() {
        let sql =
            "CREATE FUNCTION add(a INT, b INT) RETURNS INT AS $$ SELECT a + b; $$ LANGUAGE SQL;";
        let diags = parse_and_check(sql);
        assert!(!diags.iter().any(|d| d.message.contains("FUNCTION")));
    }

    #[test]
    fn function_without_language_not_flagged() {
        let sql = "CREATE FUNCTION add(INTEGER, INTEGER) RETURNS INTEGER AS 'select $1 + $2;'";
        let diags = parse_and_check(sql);
        assert!(
            !diags.iter().any(|d| d.message.contains("FUNCTION")),
            "Function without LANGUAGE clause should default to SQL and not be flagged: {diags:?}"
        );
    }

    #[test]
    fn serial_with_references_reports_both() {
        let sql = "CREATE TABLE t (id SERIAL REFERENCES other(id));";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.message.contains("SERIAL")),
            "Should report SERIAL error: {diags:?}"
        );
        assert!(
            diags.iter().any(|d| d.message.contains("FOREIGN KEY")),
            "Should also report FOREIGN KEY error: {diags:?}"
        );
    }

    #[test]
    fn create_procedure_detected() {
        let sql = "CREATE PROCEDURE do_stuff() AS BEGIN SELECT 1; END";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.message.contains("PROCEDURE")),
            "CREATE PROCEDURE should be flagged: {diags:?}"
        );
    }

    #[test]
    fn multiple_references_report_distinct_lines() {
        let sql =
            "CREATE TABLE t (\n    a INT REFERENCES foo(id),\n    b INT REFERENCES bar(id)\n);";
        let diags = parse_and_check(sql);
        let fk_lines: Vec<usize> = diags
            .iter()
            .filter(|d| d.message.contains("FOREIGN KEY"))
            .map(|d| d.line)
            .collect();
        assert_eq!(fk_lines.len(), 2, "Expected 2 FK diagnostics: {diags:?}");
        assert_ne!(
            fk_lines[0], fk_lines[1],
            "FK diagnostics should report different lines, got {fk_lines:?}"
        );
    }

    #[test]
    fn multiline_index_still_caught() {
        let sql = "CREATE INDEX idx_orders\n  ON orders(customer_id);";
        let diags = parse_and_check(sql);
        assert!(diags.iter().any(|d| d.message.contains("ASYNC")));
    }

    #[test]
    fn comment_index_not_flagged() {
        let sql = "-- CREATE INDEX idx_foo ON bar(baz);\nSELECT 1;";
        let diags = parse_and_check(sql);
        assert!(!diags.iter().any(|d| d.message.contains("ASYNC")));
    }
}
