use sqlparser::ast::{ColumnOption, DataType, Statement, TableConstraint};

use crate::lint::Diagnostic;

/// Check a statement for DSQL compatibility errors (E001, E003–E005).
pub fn check(stmt: &Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::CreateTable(ct) = stmt {
        // E003/E004/E005: serial types
        for col in &ct.columns {
            if let DataType::Custom(name, _) = &col.data_type {
                let type_str = name.to_string().to_uppercase();
                let (rule, original, replacement) = match type_str.as_str() {
                    "SERIAL" | "SERIAL4" => (
                        "E003",
                        "SERIAL",
                        "INTEGER GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
                    ),
                    "BIGSERIAL" | "SERIAL8" => (
                        "E004",
                        "BIGSERIAL",
                        "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
                    ),
                    "SMALLSERIAL" | "SERIAL2" => (
                        "E005",
                        "SMALLSERIAL",
                        "SMALLINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
                    ),
                    _ => continue,
                };
                diagnostics.push(Diagnostic {
                    line: find_line(raw_sql, &type_str.to_lowercase()),
                    rule_id: rule.to_string(),
                    message: format!(
                        "Column `{}` uses {original}, which is not supported in DSQL.",
                        col.name
                    ),
                    suggestion: format!("Use `{replacement}` instead."),
                    is_error: true,
                });
            }
        }

        // E001: foreign key — column-level REFERENCES
        for col in &ct.columns {
            for opt_def in &col.options {
                if matches!(&opt_def.option, ColumnOption::ForeignKey(_)) {
                    diagnostics.push(Diagnostic {
                        line: find_line(raw_sql, "references"),
                        rule_id: "E001".to_string(),
                        message: format!(
                            "Column `{}` has a FOREIGN KEY (REFERENCES) constraint, which is not supported in DSQL.",
                            col.name
                        ),
                        suggestion: "Remove the REFERENCES clause. Enforce referential integrity in application code.".to_string(),
                        is_error: true,
                    });
                }
            }
        }

        // E001: foreign key — table-level FOREIGN KEY constraint
        for constraint in &ct.constraints {
            if matches!(constraint, TableConstraint::ForeignKey(_)) {
                diagnostics.push(Diagnostic {
                    line: find_line(raw_sql, "foreign key"),
                    rule_id: "E001".to_string(),
                    message: "Table-level FOREIGN KEY constraint is not supported in DSQL."
                        .to_string(),
                    suggestion:
                        "Remove the FOREIGN KEY constraint. Enforce referential integrity in application code."
                            .to_string(),
                    is_error: true,
                });
            }
        }
    }

    check_json_columns(stmt, raw_sql, diagnostics);
    check_truncate(stmt, raw_sql, diagnostics);
    check_temp_table(stmt, raw_sql, diagnostics);
    check_array_columns(stmt, raw_sql, diagnostics);
    check_create_index(raw_sql);
}

/// E006: JSON/JSONB column types are not supported in DSQL.
fn check_json_columns(stmt: &Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::CreateTable(ct) = stmt {
        for col in &ct.columns {
            let type_str = col.data_type.to_string().to_uppercase();
            if matches!(type_str.as_str(), "JSON" | "JSONB") {
                diagnostics.push(Diagnostic {
                    line: find_line(raw_sql, &type_str.to_lowercase()),
                    rule_id: "E006".to_string(),
                    message: format!(
                        "Column `{}` uses {type_str}, which is not supported in DSQL.",
                        col.name
                    ),
                    suggestion: "Use TEXT and serialize with JSON.stringify.".to_string(),
                    is_error: true,
                });
            }
        }
    }
}

/// E007: TRUNCATE is not supported in DSQL.
fn check_truncate(stmt: &Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::Truncate(_) = stmt {
        diagnostics.push(Diagnostic {
            line: find_line(raw_sql, "truncate"),
            rule_id: "E007".to_string(),
            message: "TRUNCATE is not supported in DSQL.".to_string(),
            suggestion: "Use DELETE FROM table_name instead.".to_string(),
            is_error: true,
        });
    }
}

/// E008: Temporary tables are not supported in DSQL.
fn check_temp_table(stmt: &Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::CreateTable(ct) = stmt {
        if ct.temporary {
            diagnostics.push(Diagnostic {
                line: find_line(raw_sql, "temp"),
                rule_id: "E008".to_string(),
                message: "TEMPORARY tables are not supported in DSQL.".to_string(),
                suggestion: "Use regular tables or application-level caching.".to_string(),
                is_error: true,
            });
        }
    }
}

/// E009: Array column types are not supported in DSQL.
fn check_array_columns(stmt: &Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::CreateTable(ct) = stmt {
        for col in &ct.columns {
            let is_array = matches!(&col.data_type, DataType::Array(_))
                || col.data_type.to_string().contains("[]");
            if is_array {
                diagnostics.push(Diagnostic {
                    line: find_line(raw_sql, &col.name.to_string().to_lowercase()),
                    rule_id: "E009".to_string(),
                    message: format!(
                        "Column `{}` uses an array type, which is not supported in DSQL.",
                        col.name
                    ),
                    suggestion: "Use TEXT and store as comma-separated values.".to_string(),
                    is_error: true,
                });
            }
        }
    }
}

/// Stub for E002 (to be implemented in Task 7).
fn check_create_index(_raw_sql: &str) {
    // E002 will be added later
}

/// Find the 1-based line number of the first occurrence of `needle` (case-insensitive).
fn find_line(raw_sql: &str, needle: &str) -> usize {
    let lower = raw_sql.to_lowercase();
    if let Some(pos) = lower.find(needle) {
        raw_sql[..pos].matches('\n').count() + 1
    } else {
        1
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sqlparser::dialect::PostgreSqlDialect;
    use sqlparser::parser::Parser;

    fn parse_and_check(sql: &str) -> Vec<Diagnostic> {
        let dialect = PostgreSqlDialect {};
        let stmts = Parser::parse_sql(&dialect, sql).expect("SQL should parse");
        let mut diags = Vec::new();
        for stmt in &stmts {
            check(stmt, sql, &mut diags);
        }
        diags
    }

    #[test]
    fn test_e001_foreign_key_column_ref() {
        let sql = "CREATE TABLE orders (id INT, customer_id INT REFERENCES customers(id));";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E001"),
            "Expected E001, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e001_foreign_key_table_constraint() {
        let sql = "CREATE TABLE orders (id INT, customer_id INT, FOREIGN KEY (customer_id) REFERENCES customers(id));";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E001"),
            "Expected E001, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e001_no_false_positive() {
        let sql = "CREATE TABLE orders (id INT, customer_id INT);";
        let diags = parse_and_check(sql);
        assert!(
            !diags.iter().any(|d| d.rule_id == "E001"),
            "Did not expect E001, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e003_serial() {
        let sql = "CREATE TABLE users (id SERIAL PRIMARY KEY, name TEXT);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E003"),
            "Expected E003, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e004_bigserial() {
        let sql = "CREATE TABLE users (id BIGSERIAL PRIMARY KEY);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E004"),
            "Expected E004, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e005_smallserial() {
        let sql = "CREATE TABLE users (id SMALLSERIAL PRIMARY KEY);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E005"),
            "Expected E005, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e006_json_column() {
        let sql = "CREATE TABLE t (id INT, data JSON);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E006"),
            "Expected E006, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e006_jsonb_column() {
        let sql = "CREATE TABLE t (id INT, data JSONB);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E006"),
            "Expected E006, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e007_truncate() {
        let sql = "TRUNCATE TABLE orders;";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E007"),
            "Expected E007, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e008_temp_table() {
        let sql = "CREATE TEMP TABLE scratch (id INT);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E008"),
            "Expected E008, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e008_temporary_table() {
        let sql = "CREATE TEMPORARY TABLE scratch (id INT);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E008"),
            "Expected E008, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e009_array_type() {
        let sql = "CREATE TABLE t (id INT, tags TEXT[]);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E009"),
            "Expected E009, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e009_int_array() {
        let sql = "CREATE TABLE t (id INT, scores INT[]);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E009"),
            "Expected E009, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_no_serial_false_positive() {
        let sql =
            "CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);";
        let diags = parse_and_check(sql);
        assert!(
            !diags
                .iter()
                .any(|d| d.rule_id == "E003" || d.rule_id == "E004" || d.rule_id == "E005"),
            "Did not expect serial errors, got: {:?}",
            diags
        );
    }
}
