use regex::Regex;
use sqlparser::ast::{ColumnOption, DataType, Statement, TableConstraint};

use crate::lint::Diagnostic;

/// Check a statement for DSQL compatibility errors (E001, E003–E005).
pub fn check(stmt: &Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::CreateTable(ct) = stmt {
        // E003/E004/E005: serial types
        for col in &ct.columns {
            if let DataType::Custom(name, _) = &col.data_type {
                let type_str = name.to_string().to_uppercase();
                let (rule, original, replacement) = match type_str.as_str() {
                    "SERIAL" | "SERIAL4" => (
                        "E003",
                        "SERIAL",
                        "INTEGER GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
                    ),
                    "BIGSERIAL" | "SERIAL8" => (
                        "E004",
                        "BIGSERIAL",
                        "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
                    ),
                    "SMALLSERIAL" | "SERIAL2" => (
                        "E005",
                        "SMALLSERIAL",
                        "SMALLINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
                    ),
                    _ => continue,
                };
                diagnostics.push(Diagnostic {
                    line: find_line(raw_sql, &type_str.to_lowercase()),
                    rule_id: rule.to_string(),
                    message: format!(
                        "Column `{}` uses {original}, which is not supported in DSQL.",
                        col.name
                    ),
                    suggestion: format!("Use `{replacement}` instead."),
                    is_error: true,
                });
            }
        }

        // E001: foreign key — column-level REFERENCES
        for col in &ct.columns {
            for opt_def in &col.options {
                if matches!(&opt_def.option, ColumnOption::ForeignKey(_)) {
                    diagnostics.push(Diagnostic {
                        line: find_line(raw_sql, "references"),
                        rule_id: "E001".to_string(),
                        message: format!(
                            "Column `{}` has a FOREIGN KEY (REFERENCES) constraint, which is not supported in DSQL.",
                            col.name
                        ),
                        suggestion: "Remove the REFERENCES clause. Enforce referential integrity in application code.".to_string(),
                        is_error: true,
                    });
                }
            }
        }

        // E001: foreign key — table-level FOREIGN KEY constraint
        for constraint in &ct.constraints {
            if matches!(constraint, TableConstraint::ForeignKey(_)) {
                diagnostics.push(Diagnostic {
                    line: find_line(raw_sql, "foreign key"),
                    rule_id: "E001".to_string(),
                    message: "Table-level FOREIGN KEY constraint is not supported in DSQL."
                        .to_string(),
                    suggestion:
                        "Remove the FOREIGN KEY constraint. Enforce referential integrity in application code."
                            .to_string(),
                    is_error: true,
                });
            }
        }
    }

    check_json_columns(stmt, raw_sql, diagnostics);
    check_truncate(stmt, raw_sql, diagnostics);
    check_temp_table(stmt, raw_sql, diagnostics);
    check_array_columns(stmt, raw_sql, diagnostics);
    check_create_index(stmt, raw_sql, diagnostics);
    check_unsupported_statements(stmt, raw_sql, diagnostics);
}

/// E006: JSON/JSONB column types are not supported in DSQL.
fn check_json_columns(stmt: &Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::CreateTable(ct) = stmt {
        for col in &ct.columns {
            let type_str = col.data_type.to_string().to_uppercase();
            if matches!(type_str.as_str(), "JSON" | "JSONB") {
                diagnostics.push(Diagnostic {
                    line: find_line(raw_sql, &type_str.to_lowercase()),
                    rule_id: "E006".to_string(),
                    message: format!(
                        "Column `{}` uses {type_str}, which is not supported in DSQL.",
                        col.name
                    ),
                    suggestion: "Use TEXT and serialize with JSON.stringify.".to_string(),
                    is_error: true,
                });
            }
        }
    }
}

/// E007: TRUNCATE is not supported in DSQL.
fn check_truncate(stmt: &Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::Truncate(_) = stmt {
        diagnostics.push(Diagnostic {
            line: find_line(raw_sql, "truncate"),
            rule_id: "E007".to_string(),
            message: "TRUNCATE is not supported in DSQL.".to_string(),
            suggestion: "Use DELETE FROM table_name instead.".to_string(),
            is_error: true,
        });
    }
}

/// E008: Temporary tables are not supported in DSQL.
fn check_temp_table(stmt: &Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::CreateTable(ct) = stmt {
        if ct.temporary {
            diagnostics.push(Diagnostic {
                line: find_line(raw_sql, "temp"),
                rule_id: "E008".to_string(),
                message: "TEMPORARY tables are not supported in DSQL.".to_string(),
                suggestion: "Use regular tables or application-level caching.".to_string(),
                is_error: true,
            });
        }
    }
}

/// E009: Array column types are not supported in DSQL.
fn check_array_columns(stmt: &Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::CreateTable(ct) = stmt {
        for col in &ct.columns {
            let is_array = matches!(&col.data_type, DataType::Array(_))
                || col.data_type.to_string().contains("[]");
            if is_array {
                diagnostics.push(Diagnostic {
                    line: find_line(raw_sql, &col.name.to_string().to_lowercase()),
                    rule_id: "E009".to_string(),
                    message: format!(
                        "Column `{}` uses an array type, which is not supported in DSQL.",
                        col.name
                    ),
                    suggestion: "Use TEXT and store as comma-separated values.".to_string(),
                    is_error: true,
                });
            }
        }
    }
}

/// E010–E013: Unsupported statements (trigger, extension, partition, functions/procedures).
fn check_unsupported_statements(stmt: &Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    match stmt {
        // E010: CREATE TRIGGER
        Statement::CreateTrigger(_) => {
            diagnostics.push(Diagnostic {
                line: find_line(raw_sql, "create trigger"),
                rule_id: "E010".to_string(),
                message: "CREATE TRIGGER is not supported in DSQL.".to_string(),
                suggestion: "Implement trigger logic in application layer.".to_string(),
                is_error: true,
            });
        }
        // E011: CREATE EXTENSION
        Statement::CreateExtension(_) => {
            diagnostics.push(Diagnostic {
                line: find_line(raw_sql, "create extension"),
                rule_id: "E011".to_string(),
                message: "CREATE EXTENSION is not supported in DSQL.".to_string(),
                suggestion: "Extensions not available in DSQL.".to_string(),
                is_error: true,
            });
        }
        // E012: PARTITION BY in CREATE TABLE
        Statement::CreateTable(ct) if ct.partition_by.is_some() => {
            diagnostics.push(Diagnostic {
                line: find_line(raw_sql, "partition by"),
                rule_id: "E012".to_string(),
                message: "PARTITION BY is not supported in DSQL.".to_string(),
                suggestion: "Omit — DSQL manages distribution automatically.".to_string(),
                is_error: true,
            });
        }
        // E013: CREATE FUNCTION
        Statement::CreateFunction(_) => {
            diagnostics.push(Diagnostic {
                line: find_line(raw_sql, "create function"),
                rule_id: "E013".to_string(),
                message: "CREATE FUNCTION is not supported in DSQL.".to_string(),
                suggestion: "Implement in application layer.".to_string(),
                is_error: true,
            });
        }
        // E013: CREATE PROCEDURE
        Statement::CreateProcedure { .. } => {
            diagnostics.push(Diagnostic {
                line: find_line(raw_sql, "create procedure"),
                rule_id: "E013".to_string(),
                message: "CREATE PROCEDURE is not supported in DSQL.".to_string(),
                suggestion: "Implement in application layer.".to_string(),
                is_error: true,
            });
        }
        _ => {}
    }
}

/// E002: CREATE INDEX must use ASYNC in DSQL.
///
/// Because `ASYNC` is a DSQL-specific keyword that sqlparser doesn't understand,
/// `lint_sql` strips it before parsing.  We therefore check the *original* raw SQL
/// to decide whether ASYNC was present.  If a `CreateIndex` statement's corresponding
/// source text does NOT contain "ASYNC", we emit E002.
fn check_create_index(stmt: &Statement, raw_sql: &str, diagnostics: &mut Vec<Diagnostic>) {
    if let Statement::CreateIndex(ci) = stmt {
        // Find the index name to locate this statement in the original SQL.
        // We look for "CREATE INDEX" (or "CREATE UNIQUE INDEX") near the index name.
        let idx_name = ci
            .name
            .as_ref()
            .map(|n| n.to_string())
            .unwrap_or_default();

        // Search original raw_sql for this CREATE INDEX statement.
        let re = Regex::new(r"(?i)CREATE\s+(UNIQUE\s+)?INDEX\s+(ASYNC\s+)?").unwrap();
        let upper_raw = raw_sql.to_uppercase();

        // Find all CREATE INDEX occurrences and match by index name.
        for m in re.find_iter(raw_sql) {
            let after_match = &raw_sql[m.end()..];
            // Check if this match is followed by our index name.
            let is_our_stmt = if idx_name.is_empty() {
                // Anonymous index — just check if the pattern is there
                true
            } else {
                after_match
                    .trim_start()
                    .to_uppercase()
                    .starts_with(&idx_name.to_uppercase())
            };

            if is_our_stmt {
                let matched = &upper_raw[m.start()..m.end()];
                if !matched.contains("ASYNC") {
                    let line = raw_sql[..m.start()].matches('\n').count() + 1;
                    diagnostics.push(Diagnostic {
                        line,
                        rule_id: "E002".to_string(),
                        message: format!(
                            "CREATE INDEX without ASYNC is not supported in DSQL.{}",
                            if !idx_name.is_empty() {
                                format!(" Index: {idx_name}")
                            } else {
                                String::new()
                            }
                        ),
                        suggestion: "Use `CREATE INDEX ASYNC ...` instead.".to_string(),
                        is_error: true,
                    });
                }
                break;
            }
        }
    }
}

/// Find the 1-based line number of the first occurrence of `needle` (case-insensitive).
fn find_line(raw_sql: &str, needle: &str) -> usize {
    let lower = raw_sql.to_lowercase();
    if let Some(pos) = lower.find(needle) {
        raw_sql[..pos].matches('\n').count() + 1
    } else {
        1
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sqlparser::dialect::PostgreSqlDialect;
    use sqlparser::parser::Parser;

    fn parse_and_check(sql: &str) -> Vec<Diagnostic> {
        let dialect = PostgreSqlDialect {};
        let stmts = Parser::parse_sql(&dialect, sql).expect("SQL should parse");
        let mut diags = Vec::new();
        for stmt in &stmts {
            check(stmt, sql, &mut diags);
        }
        diags
    }

    #[test]
    fn test_e001_foreign_key_column_ref() {
        let sql = "CREATE TABLE orders (id INT, customer_id INT REFERENCES customers(id));";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E001"),
            "Expected E001, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e001_foreign_key_table_constraint() {
        let sql = "CREATE TABLE orders (id INT, customer_id INT, FOREIGN KEY (customer_id) REFERENCES customers(id));";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E001"),
            "Expected E001, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e001_no_false_positive() {
        let sql = "CREATE TABLE orders (id INT, customer_id INT);";
        let diags = parse_and_check(sql);
        assert!(
            !diags.iter().any(|d| d.rule_id == "E001"),
            "Did not expect E001, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e003_serial() {
        let sql = "CREATE TABLE users (id SERIAL PRIMARY KEY, name TEXT);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E003"),
            "Expected E003, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e004_bigserial() {
        let sql = "CREATE TABLE users (id BIGSERIAL PRIMARY KEY);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E004"),
            "Expected E004, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e005_smallserial() {
        let sql = "CREATE TABLE users (id SMALLSERIAL PRIMARY KEY);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E005"),
            "Expected E005, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e006_json_column() {
        let sql = "CREATE TABLE t (id INT, data JSON);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E006"),
            "Expected E006, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e006_jsonb_column() {
        let sql = "CREATE TABLE t (id INT, data JSONB);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E006"),
            "Expected E006, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e007_truncate() {
        let sql = "TRUNCATE TABLE orders;";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E007"),
            "Expected E007, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e008_temp_table() {
        let sql = "CREATE TEMP TABLE scratch (id INT);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E008"),
            "Expected E008, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e008_temporary_table() {
        let sql = "CREATE TEMPORARY TABLE scratch (id INT);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E008"),
            "Expected E008, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e009_array_type() {
        let sql = "CREATE TABLE t (id INT, tags TEXT[]);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E009"),
            "Expected E009, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e009_int_array() {
        let sql = "CREATE TABLE t (id INT, scores INT[]);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E009"),
            "Expected E009, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e010_trigger() {
        let sql = "CREATE TRIGGER my_trigger AFTER INSERT ON orders FOR EACH ROW EXECUTE FUNCTION my_func();";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E010"),
            "Expected E010, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e011_extension() {
        let sql = "CREATE EXTENSION IF NOT EXISTS pgcrypto;";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E011"),
            "Expected E011, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e012_partition_by() {
        let sql = "CREATE TABLE logs (id INT, created_at DATE) PARTITION BY RANGE (created_at);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E012"),
            "Expected E012, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e013_create_function() {
        let sql = "CREATE FUNCTION add(a INT, b INT) RETURNS INT AS $$ SELECT a + b; $$ LANGUAGE SQL;";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E013"),
            "Expected E013, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e002_create_index_no_async() {
        let sql = "CREATE INDEX idx_orders ON orders(customer_id);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E002"),
            "Expected E002, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e002_create_unique_index_no_async() {
        let sql = "CREATE UNIQUE INDEX idx_email ON users(email);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E002"),
            "Expected E002, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e002_create_index_with_async() {
        // This uses lint_sql since ASYNC stripping happens there.
        let sql = "CREATE INDEX ASYNC idx_orders ON orders(customer_id);";
        let diags = crate::lint::lint_sql(sql);
        assert!(
            !diags.iter().any(|d| d.rule_id == "E002"),
            "Did not expect E002, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e002_multiline_create_index() {
        let sql = "CREATE INDEX idx_orders\n  ON orders(customer_id);";
        let diags = parse_and_check(sql);
        assert!(
            diags.iter().any(|d| d.rule_id == "E002"),
            "Expected E002, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_e002_no_false_positive_on_comment() {
        let sql = "-- CREATE INDEX idx_foo ON bar(baz);\nSELECT 1;";
        let diags = parse_and_check(sql);
        assert!(
            !diags.iter().any(|d| d.rule_id == "E002"),
            "Did not expect E002, got: {:?}",
            diags
        );
    }

    #[test]
    fn test_no_serial_false_positive() {
        let sql =
            "CREATE TABLE users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);";
        let diags = parse_and_check(sql);
        assert!(
            !diags
                .iter()
                .any(|d| d.rule_id == "E003" || d.rule_id == "E004" || d.rule_id == "E005"),
            "Did not expect serial errors, got: {:?}",
            diags
        );
    }
}
