//! Collapse / strip the DDL idioms that a `pg_dump` taken from an Aurora DSQL
//! cluster emits but DSQL cannot itself re-ingest.
//!
//! When pg_dump dumps a DSQL table it faithfully reproduces two constructs that
//! the cluster produces internally yet rejects as input:
//!
//! ```sql
//! CREATE TABLE public.t (id bigint NOT NULL, payload json);
//! ALTER TABLE ONLY public.t ALTER COLUMN payload SET COMPRESSION lz4;
//! ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
//!     SEQUENCE NAME public.t_id_seq START WITH 1 INCREMENT BY 1
//!     NO MINVALUE NO MAXVALUE CACHE 1);
//! ```
//!
//! Neither ALTER is accepted by DSQL (`ALTER COLUMN ... ADD GENERATED` and
//! `... SET COMPRESSION` both error), and neither parses in our bundled
//! `sqlparser-dsql` — they surface as `ParseError`/Unfixable. This module
//! rewrites them at the text level so a DSQL→DSQL dump round-trips:
//!
//! - **`ADD GENERATED ... AS IDENTITY`** is folded back onto the matching
//!   `CREATE TABLE` column as an inline
//!   `GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY (CACHE 1)` (mirroring the
//!   SERIAL-idiom collapse). We drop the source's `(SEQUENCE NAME ...)` tail, so
//!   the implicit sequence's name is server-chosen: PostgreSQL auto-names it
//!   `<table>_<column>_seq`, the same name pg_dump used in the dumped
//!   `SEQUENCE NAME`/`setval`. The trailing `SELECT setval('t_id_seq', ...)` is
//!   therefore **left untouched** — it normally lands on that implicit sequence
//!   and advances the counter (no manual reset, unlike the SERIAL path). This
//!   relies on the auto-naming heuristic; if that name were already taken the
//!   server would pick another and the setval would miss.
//! - **`SET COMPRESSION`** is dropped outright. Column compression is a storage
//!   detail DSQL manages itself; the column definition is unchanged.
//!
//! Both passes match the offending ALTER at the TEXT level because it does not
//! parse. Matching is anchored on whole statements (the `parts` list is already
//! split on `;`), so a `;` inside a string literal cannot trip it.

use sqlparser::ast::{ColumnOption, GeneratedAs, Statement};
use sqlparser::dialect::PostgreSqlDialect;
use sqlparser::parser::Parser;

use super::errors::identity_cache_1;
use crate::lint::{Diagnostic, FixResult, LintRule};
use crate::rules::name_match::{
    drop_parts, fold_ident, fold_text_ident, normalize_dotted_identifier, normalize_object_name,
    parse_parts, refs_match, NameRef,
};

/// A detected `ALTER TABLE ... ALTER COLUMN <col> ADD GENERATED <as> AS
/// IDENTITY (...)` whose target `CREATE TABLE` is present earlier in the input.
struct IdentityAdd {
    /// Normalized (schema, table) the ALTER targets.
    table: NameRef,
    /// Column the identity attaches to (PG case-folded).
    column: String,
    /// `ALWAYS` or `BY DEFAULT`, preserved from the source.
    generated_as: GeneratedAs,
    /// Index into `parts` of the (unparseable) ALTER statement to drop.
    alter_part: usize,
}

/// Parse `ALTER TABLE [ONLY] <name> ALTER COLUMN <col> ADD GENERATED
/// { ALWAYS | BY DEFAULT } AS IDENTITY` out of a single statement's text. Stops
/// at `AS IDENTITY` — the `(SEQUENCE NAME ...)` tail (the part sqlparser chokes
/// on) is irrelevant to the collapse. Returns `(table_ref, column, generated_as)`.
///
/// Matched at the text level because the full statement does not parse. The
/// lowercased copy is used only for case-insensitive keyword scanning; every
/// identifier span is sliced out of the original `trimmed` text (offsets agree
/// because `to_ascii_lowercase` is length-preserving for ASCII keywords).
fn parse_identity_add(text: &str) -> Option<(NameRef, String, GeneratedAs)> {
    let (trimmed, lower, table, mut consumed) = scan_alter_column(text)?;

    // Column name runs up to " add generated ".
    let add_gen_off = lower[consumed..].find(" add generated ")?;
    let column = fold_text_ident(&trimmed[consumed..consumed + add_gen_off]);
    consumed += add_gen_off + " add generated ".len();

    // `always as identity` | `by default as identity`.
    let rest = &lower[consumed..];
    let (generated_as, after_kw) = if let Some(after) = rest.strip_prefix("always ") {
        (GeneratedAs::Always, after)
    } else if let Some(after) = rest.strip_prefix("by default ") {
        (GeneratedAs::ByDefault, after)
    } else {
        return None;
    };
    after_kw
        .starts_with("as identity")
        .then_some((table, column, generated_as))
}

/// Whether a statement's text is `ALTER TABLE [ONLY] <name> ALTER COLUMN <col>
/// SET COMPRESSION <method>`. DSQL manages column compression itself, so the
/// statement is dropped wholesale; we only need to recognize the shape.
fn is_set_compression(text: &str) -> bool {
    let Some((_, lower, _, consumed)) = scan_alter_column(text) else {
        return false;
    };
    lower[consumed..].contains(" set compression ")
}

/// Match the `ALTER TABLE [ONLY] <name> ALTER COLUMN` prefix shared by both
/// DSQL-native idioms. Returns the trimmed text, its lowercased copy (for
/// case-insensitive keyword scanning — byte offsets agree because
/// `to_ascii_lowercase` is length-preserving for the ASCII keywords), the
/// normalized table name, and the byte offset just past ` alter column `.
/// `None` if the statement is not an `ALTER TABLE ... ALTER COLUMN`.
fn scan_alter_column(text: &str) -> Option<(String, String, NameRef, usize)> {
    let trimmed = text.trim().trim_end_matches(';').trim().to_string();
    let lower = trimmed.to_ascii_lowercase();

    let mut consumed = "alter table ".len();
    if !lower.starts_with("alter table ") {
        return None;
    }
    if let Some(after) = lower[consumed..].strip_prefix("only ") {
        consumed += lower[consumed..].len() - after.len();
    }
    // Table name runs up to " alter column ".
    let alter_col_off = lower[consumed..].find(" alter column ")?;
    let table = normalize_dotted_identifier(&trimmed[consumed..consumed + alter_col_off]);
    consumed += alter_col_off + " alter column ".len();
    Some((trimmed, lower, table, consumed))
}

/// Collect every `CREATE TABLE` in the parsed statements as a
/// `(NameRef, columns, part_idx)` triple for correlation.
fn create_tables(parts: &[(usize, String)]) -> Vec<(NameRef, Vec<String>, usize)> {
    let (parsed, parsed_to_part) = parse_parts(parts);
    parsed
        .iter()
        .enumerate()
        .filter_map(|(i, stmt)| match stmt {
            Statement::CreateTable(ct) => normalize_object_name(&ct.name).map(|n| {
                let cols = ct.columns.iter().map(|c| fold_ident(&c.name)).collect();
                (n, cols, parsed_to_part[i])
            }),
            _ => None,
        })
        .collect()
}

/// Find every collapsible `ADD GENERATED ... AS IDENTITY` ALTER: one whose
/// target CREATE TABLE (with the named column) appears earlier in `parts`.
/// Cross-file ALTERs without a preceding CREATE TABLE are left for the
/// per-statement Unfixable path.
fn detect_identity_adds(parts: &[(usize, String)]) -> Vec<IdentityAdd> {
    let tables = create_tables(parts);
    let mut found = Vec::new();
    for (part_idx, (_, text)) in parts.iter().enumerate() {
        let Some((table, column, generated_as)) = parse_identity_add(text) else {
            continue;
        };
        if find_target_create_table(&tables, &table, &column, part_idx).is_some() {
            found.push(IdentityAdd {
                table,
                column,
                generated_as,
                alter_part: part_idx,
            });
        }
    }
    found
}

/// The `parts` index of the closest `CREATE TABLE` before `alter_part` that
/// matches `table` and declares `column`, or `None`. Unlike the sibling rules'
/// `pick_best_match` (exact-schema-over-wildcard), this selects by position
/// (`.max()` = closest preceding): pg_dump emits the `CREATE TABLE` immediately
/// before its identity `ALTER`, so positional proximity is the correct anchor.
fn find_target_create_table(
    tables: &[(NameRef, Vec<String>, usize)],
    table: &NameRef,
    column: &str,
    alter_part: usize,
) -> Option<usize> {
    tables
        .iter()
        .filter(|(t, cols, p)| {
            *p < alter_part && refs_match(t, table) && cols.iter().any(|c| c == column)
        })
        .map(|(_, _, p)| *p)
        .max()
}

fn identity_message(column: &str) -> String {
    format!(
        "Column `{column}` is made an identity column via a standalone \
         `ALTER TABLE ... ADD GENERATED ... AS IDENTITY`, which is not supported in DSQL. \
         Define the identity inline on the CREATE TABLE."
    )
}

fn identity_diag(line: usize, statement: String, column: &str, fixed: bool) -> Diagnostic {
    let verb = if fixed { "Moved" } else { "Move" };
    Diagnostic {
        rule: LintRule::IdentityAddGeneratedCollapse,
        line,
        statement,
        message: identity_message(column),
        suggestion: format!(
            "{verb} the GENERATED ... AS IDENTITY clause onto the column in the CREATE TABLE definition."
        ),
        fix_result: FixResult::Fixed(format!(
            "Folded the identity clause for `{column}` into the CREATE TABLE definition."
        )),
    }
}

/// Lint-only pass: surface one `IdentityAddGeneratedCollapse` per collapsible
/// ALTER, without touching the input.
pub(crate) fn check_identity_adds(parts: &[(usize, String)], diagnostics: &mut Vec<Diagnostic>) {
    for add in detect_identity_adds(parts) {
        let (line, stmt) = (parts[add.alter_part].0, parts[add.alter_part].1.clone());
        diagnostics.push(identity_diag(line, stmt, &add.column, false));
    }
}

/// Fix pass: fold each collapsible `ADD GENERATED ... AS IDENTITY` onto its
/// CREATE TABLE column and drop the ALTER statement.
pub(crate) fn fix_identity_adds(
    parts: &mut Vec<(usize, String)>,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let dialect = PostgreSqlDialect {};
    let adds = detect_identity_adds(parts);
    if adds.is_empty() {
        return;
    }
    let tables = create_tables(parts);
    let mut parts_to_remove = Vec::with_capacity(adds.len());

    for add in &adds {
        let Some(ct_part) =
            find_target_create_table(&tables, &add.table, &add.column, add.alter_part)
        else {
            debug_assert!(
                false,
                "no CREATE TABLE for `{}` after detect confirmed it",
                add.column
            );
            continue;
        };

        // Re-parse the CREATE TABLE part and rewrite the target column inline.
        // Both guards below are unreachable (detect already proved parse +
        // column presence); debug_assert! surfaces drift loudly in tests.
        let Ok(mut stmts) = Parser::parse_sql(&dialect, parts[ct_part].1.trim()) else {
            debug_assert!(
                false,
                "re-parse of CREATE TABLE for `{}` failed",
                add.column
            );
            continue;
        };
        let mut rewrote = false;
        for stmt in &mut stmts {
            if let Statement::CreateTable(ct) = stmt {
                for col in &mut ct.columns {
                    if fold_ident(&col.name) == add.column {
                        // Drop any pre-existing GENERATED clause (defensive) so
                        // we never emit a doubled identity, then add ours.
                        col.options
                            .retain(|opt| !matches!(opt.option, ColumnOption::Generated { .. }));
                        col.options.push(identity_cache_1(add.generated_as));
                        rewrote = true;
                    }
                }
            }
        }
        if !rewrote {
            debug_assert!(
                false,
                "column `{}` not in CREATE TABLE after detect confirmed it",
                add.column
            );
            continue;
        }
        parts[ct_part].1 = stmts
            .iter()
            .map(|s| format!("{s:#}"))
            .collect::<Vec<_>>()
            .join(";\n");

        parts_to_remove.push(add.alter_part);
        diagnostics.push(identity_diag(
            parts[add.alter_part].0,
            parts[add.alter_part].1.clone(),
            &add.column,
            true,
        ));
    }

    drop_parts(parts, parts_to_remove);
}

fn compression_message() -> String {
    "ALTER TABLE ... ALTER COLUMN ... SET COMPRESSION is not supported in DSQL. \
     Column compression is managed automatically."
        .to_string()
}

fn compression_diag(line: usize, statement: String, fixed: bool) -> Diagnostic {
    let suggestion = if fixed {
        "Removed the SET COMPRESSION statement; DSQL manages compression."
    } else {
        "Remove the SET COMPRESSION statement; DSQL manages compression."
    };
    Diagnostic {
        rule: LintRule::AlterColumnSetCompressionStrip,
        line,
        statement,
        message: compression_message(),
        suggestion: suggestion.to_string(),
        fix_result: FixResult::Fixed("Removed unsupported SET COMPRESSION statement.".to_string()),
    }
}

/// Lint-only pass: surface one `AlterColumnSetCompressionStrip` per SET
/// COMPRESSION statement.
pub(crate) fn check_set_compression(parts: &[(usize, String)], diagnostics: &mut Vec<Diagnostic>) {
    for (line, text) in parts.iter().filter(|(_, t)| is_set_compression(t)) {
        diagnostics.push(compression_diag(*line, text.clone(), false));
    }
}

/// Fix pass: drop every SET COMPRESSION statement.
pub(crate) fn fix_set_compression(
    parts: &mut Vec<(usize, String)>,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let to_remove: Vec<usize> = parts
        .iter()
        .enumerate()
        .filter(|(_, (_, t))| is_set_compression(t))
        .map(|(i, _)| i)
        .collect();
    for idx in &to_remove {
        diagnostics.push(compression_diag(parts[*idx].0, parts[*idx].1.clone(), true));
    }
    drop_parts(parts, to_remove);
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The real pg_dump-of-DSQL identity ALTER (with the `(SEQUENCE NAME ...)`
    /// tail that sqlparser cannot parse) is recognized at the text level, with
    /// `BY DEFAULT` preserved and the name/column folded.
    #[test]
    fn parse_identity_add_full_pgdump_form() {
        let (table, column, gen) = parse_identity_add(
            "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (\n\
             SEQUENCE NAME public.t_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1)",
        )
        .expect("identity ALTER must parse at text level");
        assert_eq!(table, (Some("public".into()), "t".into()));
        assert_eq!(column, "id");
        assert_eq!(gen, GeneratedAs::ByDefault);
    }

    /// `ALWAYS` is preserved (must not be forced to BY DEFAULT) and `ONLY`,
    /// trailing `;`, and quoted mixed-case identifiers are handled.
    #[test]
    fn parse_identity_add_always_only_quoted() {
        let (table, column, gen) = parse_identity_add(
            "ALTER TABLE ONLY public.\"T\" ALTER COLUMN \"Id\" ADD GENERATED ALWAYS AS IDENTITY (CACHE 1);",
        )
        .expect("identity ALTER must parse");
        assert_eq!(table, (Some("public".into()), "T".into()));
        assert_eq!(column, "Id");
        assert_eq!(gen, GeneratedAs::Always);
    }

    #[test]
    fn parse_identity_add_rejects_non_matching() {
        assert!(parse_identity_add("ALTER TABLE t ALTER COLUMN id SET DEFAULT 0").is_none());
        assert!(parse_identity_add("CREATE TABLE t (id bigint)").is_none());
        // ADD a constraint, not GENERATED.
        assert!(parse_identity_add("ALTER TABLE t ADD CONSTRAINT pk PRIMARY KEY (id)").is_none());
    }

    #[test]
    fn detect_requires_preceding_create_table_with_column() {
        // Matching CREATE TABLE present → detected.
        let parts = vec![
            (1, "CREATE TABLE public.t (id bigint NOT NULL, x text)".into()),
            (
                2,
                "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_id_seq CACHE 1)".into(),
            ),
        ];
        assert_eq!(detect_identity_adds(&parts).len(), 1);

        // No CREATE TABLE (cross-file ALTER) → not collapsed; left for the
        // per-statement Unfixable path.
        let parts = vec![(
            1,
            "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_id_seq CACHE 1)".into(),
        )];
        assert!(detect_identity_adds(&parts).is_empty());

        // CREATE TABLE lacks the named column → not collapsed.
        let parts = vec![
            (1, "CREATE TABLE public.t (other bigint)".into()),
            (
                2,
                "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME s CACHE 1)".into(),
            ),
        ];
        assert!(detect_identity_adds(&parts).is_empty());
    }

    #[test]
    fn fix_folds_identity_inline_and_drops_alter() {
        let mut parts = vec![
            (1, "CREATE TABLE public.t (id bigint NOT NULL, x text)".into()),
            (
                2,
                "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_id_seq START WITH 1 CACHE 1)".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_identity_adds(&mut parts, &mut diags);
        assert_eq!(parts.len(), 1, "the ALTER statement must be dropped");
        let upper = parts[0].1.to_uppercase();
        assert!(
            upper.contains("GENERATED BY DEFAULT AS IDENTITY"),
            "identity must be inline on the CREATE TABLE, got: {}",
            parts[0].1
        );
        assert!(
            upper.contains("CACHE 1"),
            "must emit CACHE 1: {}",
            parts[0].1
        );
        assert_eq!(diags.len(), 1);
        assert_eq!(diags[0].rule, LintRule::IdentityAddGeneratedCollapse);
    }

    #[test]
    fn fix_collapses_multiple_identity_adds_independently() {
        let mut parts = vec![
            (1, "CREATE TABLE public.a (id bigint NOT NULL)".into()),
            (2, "CREATE TABLE public.b (id bigint NOT NULL)".into()),
            (
                3,
                "ALTER TABLE public.a ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.a_id_seq CACHE 1)".into(),
            ),
            (
                4,
                "ALTER TABLE public.b ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME public.b_id_seq CACHE 1)".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_identity_adds(&mut parts, &mut diags);
        // Both ALTERs dropped, both CREATE TABLEs left.
        assert_eq!(
            parts.len(),
            2,
            "both ALTERs must be dropped, got: {parts:?}"
        );
        let a = parts
            .iter()
            .find(|(_, t)| t.contains("public.a"))
            .unwrap()
            .1
            .to_uppercase();
        let b = parts
            .iter()
            .find(|(_, t)| t.contains("public.b"))
            .unwrap()
            .1
            .to_uppercase();
        assert!(a.contains("GENERATED BY DEFAULT AS IDENTITY"), "a: {a}");
        assert!(b.contains("GENERATED ALWAYS AS IDENTITY"), "b: {b}");
        assert_eq!(diags.len(), 2);
    }

    /// If the CREATE TABLE column already carries a GENERATED clause, the fold
    /// must replace it (the defensive `retain`) rather than emit a doubled
    /// identity, and the ALTER's ALWAYS/BY DEFAULT choice wins.
    #[test]
    fn fix_replaces_pre_existing_generated_clause() {
        let mut parts = vec![
            (
                1,
                "CREATE TABLE t (id bigint GENERATED ALWAYS AS IDENTITY)".into(),
            ),
            (
                2,
                "ALTER TABLE t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME s CACHE 1)".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_identity_adds(&mut parts, &mut diags);
        let upper = parts[0].1.to_uppercase();
        assert_eq!(
            upper.matches("GENERATED").count(),
            1,
            "exactly one GENERATED clause must survive, got: {}",
            parts[0].1
        );
        assert!(
            upper.contains("GENERATED BY DEFAULT AS IDENTITY"),
            "the ALTER's BY DEFAULT must win, got: {}",
            parts[0].1
        );
    }

    #[test]
    fn fix_preserves_generated_always() {
        let mut parts = vec![
            (1, "CREATE TABLE t (id bigint NOT NULL)".into()),
            (
                2,
                "ALTER TABLE t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME s CACHE 1)".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_identity_adds(&mut parts, &mut diags);
        assert!(
            parts[0]
                .1
                .to_uppercase()
                .contains("GENERATED ALWAYS AS IDENTITY"),
            "ALWAYS must be preserved, got: {}",
            parts[0].1
        );
    }

    #[test]
    fn set_compression_detected_and_stripped() {
        assert!(is_set_compression(
            "ALTER TABLE ONLY public.t ALTER COLUMN payload SET COMPRESSION lz4;"
        ));
        assert!(is_set_compression(
            "ALTER TABLE t ALTER COLUMN c SET COMPRESSION pglz"
        ));
        // Not a SET COMPRESSION statement.
        assert!(!is_set_compression(
            "ALTER TABLE t ALTER COLUMN c SET DEFAULT 0"
        ));
        assert!(!is_set_compression("CREATE TABLE t (c text)"));

        let mut parts = vec![
            (1, "CREATE TABLE t (c text)".into()),
            (
                2,
                "ALTER TABLE ONLY public.t ALTER COLUMN c SET COMPRESSION lz4".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_set_compression(&mut parts, &mut diags);
        assert_eq!(parts.len(), 1, "SET COMPRESSION must be dropped");
        assert_eq!(diags.len(), 1);
        assert_eq!(diags[0].rule, LintRule::AlterColumnSetCompressionStrip);
    }
}
