//! Collapse / strip the DDL idioms that a `pg_dump` taken from an Aurora DSQL
//! cluster emits but DSQL cannot itself re-ingest.
//!
//! When pg_dump dumps a DSQL table it faithfully reproduces two constructs that
//! the cluster produces internally yet rejects as input:
//!
//! ```sql
//! CREATE TABLE public.t (id bigint NOT NULL, payload json);
//! ALTER TABLE ONLY public.t ALTER COLUMN payload SET COMPRESSION lz4;
//! ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
//!     SEQUENCE NAME public.t_id_seq START WITH 1 INCREMENT BY 1
//!     NO MINVALUE NO MAXVALUE CACHE 1);
//! ```
//!
//! Neither ALTER is accepted by DSQL (`ALTER COLUMN ... ADD GENERATED` and
//! `... SET COMPRESSION` both error), and neither parses in our bundled
//! `sqlparser-dsql` — they surface as `ParseError`/Unfixable. This module
//! rewrites them at the text level so a DSQL→DSQL dump round-trips:
//!
//! - **`ADD GENERATED ... AS IDENTITY`** is folded back onto the matching
//!   `CREATE TABLE` column as an inline
//!   `GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY (CACHE n)`. The source
//!   `CACHE n` is preserved (not forced to `1`) so a tuned `CACHE 65536` isn't
//!   silently downgraded; an out-of-range value is clamped downstream. We drop
//!   the `(SEQUENCE NAME ...)` tail and leave the trailing `setval(...)`: it
//!   lands on the implicit sequence PostgreSQL auto-names `<table>_<column>_seq`
//!   — the same name pg_dump used. When the source name differs (a collision
//!   suffix), that auto-name won't match and the setval misses, so we warn (see
//!   [`setval_may_miss`]).
//! - **`SET COMPRESSION`** is dropped outright. Column compression is a storage
//!   detail DSQL manages itself; the column definition is unchanged.
//!
//! Both passes match the offending ALTER at the TEXT level because it does not
//! parse. Matching is anchored on whole statements (the `parts` list is already
//! split on `;`), so a `;` inside a string literal cannot trip it.

use sqlparser::{
    ast::{ColumnOption, GeneratedAs, Statement},
    dialect::PostgreSqlDialect,
    parser::Parser,
};

use super::errors::identity_with_cache;
use crate::lint::{Diagnostic, FixResult, LintRule};
use crate::rules::name_match::*;

const ALTER_TABLE: &str = "alter table ";
const ONLY: &str = "only ";
const ALTER_COLUMN: &str = " alter column ";
const ADD_GENERATED: &str = " add generated ";
const SET_COMPRESSION: &str = " set compression ";

/// A detected `ALTER TABLE ... ALTER COLUMN <col> ADD GENERATED <as> AS
/// IDENTITY (...)` whose target `CREATE TABLE` is present earlier in the input.
struct IdentityAdd {
    /// Normalized (schema, table) the ALTER targets.
    table: NameRef,
    /// Column the identity attaches to (PG case-folded).
    column: String,
    /// `ALWAYS` or `BY DEFAULT`, preserved from the source.
    generated_as: GeneratedAs,
    /// Source cache, preserved so a tuned `CACHE 65536` isn't reset to 1.
    /// Defaults to 1 when the tail carries no `CACHE`.
    cache: i64,
    /// Bare (schema-stripped, folded) source sequence name; `None` if the tail
    /// names none. Compared against the auto-name to detect a setval miss.
    seq_name: Option<String>,
    /// Index into `parts` of the (unparseable) ALTER statement to drop.
    alter_part: usize,
}

/// The `ALTER TABLE [ONLY] <name> ALTER COLUMN` prefix shared by both idioms,
/// scanned from statement text that does not parse.
struct AlterColumnPrefix<'a> {
    /// Case-preserving statement text (borrowed), for slicing identifier spans.
    original: &'a str,
    /// Lowercased copy, for case-insensitive keyword scanning. Same byte length
    /// as `original` (`to_ascii_lowercase` only remaps ASCII A–Z), so a byte
    /// offset found in one is valid in the other.
    lowered: String,
    /// Normalized table name the ALTER targets.
    table: NameRef,
    /// Byte offset just past ` alter column `, into both `original`/`lowered`.
    col_offset: usize,
}

/// A `CREATE TABLE` located in the input, for correlating an ALTER against it.
struct CreateTableRef {
    table: NameRef,
    /// PG case-folded column names.
    columns: Vec<String>,
    /// Index into `parts`.
    part_idx: usize,
}

/// Parse `ALTER TABLE [ONLY] <name> ALTER COLUMN <col> ADD GENERATED
/// { ALWAYS | BY DEFAULT } AS IDENTITY (SEQUENCE NAME ... CACHE n ...)` into an
/// [`IdentityAdd`] for the statement at `alter_part`. The `(...)` tail doesn't
/// parse in sqlparser, so its `CACHE` / `SEQUENCE NAME` are scanned from text.
fn parse_identity_add(text: &str, alter_part: usize) -> Option<IdentityAdd> {
    let prefix = scan_alter_column(text)?;
    let after_col = &prefix.lowered[prefix.col_offset..];

    let add_gen_off = after_col.find(ADD_GENERATED)?;
    let column =
        fold_text_ident(&prefix.original[prefix.col_offset..prefix.col_offset + add_gen_off]);
    let after_gen_off = prefix.col_offset + add_gen_off + ADD_GENERATED.len();
    let after_gen = &prefix.lowered[after_gen_off..];

    const AS_IDENTITY: &str = "as identity";
    let (generated_as, gen_kw_len) = if after_gen.starts_with("always ") {
        (GeneratedAs::Always, "always ".len())
    } else if after_gen.starts_with("by default ") {
        (GeneratedAs::ByDefault, "by default ".len())
    } else {
        return None;
    };
    if !after_gen[gen_kw_len..].starts_with(AS_IDENTITY) {
        return None;
    }

    // Lowercase preserves byte length, so one offset slices both copies:
    // `lowered` for keyword matching, `original` to keep a quoted name's case.
    let tail_off = after_gen_off + gen_kw_len + AS_IDENTITY.len();
    let cache = parse_cache(&prefix.lowered[tail_off..]).unwrap_or(1);
    let seq_name = parse_sequence_name(&prefix.lowered[tail_off..], &prefix.original[tail_off..]);

    Some(IdentityAdd {
        table: prefix.table,
        column,
        generated_as,
        cache,
        seq_name,
        alter_part,
    })
}

/// `CACHE n` from a lowercased identity tail; `None` if absent or non-integer.
/// pg_dump normally emits `SEQUENCE NAME ... CACHE n` (space-delimited), but with
/// no `SEQUENCE NAME` the tail is the paren-adjacent `(CACHE n)`, so `(` counts as
/// a word boundary too — otherwise that shape silently defaults to `CACHE 1`.
fn parse_cache(tail_lower: &str) -> Option<i64> {
    let after = tail_lower.replace('(', " ");
    let after = after.split(" cache ").nth(1)?;
    after
        .split(|c: char| !c.is_ascii_digit())
        .next()
        .filter(|s| !s.is_empty())
        .and_then(|s| s.parse::<i64>().ok())
}

/// Bare (schema-stripped, folded) name from a `SEQUENCE NAME <name>` clause;
/// `None` if absent. Folded to match the auto-name and setval target.
fn parse_sequence_name(tail_lower: &str, tail_orig: &str) -> Option<String> {
    const SEQ_NAME: &str = "sequence name ";
    let kw_off = tail_lower.find(SEQ_NAME)? + SEQ_NAME.len();
    // Name ends at the first whitespace/`)` outside quotes — the following
    // option keywords are all so delimited.
    let rest = &tail_orig[kw_off..];
    let mut in_quotes = false;
    let mut end = rest.len();
    for (i, ch) in rest.char_indices() {
        match ch {
            '"' => in_quotes = !in_quotes,
            c if !in_quotes && (c.is_whitespace() || c == ')') => {
                end = i;
                break;
            }
            _ => {}
        }
    }
    let raw = rest[..end].trim();
    if raw.is_empty() {
        return None;
    }
    Some(normalize_dotted_identifier(raw).1)
}

fn is_set_compression(text: &str) -> bool {
    scan_alter_column(text).is_some_and(|prefix| {
        // Require SET COMPRESSION right after the column. A `.contains` would
        // also fire on the phrase inside another op's argument (e.g.
        // `SET DEFAULT 'set compression'`), silently deleting that statement.
        let tail = &prefix.lowered[prefix.col_offset..];
        let after_col = skip_identifier(tail);
        tail[after_col..]
            .trim_start()
            .starts_with(SET_COMPRESSION.trim_start())
    })
}

/// Byte offset past a leading (optionally `"`-quoted) identifier in `s`,
/// skipping leading whitespace and ending at the first unquoted whitespace.
fn skip_identifier(s: &str) -> usize {
    let lead_ws = s.len() - s.trim_start().len();
    let mut in_quotes = false;
    for (i, ch) in s[lead_ws..].char_indices() {
        match ch {
            '"' => in_quotes = !in_quotes,
            c if !in_quotes && c.is_whitespace() => return lead_ws + i,
            _ => {}
        }
    }
    s.len()
}

/// `None` unless the statement is an `ALTER TABLE ... ALTER COLUMN`. Matched at
/// the text level because these idioms do not parse.
fn scan_alter_column(text: &str) -> Option<AlterColumnPrefix<'_>> {
    let original = text.trim().trim_end_matches(';').trim();
    let lowered = original.to_ascii_lowercase();

    if !lowered.starts_with(ALTER_TABLE) {
        return None;
    }
    let mut consumed = ALTER_TABLE.len();

    let rest = &lowered[consumed..];
    if rest.starts_with(ONLY) {
        consumed += ONLY.len();
    }

    let rest = &lowered[consumed..];
    let alter_col_off = rest.find(ALTER_COLUMN)?;
    let table = normalize_dotted_identifier(&original[consumed..consumed + alter_col_off]);
    consumed += alter_col_off + ALTER_COLUMN.len();
    Some(AlterColumnPrefix {
        original,
        lowered,
        table,
        col_offset: consumed,
    })
}

/// Collect every `CREATE TABLE` in the input for correlation.
fn create_tables(parts: &[(usize, String)]) -> Vec<CreateTableRef> {
    let (parsed, parsed_to_part) = parse_parts(parts);
    parsed
        .iter()
        .enumerate()
        .filter_map(|(i, stmt)| match stmt {
            Statement::CreateTable(ct) => {
                normalize_object_name(&ct.name).map(|table| CreateTableRef {
                    table,
                    columns: ct.columns.iter().map(|c| fold_ident(&c.name)).collect(),
                    part_idx: parsed_to_part[i],
                })
            }
            _ => None,
        })
        .collect()
}

/// Every collapsible `ADD GENERATED ... AS IDENTITY` ALTER, i.e. one whose
/// target CREATE TABLE (with the named column) appears earlier in `parts`.
/// Cross-file ALTERs without a preceding CREATE TABLE are left for the
/// per-statement Unfixable path.
fn detect_identity_adds(parts: &[(usize, String)]) -> Vec<IdentityAdd> {
    let tables = create_tables(parts);
    parts
        .iter()
        .enumerate()
        .filter_map(|(part_idx, (_, text))| parse_identity_add(text, part_idx))
        .filter(|add| find_target_create_table(&tables, add).is_some())
        .collect()
}

/// The `parts` index of the closest `CREATE TABLE` before the ALTER that matches
/// its table and declares its column. Unlike the sibling rules' `pick_best_match`
/// (exact-schema-over-wildcard), this selects by position (`.max()` = closest
/// preceding): pg_dump emits the `CREATE TABLE` immediately before its identity
/// `ALTER`, so positional proximity is the correct anchor.
fn find_target_create_table(tables: &[CreateTableRef], add: &IdentityAdd) -> Option<usize> {
    tables
        .iter()
        .filter(|ct| {
            ct.part_idx < add.alter_part
                && refs_match(&ct.table, &add.table)
                && ct.columns.contains(&add.column)
        })
        .map(|ct| ct.part_idx)
        .max()
}

fn identity_message(column: &str) -> String {
    format!(
        "Column `{column}` is made an identity column via a standalone \
         `ALTER TABLE ... ADD GENERATED ... AS IDENTITY`, which is not supported in DSQL. \
         Define the identity inline on the CREATE TABLE."
    )
}

/// PostgreSQL's implicit-sequence auto-name for an identity/serial column —
/// `makeObjectName(table, column, "seq")`. Normally `<table>_<column>_seq`, but
/// when that exceeds `NAMEDATALEN-1` (63 bytes) Postgres shaves a byte off the
/// *longer* of table/column until it fits, never the `_seq` suffix. pg_dump emits
/// this truncated name, so the setval-miss check must compare against it (a naive
/// `<table>_<column>_seq` would spuriously mismatch for long names).
fn auto_sequence_name(table: &str, column: &str) -> String {
    const NAMEDATALEN: usize = 64;
    const LABEL: &str = "seq";
    // Overhead: the `_` between table/column plus `_` + the label.
    let avail = NAMEDATALEN - 1 - (1 + 1 + LABEL.len());
    let (mut t, mut c) = (table.len(), column.len());
    while t + c > avail {
        if t > c {
            t -= 1;
        } else {
            c -= 1;
        }
    }
    // Byte-truncate, then back off to a char boundary (Postgres' pg_mbcliplen) so
    // a multibyte folded identifier is never split.
    while !table.is_char_boundary(t) {
        t -= 1;
    }
    while !column.is_char_boundary(c) {
        c -= 1;
    }
    format!("{}_{}_{LABEL}", &table[..t], &column[..c])
}

/// True when the preserved `setval(...)` may miss its target: dropping
/// `SEQUENCE NAME` makes the implicit sequence auto-named per [`auto_sequence_name`],
/// so a source named anything else leaves the counter un-advanced and risks a
/// PK collision on the first insert. No source name → can't tell, don't warn.
fn setval_may_miss(add: &IdentityAdd) -> bool {
    match &add.seq_name {
        Some(name) => *name != auto_sequence_name(&add.table.1, &add.column),
        None => false,
    }
}

fn identity_diag(line: usize, statement: String, add: &IdentityAdd, fixed: bool) -> Diagnostic {
    let column = &add.column;
    let verb = if fixed { "Moved" } else { "Move" };
    let fix_result = if setval_may_miss(add) {
        FixResult::FixedWithWarning(format!(
            "Folded the identity clause for `{column}` into the CREATE TABLE definition. \
             The source sequence `{}` does not match the auto-generated name \
             `{}` that DSQL will assign to the inline identity, so the dump's \
             trailing `setval(...)` may not advance this column's counter — verify the \
             next insert does not collide on the primary key, and reset the counter if needed.",
            add.seq_name.as_deref().unwrap_or_default(),
            auto_sequence_name(&add.table.1, column),
        ))
    } else {
        FixResult::Fixed(format!(
            "Folded the identity clause for `{column}` into the CREATE TABLE definition."
        ))
    };
    Diagnostic {
        rule: LintRule::IdentityAddGeneratedCollapse,
        line,
        statement,
        message: identity_message(column),
        suggestion: format!(
            "{verb} the GENERATED ... AS IDENTITY clause onto the column in the CREATE TABLE definition."
        ),
        fix_result,
    }
}

/// Lint-only pass: surface one `IdentityAddGeneratedCollapse` per collapsible
/// ALTER, without touching the input.
pub(crate) fn check_identity_adds(parts: &[(usize, String)], diagnostics: &mut Vec<Diagnostic>) {
    for add in detect_identity_adds(parts) {
        let (line, stmt) = (parts[add.alter_part].0, parts[add.alter_part].1.clone());
        diagnostics.push(identity_diag(line, stmt, &add, false));
    }
}

/// Fix pass: fold each collapsible `ADD GENERATED ... AS IDENTITY` onto its
/// CREATE TABLE column and drop the ALTER statement.
pub(crate) fn fix_identity_adds(
    parts: &mut Vec<(usize, String)>,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let dialect = PostgreSqlDialect {};
    let adds = detect_identity_adds(parts);
    if adds.is_empty() {
        return;
    }
    let tables = create_tables(parts);
    let mut parts_to_remove = Vec::with_capacity(adds.len());

    for add in &adds {
        let Some(ct_part) = find_target_create_table(&tables, add) else {
            debug_assert!(
                false,
                "no CREATE TABLE for `{}` after detect confirmed it",
                add.column
            );
            continue;
        };

        // The two guards below are unreachable — detect already proved this
        // part parses and contains the column. debug_assert! turns any future
        // drift into a loud test failure rather than a silently skipped fix.
        let Ok(mut stmts) = Parser::parse_sql(&dialect, parts[ct_part].1.trim()) else {
            debug_assert!(
                false,
                "re-parse of CREATE TABLE for `{}` failed",
                add.column
            );
            continue;
        };
        let mut rewrote = false;
        for stmt in &mut stmts {
            if let Statement::CreateTable(ct) = stmt {
                for col in &mut ct.columns {
                    if fold_ident(&col.name) == add.column {
                        // Defensive: drop any pre-existing GENERATED clause so a
                        // column that already declares one never doubles up.
                        col.options
                            .retain(|opt| !matches!(opt.option, ColumnOption::Generated { .. }));
                        col.options
                            .push(identity_with_cache(add.generated_as, add.cache));
                        rewrote = true;
                    }
                }
            }
        }
        if !rewrote {
            debug_assert!(
                false,
                "column `{}` not in CREATE TABLE after detect confirmed it",
                add.column
            );
            continue;
        }
        parts[ct_part].1 = stmts
            .iter()
            .map(|s| format!("{s:#}"))
            .collect::<Vec<_>>()
            .join(";\n");

        parts_to_remove.push(add.alter_part);
        diagnostics.push(identity_diag(
            parts[add.alter_part].0,
            parts[add.alter_part].1.clone(),
            add,
            true,
        ));
    }

    drop_parts(parts, parts_to_remove);
}

fn compression_message() -> String {
    "ALTER TABLE ... ALTER COLUMN ... SET COMPRESSION is not supported in DSQL. \
     Column compression is managed automatically."
        .to_string()
}

fn compression_diag(line: usize, statement: String, fixed: bool) -> Diagnostic {
    let suggestion = if fixed {
        "Removed the SET COMPRESSION statement; DSQL manages compression."
    } else {
        "Remove the SET COMPRESSION statement; DSQL manages compression."
    };
    Diagnostic {
        rule: LintRule::AlterColumnSetCompressionStrip,
        line,
        statement,
        message: compression_message(),
        suggestion: suggestion.to_string(),
        fix_result: FixResult::Fixed("Removed unsupported SET COMPRESSION statement.".to_string()),
    }
}

/// Lint-only pass: surface one `AlterColumnSetCompressionStrip` per SET
/// COMPRESSION statement.
pub(crate) fn check_set_compression(parts: &[(usize, String)], diagnostics: &mut Vec<Diagnostic>) {
    for (line, text) in parts.iter().filter(|(_, t)| is_set_compression(t)) {
        diagnostics.push(compression_diag(*line, text.clone(), false));
    }
}

/// Fix pass: drop every SET COMPRESSION statement.
pub(crate) fn fix_set_compression(
    parts: &mut Vec<(usize, String)>,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let to_remove: Vec<usize> = parts
        .iter()
        .enumerate()
        .filter(|(_, (_, t))| is_set_compression(t))
        .map(|(i, _)| i)
        .collect();
    for idx in &to_remove {
        diagnostics.push(compression_diag(parts[*idx].0, parts[*idx].1.clone(), true));
    }
    drop_parts(parts, to_remove);
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The real pg_dump-of-DSQL identity ALTER (with the `(SEQUENCE NAME ...)`
    /// tail that sqlparser cannot parse) is recognized at the text level, with
    /// `BY DEFAULT` preserved and the name/column folded.
    #[test]
    fn parse_identity_add_full_pgdump_form() {
        let add = parse_identity_add(
            "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (\n\
             SEQUENCE NAME public.t_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1)",
            0,
        )
        .expect("identity ALTER must parse at text level");
        assert_eq!(add.table, (Some("public".into()), "t".into()));
        assert_eq!(add.column, "id");
        assert_eq!(add.generated_as, GeneratedAs::ByDefault);
        assert_eq!(add.cache, 1);
        assert_eq!(add.seq_name.as_deref(), Some("t_id_seq"));
    }

    /// L1: a tuned source `CACHE 65536` is read from the tail, not forced to 1.
    #[test]
    fn parse_identity_add_preserves_source_cache() {
        let add = parse_identity_add(
            "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (\n\
             SEQUENCE NAME public.t_id_seq INCREMENT BY 1 CACHE 65536)",
            0,
        )
        .expect("must parse");
        assert_eq!(add.cache, 65536);
    }

    /// A tail with no `CACHE` clause defaults to 1 (the safe DSQL default).
    #[test]
    fn parse_identity_add_defaults_cache_when_absent() {
        let add = parse_identity_add(
            "ALTER TABLE t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME s)",
            0,
        )
        .expect("must parse");
        assert_eq!(add.cache, 1);
        assert_eq!(add.seq_name.as_deref(), Some("s"));
    }

    /// L1: a preserved high-throughput cache round-trips onto the CREATE TABLE
    /// rather than being silently downgraded to `CACHE 1`.
    #[test]
    fn fix_preserves_high_throughput_cache() {
        let mut parts = vec![
            (1, "CREATE TABLE public.t (id bigint NOT NULL)".into()),
            (
                2,
                "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_id_seq CACHE 65536)".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_identity_adds(&mut parts, &mut diags);
        assert!(
            parts[0].1.contains("65536"),
            "source CACHE 65536 must be preserved, got: {}",
            parts[0].1
        );
    }

    /// L2: when the source `SEQUENCE NAME` matches the auto-name DSQL will pick
    /// (`<table>_<column>_seq`), the collapse is a plain `Fixed` — the trailing
    /// setval lands correctly, no warning needed.
    #[test]
    fn fix_setval_match_is_plain_fixed() {
        let mut parts = vec![
            (1, "CREATE TABLE public.t (id bigint NOT NULL)".into()),
            (
                2,
                "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_id_seq CACHE 1)".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_identity_adds(&mut parts, &mut diags);
        assert_eq!(diags.len(), 1);
        assert!(
            matches!(diags[0].fix_result, FixResult::Fixed(_)),
            "matching sequence name must not warn, got: {:?}",
            diags[0].fix_result
        );
    }

    /// L2: when the source sequence name does NOT match the auto-name (e.g. a
    /// `_seq1` collision suffix), the preserved setval would miss — emit a
    /// `FixedWithWarning` so the silent PK-collision risk is surfaced.
    #[test]
    fn fix_setval_mismatch_warns() {
        let mut parts = vec![
            (1, "CREATE TABLE public.t (id bigint NOT NULL)".into()),
            (
                2,
                "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_id_seq1 CACHE 1)".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_identity_adds(&mut parts, &mut diags);
        assert_eq!(diags.len(), 1);
        let warning = match &diags[0].fix_result {
            FixResult::FixedWithWarning(w) => w,
            other => panic!("expected FixedWithWarning, got: {other:?}"),
        };
        assert!(
            warning.contains("t_id_seq1") && warning.contains("t_id_seq"),
            "warning must name both the source and auto-generated sequence: {warning}"
        );
    }

    /// L2: for a long table name, pg_dump emits the *truncated* implicit-sequence
    /// auto-name (Postgres' `makeObjectName`), so `setval_may_miss` must compare
    /// against that truncated name — not the raw `<table>_<column>_seq` — or it
    /// fires a spurious warning on every long identity.
    #[test]
    fn fix_setval_match_with_truncated_auto_name_is_plain_fixed() {
        // 58-char table: raw `<table>_id_seq` is 65 bytes (> 63), so Postgres
        // truncates the table component; pg_dump's SEQUENCE NAME carries that.
        let table = format!("public.{}", "t".repeat(58));
        let bare = "t".repeat(58);
        let auto = super::auto_sequence_name(&bare, "id");
        assert!(auto.len() <= 63 && auto.ends_with("_seq"));
        let mut parts = vec![
            (1, format!("CREATE TABLE {table} (id bigint NOT NULL)")),
            (
                2,
                format!(
                    "ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.{auto} CACHE 1)"
                ),
            ),
        ];
        let mut diags = Vec::new();
        fix_identity_adds(&mut parts, &mut diags);
        assert_eq!(diags.len(), 1);
        assert!(
            matches!(diags[0].fix_result, FixResult::Fixed(_)),
            "truncated auto-name must match (no warning), got: {:?}",
            diags[0].fix_result
        );
    }

    /// `ALWAYS` is preserved (must not be forced to BY DEFAULT) and `ONLY`,
    /// trailing `;`, and quoted mixed-case identifiers are handled.
    #[test]
    fn parse_identity_add_always_only_quoted() {
        let add = parse_identity_add(
            "ALTER TABLE ONLY public.\"T\" ALTER COLUMN \"Id\" ADD GENERATED ALWAYS AS IDENTITY (CACHE 1);",
            0,
        )
        .expect("identity ALTER must parse");
        assert_eq!(add.table, (Some("public".into()), "T".into()));
        assert_eq!(add.column, "Id");
        assert_eq!(add.generated_as, GeneratedAs::Always);
        assert_eq!(add.cache, 1);
    }

    /// `parse_cache` must read the paren-adjacent `(CACHE n)` form (no preceding
    /// `SEQUENCE NAME`, so `(` directly abuts `CACHE`) — otherwise it silently
    /// defaults to `CACHE 1`, re-introducing the L1 downgrade for that shape.
    #[test]
    fn parse_identity_add_cache_adjacent_to_paren() {
        let add = parse_identity_add(
            "ALTER TABLE t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (CACHE 65536)",
            0,
        )
        .expect("must parse");
        assert_eq!(add.cache, 65536);
    }

    #[test]
    fn parse_identity_add_rejects_non_matching() {
        assert!(parse_identity_add("ALTER TABLE t ALTER COLUMN id SET DEFAULT 0", 0).is_none());
        assert!(parse_identity_add("CREATE TABLE t (id bigint)", 0).is_none());
        // ADD a constraint, not GENERATED.
        assert!(
            parse_identity_add("ALTER TABLE t ADD CONSTRAINT pk PRIMARY KEY (id)", 0).is_none()
        );
    }

    #[test]
    fn detect_requires_preceding_create_table_with_column() {
        // Matching CREATE TABLE present → detected.
        let parts = vec![
            (1, "CREATE TABLE public.t (id bigint NOT NULL, x text)".into()),
            (
                2,
                "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_id_seq CACHE 1)".into(),
            ),
        ];
        assert_eq!(detect_identity_adds(&parts).len(), 1);

        // No CREATE TABLE (cross-file ALTER) → not collapsed; left for the
        // per-statement Unfixable path.
        let parts = vec![(
            1,
            "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_id_seq CACHE 1)".into(),
        )];
        assert!(detect_identity_adds(&parts).is_empty());

        // CREATE TABLE lacks the named column → not collapsed.
        let parts = vec![
            (1, "CREATE TABLE public.t (other bigint)".into()),
            (
                2,
                "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME s CACHE 1)".into(),
            ),
        ];
        assert!(detect_identity_adds(&parts).is_empty());
    }

    #[test]
    fn fix_folds_identity_inline_and_drops_alter() {
        let mut parts = vec![
            (1, "CREATE TABLE public.t (id bigint NOT NULL, x text)".into()),
            (
                2,
                "ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.t_id_seq START WITH 1 CACHE 1)".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_identity_adds(&mut parts, &mut diags);
        assert_eq!(parts.len(), 1, "the ALTER statement must be dropped");
        let upper = parts[0].1.to_uppercase();
        assert!(
            upper.contains("GENERATED BY DEFAULT AS IDENTITY"),
            "identity must be inline on the CREATE TABLE, got: {}",
            parts[0].1
        );
        assert!(
            upper.contains("CACHE 1"),
            "must emit CACHE 1: {}",
            parts[0].1
        );
        assert_eq!(diags.len(), 1);
        assert_eq!(diags[0].rule, LintRule::IdentityAddGeneratedCollapse);
    }

    #[test]
    fn fix_collapses_multiple_identity_adds_independently() {
        let mut parts = vec![
            (1, "CREATE TABLE public.a (id bigint NOT NULL)".into()),
            (2, "CREATE TABLE public.b (id bigint NOT NULL)".into()),
            (
                3,
                "ALTER TABLE public.a ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.a_id_seq CACHE 1)".into(),
            ),
            (
                4,
                "ALTER TABLE public.b ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME public.b_id_seq CACHE 1)".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_identity_adds(&mut parts, &mut diags);
        // Both ALTERs dropped, both CREATE TABLEs left.
        assert_eq!(
            parts.len(),
            2,
            "both ALTERs must be dropped, got: {parts:?}"
        );
        let a = parts
            .iter()
            .find(|(_, t)| t.contains("public.a"))
            .unwrap()
            .1
            .to_uppercase();
        let b = parts
            .iter()
            .find(|(_, t)| t.contains("public.b"))
            .unwrap()
            .1
            .to_uppercase();
        assert!(a.contains("GENERATED BY DEFAULT AS IDENTITY"), "a: {a}");
        assert!(b.contains("GENERATED ALWAYS AS IDENTITY"), "b: {b}");
        assert_eq!(diags.len(), 2);
    }

    /// If the CREATE TABLE column already carries a GENERATED clause, the fold
    /// must replace it (the defensive `retain`) rather than emit a doubled
    /// identity, and the ALTER's ALWAYS/BY DEFAULT choice wins.
    #[test]
    fn fix_replaces_pre_existing_generated_clause() {
        let mut parts = vec![
            (
                1,
                "CREATE TABLE t (id bigint GENERATED ALWAYS AS IDENTITY)".into(),
            ),
            (
                2,
                "ALTER TABLE t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME s CACHE 1)".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_identity_adds(&mut parts, &mut diags);
        let upper = parts[0].1.to_uppercase();
        assert_eq!(
            upper.matches("GENERATED").count(),
            1,
            "exactly one GENERATED clause must survive, got: {}",
            parts[0].1
        );
        assert!(
            upper.contains("GENERATED BY DEFAULT AS IDENTITY"),
            "the ALTER's BY DEFAULT must win, got: {}",
            parts[0].1
        );
    }

    #[test]
    fn fix_preserves_generated_always() {
        let mut parts = vec![
            (1, "CREATE TABLE t (id bigint NOT NULL)".into()),
            (
                2,
                "ALTER TABLE t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (SEQUENCE NAME s CACHE 1)".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_identity_adds(&mut parts, &mut diags);
        assert!(
            parts[0]
                .1
                .to_uppercase()
                .contains("GENERATED ALWAYS AS IDENTITY"),
            "ALWAYS must be preserved, got: {}",
            parts[0].1
        );
    }

    #[test]
    fn set_compression_detected_and_stripped() {
        assert!(is_set_compression(
            "ALTER TABLE ONLY public.t ALTER COLUMN payload SET COMPRESSION lz4;"
        ));
        assert!(is_set_compression(
            "ALTER TABLE t ALTER COLUMN c SET COMPRESSION pglz"
        ));
        // Not a SET COMPRESSION statement.
        assert!(!is_set_compression(
            "ALTER TABLE t ALTER COLUMN c SET DEFAULT 0"
        ));
        assert!(!is_set_compression("CREATE TABLE t (c text)"));
        // L3: the phrase only appears inside another op's argument — must NOT
        // be treated as a SET COMPRESSION statement (would silently delete it).
        assert!(!is_set_compression(
            "ALTER TABLE t ALTER COLUMN c SET DEFAULT 'set compression lz4'"
        ));
        // Quoted column name whose value embeds the phrase must not false-match.
        assert!(!is_set_compression(
            "ALTER TABLE t ALTER COLUMN \"weird set compression col\" SET DEFAULT 0"
        ));
        // Quoted column name still matches a genuine SET COMPRESSION.
        assert!(is_set_compression(
            "ALTER TABLE t ALTER COLUMN \"My Col\" SET COMPRESSION lz4"
        ));

        let mut parts = vec![
            (1, "CREATE TABLE t (c text)".into()),
            (
                2,
                "ALTER TABLE ONLY public.t ALTER COLUMN c SET COMPRESSION lz4".into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_set_compression(&mut parts, &mut diags);
        assert_eq!(parts.len(), 1, "SET COMPRESSION must be dropped");
        assert_eq!(diags.len(), 1);
        assert_eq!(diags[0].rule, LintRule::AlterColumnSetCompressionStrip);
    }
}
