//! Detection AND collapse of the pg_dump "SERIAL idiom".
//!
//! A real PostgreSQL `pg_dump` expands a `SERIAL`/`bigserial` column into four
//! separate statements:
//!
//! ```sql
//! CREATE TABLE public.t (id integer NOT NULL, x text);
//! CREATE SEQUENCE public.t_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
//! ALTER SEQUENCE public.t_id_seq OWNED BY public.t.id;
//! ALTER TABLE ONLY public.t ALTER COLUMN id SET DEFAULT nextval('public.t_id_seq'::regclass);
//! ```
//!
//! ## Why collapse?
//! DSQL accepts `CREATE SEQUENCE ... CACHE 1` and `ALTER SEQUENCE ... OWNED BY`
//! at the executor level, but `ALTER TABLE ... ALTER COLUMN ... SET DEFAULT
//! nextval(...)` is rejected outright. On top of that, our bundled parser
//! (`sqlparser-dsql 0.62.0`) cannot parse `ALTER SEQUENCE` at all, so the
//! OWNED BY line surfaces as a `ParseError` even though the cluster would
//! accept it. The cleaner DSQL-idiomatic shape is a single inline
//! `BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)` column, which is what
//! this module collapses the four-statement quartet into.
//!
//! This module exposes three entry points used by the lint engine:
//! - [`detect_serial_idioms`] (pure, AST-only) — finds idioms across a parsed
//!   statement list and returns structured info pointing at each piece.
//! - [`check_serial_idioms`] (lint pass) — surfaces a single
//!   `SerialSequenceIdiom` diagnostic per detected idiom, without touching input.
//! - [`fix_serial_idioms`] (fix pass) — rewrites the CREATE TABLE column to an
//!   inline `BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)` and removes the
//!   redundant CREATE SEQUENCE / SET DEFAULT statements (and the unparseable
//!   `ALTER SEQUENCE ... OWNED BY` line, matched by text).
//!
//! ## Index space
//! Detection operates only on the PARSEABLE statements. sqlparser-dsql 0.62.0
//! does not support `ALTER SEQUENCE` at all (the keyword is rejected before any
//! arm — `OWNED BY`, `RESTART`, etc. — is considered), so the detection function
//! receives only the successfully-parsed statements (CREATE TABLE, CREATE
//! SEQUENCE, ALTER TABLE). Every index in [`SerialIdiom`]
//! (`create_table_index`, `redundant_indices`) is an index into the `stmts`
//! slice handed to [`detect_serial_idioms`]; the lint and fix passes here
//! translate those back to indices into the original `parts` list via a
//! `parsed_to_part` mapping built by [`parse_parts`].

use sqlparser::ast::{
    AlterColumnOperation, AlterTableOperation, ColumnOption, DataType, Expr, FunctionArg,
    FunctionArgExpr, FunctionArguments, Ident, ObjectName, Statement, Value, ValueWithSpan,
};
use sqlparser::dialect::PostgreSqlDialect;
use sqlparser::parser::Parser;

use super::errors::identity_by_default_cache_1;
use crate::lint::{Diagnostic, FixResult, LintRule};

/// A normalized object reference: `(optional schema, name)` with quoting and
/// `::regclass` casts stripped, used to correlate the idiom's pieces. Names are
/// PG-folded — unquoted segments are lowercased; quoted segments keep their
/// original case — so a `NameRef` can be compared with byte-equal `==` and
/// still respect PostgreSQL's identifier-case rules.
type NameRef = (Option<String>, String);

/// PG case-folding for an `Ident` parsed by sqlparser. Unquoted identifiers
/// fold to lowercase (PostgreSQL's documented rule); quoted identifiers keep
/// their case verbatim. Mirrors what the server does at parse time.
fn fold_ident(ident: &Ident) -> String {
    if ident.quote_style.is_some() {
        ident.value.clone()
    } else {
        ident.value.to_ascii_lowercase()
    }
}

/// PG case-folding for a single textual identifier segment (no dots). If the
/// segment is wrapped in `"..."` the inner value is preserved verbatim;
/// otherwise it is lowercased. Used by the text-level `OWNED BY` matcher and
/// by `nextval('...')`-string parsing where we don't have an `Ident` to read.
fn fold_text_ident(segment: &str) -> String {
    let trimmed = segment.trim();
    if let Some(inner) = trimmed.strip_prefix('"').and_then(|s| s.strip_suffix('"')) {
        inner.to_string()
    } else {
        trimmed.to_ascii_lowercase()
    }
}

/// `rsplit_once('.')` but skips dots that fall inside `"..."`-quoted
/// identifier segments. Used so a sequence named `"my.seq"` is not mis-split
/// into schema=`"my` / name=`seq"`.
fn rsplit_dot_outside_quotes(s: &str) -> Option<(&str, &str)> {
    let bytes = s.as_bytes();
    let mut in_quotes = false;
    let mut last_dot: Option<usize> = None;
    for (i, b) in bytes.iter().enumerate() {
        match b {
            b'"' => in_quotes = !in_quotes,
            b'.' if !in_quotes => last_dot = Some(i),
            _ => {}
        }
    }
    last_dot.map(|i| (&s[..i], &s[i + 1..]))
}

/// A detected pg_dump SERIAL idiom: a CREATE TABLE column whose auto-increment
/// is wired up via a separate CREATE SEQUENCE + ALTER COLUMN SET DEFAULT nextval.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct SerialIdiom {
    /// Normalized (schema, table) of the CREATE TABLE.
    pub table: NameRef,
    /// Column name that should become an identity column.
    pub column: String,
    /// Normalized (schema, sequence_name).
    pub sequence: NameRef,
    /// Index (into the input statement slice) of the CREATE TABLE. The
    /// CREATE TABLE is rewritten (not removed), so it is tracked separately.
    pub create_table_index: usize,
    /// Indices (into the input statement slice) of the statements that make up
    /// the rest of the idiom and will later be removed: the CREATE SEQUENCE and
    /// the ALTER COLUMN SET DEFAULT.
    pub redundant_indices: Vec<usize>,
}

/// Normalize an `ObjectName` to `(Option<schema>, name)`, stripping quoting.
///
/// - 1 part  -> `(None, name)`
/// - 2 parts -> `(Some(schema), name)`
/// - 3+ parts -> the last two parts are treated as `(schema, name)` (handles
///   `db.schema.table` by keeping the trailing schema-qualified pair).
fn normalize_object_name(name: &ObjectName) -> Option<NameRef> {
    let folded: Vec<String> = name
        .0
        .iter()
        .filter_map(|part| part.as_ident())
        .map(fold_ident)
        .collect();
    match folded.as_slice() {
        [] => None,
        [n] => Some((None, n.clone())),
        [.., schema, n] => Some((Some(schema.clone()), n.clone())),
    }
}

/// Two normalized references match if their names are equal AND their schemas
/// agree where both are present. A missing schema on either side is treated as
/// a wildcard (pg_dump emits `public.t` in one place and `t` in another).
fn refs_match(a: &NameRef, b: &NameRef) -> bool {
    if a.1 != b.1 {
        return false;
    }
    match (&a.0, &b.0) {
        (Some(s1), Some(s2)) => s1 == s2,
        _ => true,
    }
}

/// Find the best `refs_match`-compatible candidate for `target` in `items`,
/// preferring an exact-schema match (both sides present and equal) over a
/// wildcard match (one side missing a schema). `key` projects each candidate
/// to its `NameRef`; `extra` is an additional predicate the candidate must
/// also satisfy (e.g. "the table's columns include the one we're wiring").
///
/// Why preference matters: if a hand-edited dump has both `CREATE TABLE t` and
/// `CREATE TABLE other.t`, a SET DEFAULT naming `other.t.id` should correlate
/// with the qualified one, not the first wildcard hit (the unqualified `t`).
fn pick_best_match<'a, T>(
    items: &'a [T],
    target: &NameRef,
    key: impl Fn(&'a T) -> &'a NameRef,
    extra: impl Fn(&'a T) -> bool,
) -> Option<&'a T> {
    let mut wildcard: Option<&'a T> = None;
    for item in items {
        let candidate = key(item);
        if !refs_match(candidate, target) || !extra(item) {
            continue;
        }
        // Exact: both sides have schemas and they agree (schemas already
        // proven equal by refs_match).
        if candidate.0.is_some() && target.0.is_some() {
            return Some(item);
        }
        // Wildcard: one side is missing a schema. Remember the FIRST hit and
        // keep scanning for an exact match that may appear later in the list.
        if wildcard.is_none() {
            wildcard = Some(item);
        }
    }
    wildcard
}

/// Extract the referenced sequence name from a `nextval('seq'::regclass)` /
/// `nextval('seq')` expression. Returns the unwrapped, normalized sequence ref,
/// or `None` if the expression is not a recognizable `nextval(...)` call.
fn extract_nextval_sequence(expr: &Expr) -> Option<NameRef> {
    let Expr::Function(func) = expr else {
        return None;
    };
    // Function name must be `nextval` (case-insensitive), unqualified or
    // schema-qualified (e.g. `pg_catalog.nextval`).
    let fn_name = func.name.0.last().and_then(|p| p.as_ident())?;
    if !fn_name.value.eq_ignore_ascii_case("nextval") {
        return None;
    }

    let FunctionArguments::List(list) = &func.args else {
        return None;
    };
    let [FunctionArg::Unnamed(FunctionArgExpr::Expr(arg))] = list.args.as_slice() else {
        return None;
    };

    // The argument is the sequence name as a single-quoted string, possibly
    // wrapped in a `::regclass` cast.
    let str_expr = match arg {
        Expr::Cast { expr, .. } => expr.as_ref(),
        other => other,
    };
    if let Expr::Value(ValueWithSpan {
        value: Value::SingleQuotedString(s),
        ..
    }) = str_expr
    {
        Some(normalize_dotted_identifier(s))
    } else {
        None
    }
}

/// Detect all SERIAL idioms across a parsed statement list.
///
/// Reports an idiom only when ALL three linked pieces are present:
/// a `CREATE TABLE` for table T with column C, a
/// `CREATE SEQUENCE S`, and an
/// `ALTER TABLE T ALTER COLUMN C SET DEFAULT nextval('S'...)`. If any piece is
/// missing the candidate is dropped (it cannot be safely collapsed).
pub(crate) fn detect_serial_idioms(stmts: &[Statement]) -> Vec<SerialIdiom> {
    // CREATE TABLE: normalized (schema, table) -> (index, columns).
    let mut tables: Vec<(NameRef, usize, Vec<String>)> = Vec::new();
    // CREATE SEQUENCE: normalized (schema, name) -> index.
    let mut sequences: Vec<(NameRef, usize)> = Vec::new();
    // SET DEFAULT nextval: (table_ref, column, sequence_ref, index).
    let mut set_defaults: Vec<(NameRef, String, NameRef, usize)> = Vec::new();

    for (idx, stmt) in stmts.iter().enumerate() {
        match stmt {
            Statement::CreateTable(ct) => {
                if let Some(table_ref) = normalize_object_name(&ct.name) {
                    let cols = ct.columns.iter().map(|c| c.name.value.clone()).collect();
                    tables.push((table_ref, idx, cols));
                }
            }
            Statement::CreateSequence { name, .. } => {
                if let Some(seq_ref) = normalize_object_name(name) {
                    sequences.push((seq_ref, idx));
                }
            }
            Statement::AlterTable(alter) => {
                let Some(table_ref) = normalize_object_name(&alter.name) else {
                    continue;
                };
                // Only consider ALTER TABLEs whose sole operation is the SET DEFAULT
                // we are about to remove. With multiple operations the part can't be
                // dropped wholesale (we'd lose siblings like ADD CONSTRAINT or
                // SET NOT NULL); the existing per-statement
                // `AtUnsupportedAlterColumnSetDefault` rule still flags it Unfixable.
                if alter.operations.len() != 1 {
                    continue;
                }
                if let AlterTableOperation::AlterColumn {
                    column_name,
                    op: AlterColumnOperation::SetDefault { value },
                } = &alter.operations[0]
                {
                    if let Some(seq_ref) = extract_nextval_sequence(value) {
                        set_defaults.push((table_ref, column_name.value.clone(), seq_ref, idx));
                    }
                }
            }
            _ => {}
        }
    }

    let mut idioms = Vec::new();
    for (table_ref, column, seq_ref, set_default_idx) in &set_defaults {
        // Full-signature gate: the CREATE TABLE (with the column), the matching
        // CREATE SEQUENCE, and this SET DEFAULT must all be present and linked.
        // `pick_best_match` prefers an exact-schema candidate over a wildcard
        // one, so an unqualified `CREATE TABLE t` does not steal a SET DEFAULT
        // that names `other.t` when an explicit `CREATE TABLE other.t` exists.
        let Some((tbl_ref_norm, create_table_index, _)) = pick_best_match(
            &tables,
            table_ref,
            |(t, _, _)| t,
            |(_, _, cols)| cols.iter().any(|c| c == column),
        ) else {
            continue;
        };
        let Some((seq_ref_norm, sequence_index)) =
            pick_best_match(&sequences, seq_ref, |(s, _)| s, |_| true)
        else {
            continue;
        };

        idioms.push(SerialIdiom {
            table: tbl_ref_norm.clone(),
            column: column.clone(),
            sequence: seq_ref_norm.clone(),
            create_table_index: *create_table_index,
            redundant_indices: vec![*sequence_index, *set_default_idx],
        });
    }
    idioms
}

/// Re-parse each part into statements, returning the parsed statements alongside
/// a `parsed_to_part` map (parsed-index -> originating-part-index). Parts that
/// fail to parse (e.g. `ALTER SEQUENCE ... OWNED BY`) are simply skipped.
fn parse_parts(parts: &[(usize, String)]) -> (Vec<Statement>, Vec<usize>) {
    let dialect = PostgreSqlDialect {};
    let mut parsed: Vec<Statement> = Vec::new();
    let mut parsed_to_part: Vec<usize> = Vec::new();
    for (part_idx, (_, text)) in parts.iter().enumerate() {
        if let Ok(stmts) = Parser::parse_sql(&dialect, text.trim()) {
            for stmt in stmts {
                parsed.push(stmt);
                parsed_to_part.push(part_idx);
            }
        }
    }
    (parsed, parsed_to_part)
}

/// User-facing message text for the SerialSequenceIdiom diagnostic. Shared
/// between the lint and fix entry points so the wording can't drift.
fn idiom_message(column: &str) -> String {
    format!(
        "Column `{column}` is populated by a sequence via `SET DEFAULT nextval(...)`, \
         which is not supported in DSQL."
    )
}

/// Lint-only pass: surface a `SerialSequenceIdiom` diagnostic for each detected
/// idiom, without touching the input. The per-statement loop in `lint_sql` still
/// runs over the original (unmodified) statements, so users see this high-level
/// finding ALONGSIDE the lower-level rule violations on the constituent
/// statements (the unparseable `ALTER SEQUENCE … OWNED BY` line surfaces as a
/// `ParseError`, the `SET DEFAULT nextval` as `AtUnsupportedAlterColumnSetDefault`).
/// `fix_sql` emits ONLY this finding because `fix_serial_idioms` removes the
/// constituent statements before the per-statement loop runs.
pub(crate) fn check_serial_idioms(parts: &[(usize, String)], diagnostics: &mut Vec<Diagnostic>) {
    let (parsed, parsed_to_part) = parse_parts(parts);

    for idiom in detect_serial_idioms(&parsed) {
        let create_table_part = parsed_to_part[idiom.create_table_index];
        let (line, statement) = (
            parts[create_table_part].0,
            parts[create_table_part].1.clone(),
        );
        diagnostics.push(Diagnostic {
            rule: LintRule::SerialSequenceIdiom,
            line,
            statement,
            message: idiom_message(&idiom.column),
            suggestion: "Replace the CREATE SEQUENCE + SET DEFAULT pair with an inline \
                 `BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)` column on the CREATE TABLE."
                .to_string(),
            fix_result: FixResult::FixedWithWarning(
                "`fix_sql` rewrites the CREATE TABLE column to an inline identity and removes the \
                 sequence wiring; the identity counter is NOT advanced to the max existing id, so \
                 reset it after loading data if the table is pre-populated."
                    .to_string(),
            ),
        });
    }
}

/// Collapse pg_dump's SERIAL idiom into an inline identity column, operating on
/// the split statement-text list that `fix_sql` maintains.
///
/// For each detected idiom this:
/// 1. rewrites the `CREATE TABLE` part so the column becomes
///    `BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)` (reusing the same
///    mutation as the inline-`SERIAL` rule),
/// 2. removes the `CREATE SEQUENCE` and `ALTER COLUMN ... SET DEFAULT nextval`
///    parts (they parse, so they are matched by index), and
/// 3. removes the `ALTER SEQUENCE <seq> OWNED BY ...` part at the TEXT level
///    (it does not parse, so it is matched by its leading tokens + the
///    collapsed sequence name).
///
/// `parts` is `(line_number, statement_text)` as built by `fix_sql`. Each entry
/// is a single statement (already split), so text matching for the unparseable
/// `OWNED BY` line is anchored on a whole statement and cannot trip over a `;`
/// inside a string literal.
pub(crate) fn fix_serial_idioms(
    parts: &mut Vec<(usize, String)>,
    diagnostics: &mut Vec<Diagnostic>,
) {
    let dialect = PostgreSqlDialect {};

    let (parsed, parsed_to_part) = parse_parts(parts);
    let idioms = detect_serial_idioms(&parsed);
    if idioms.is_empty() {
        return;
    }

    let mut parts_to_remove: Vec<usize> = Vec::new();

    for idiom in &idioms {
        let create_table_part = parsed_to_part[idiom.create_table_index];
        // Snapshot the original CREATE TABLE text BEFORE we rewrite it, so the
        // diagnostic's `statement` field reflects what the user wrote (the
        // integer-NOT-NULL column the message describes), not the post-fix
        // identity-column rewrite. The `Diagnostic.statement` contract is
        // "what was found"; the rewrite is implied by `FixResult::FixedWithWarning`.
        let original_statement = parts[create_table_part].1.clone();

        // Re-parse the CREATE TABLE part (rather than mutate the shared `parsed`
        // copy) so we emit exactly that statement's canonical text. Both arms
        // below should be unreachable — `parse_parts` already proved this text
        // parses, and `detect_serial_idioms` proved the column is in the table.
        // If they ever fire, the silent `continue` would mask a real regression
        // (we'd skip the diagnostic AND keep the redundant statements), so guard
        // with `debug_assert!` so test runs catch the drift loudly.
        let Ok(mut stmts) = Parser::parse_sql(&dialect, parts[create_table_part].1.trim()) else {
            debug_assert!(
                false,
                "re-parse of CREATE TABLE for `{}` failed after parse_parts succeeded",
                idiom.column
            );
            continue;
        };
        let mut rewrote = false;
        for stmt in &mut stmts {
            if let Statement::CreateTable(ct) = stmt {
                for col in &mut ct.columns {
                    if col.name.value == idiom.column {
                        make_identity_column(col);
                        rewrote = true;
                    }
                }
            }
        }
        if !rewrote {
            debug_assert!(
                false,
                "column `{}` not found in CREATE TABLE after detect_serial_idioms confirmed it",
                idiom.column
            );
            continue;
        }
        parts[create_table_part].1 = stmts
            .iter()
            .map(|s| format!("{s:#}"))
            .collect::<Vec<_>>()
            .join(";\n");

        // Drop the parseable redundant statements (CREATE SEQUENCE, SET DEFAULT).
        for parsed_idx in &idiom.redundant_indices {
            parts_to_remove.push(parsed_to_part[*parsed_idx]);
        }

        // Drop the unparseable `ALTER SEQUENCE <seq> OWNED BY ...` part, scoped
        // to this idiom's sequence name (multi-table dumps must not bleed over).
        for (part_idx, (_, text)) in parts.iter().enumerate() {
            if is_alter_sequence_owned_by(text, &idiom.sequence) {
                parts_to_remove.push(part_idx);
            }
        }

        let line = parts[create_table_part].0;
        diagnostics.push(Diagnostic {
            rule: LintRule::SerialSequenceIdiom,
            line,
            statement: original_statement,
            message: idiom_message(&idiom.column),
            suggestion: "Collapsed pg_dump's CREATE SEQUENCE + SET DEFAULT into an inline \
                 `BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)` column."
                .to_string(),
            fix_result: FixResult::FixedWithWarning(format!(
                "Replaced the sequence/default wiring on column `{}` with an inline identity \
                 column; the identity counter is NOT advanced to the max existing id, so reset it \
                 after loading data if the table is pre-populated.",
                idiom.column
            )),
        });
    }

    // Remove marked parts in descending order so earlier removals don't shift
    // the indices of later ones. Dedup first (a part is only removed once).
    parts_to_remove.sort_unstable();
    parts_to_remove.dedup();
    for part_idx in parts_to_remove.into_iter().rev() {
        parts.remove(part_idx);
    }
}

/// Mutate a column definition into `BIGINT GENERATED BY DEFAULT AS IDENTITY
/// (CACHE 1)`, preserving options like `NOT NULL` / `PRIMARY KEY` while dropping
/// any pre-existing `DEFAULT` (the sequence default is what we are replacing)
/// or `GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY` (avoids a doubled identity
/// clause when the column already had one and a stray `SET DEFAULT nextval` was
/// also pointing at it). Reuses the shared `identity_by_default_cache_1()`
/// helper in `errors.rs` so the inline-`SERIAL` rule and the SERIAL-idiom
/// collapse always emit the same shape.
fn make_identity_column(col: &mut sqlparser::ast::ColumnDef) {
    col.data_type = DataType::BigInt(None);
    col.options.retain(|opt| {
        !matches!(
            opt.option,
            ColumnOption::Default(_) | ColumnOption::Generated { .. }
        )
    });
    col.options.push(identity_by_default_cache_1());
}

/// Whether a statement's text is `ALTER SEQUENCE <seq> OWNED BY ...` referencing
/// the given (normalized) sequence. Used to drop the unparseable OWNED BY line
/// that belongs to a collapsed idiom. Keywords (`ALTER SEQUENCE [IF EXISTS]`,
/// `OWNED BY`) are matched case-insensitively; the sequence name is parsed by
/// `normalize_dotted_identifier`, which applies PG case-folding (unquoted →
/// lowercase, quoted → preserved) so the comparison mirrors how the matching
/// `CREATE SEQUENCE` produced its `NameRef` from the AST.
fn is_alter_sequence_owned_by(text: &str, sequence: &NameRef) -> bool {
    let trimmed = text.trim().trim_end_matches(';').trim();
    // `to_ascii_lowercase` preserves byte length for ASCII, so byte offsets
    // computed against `lower` are valid indices into `trimmed` too. We use
    // `lower` for keyword matching and slice `trimmed` for the name to keep its
    // original case (quoted identifiers can be case-sensitive).
    let lower = trimmed.to_ascii_lowercase();
    let mut prefix_len = match lower.strip_prefix("alter sequence ") {
        Some(_) => "alter sequence ".len(),
        None => return false,
    };
    if lower[prefix_len..].starts_with("if exists ") {
        prefix_len += "if exists ".len();
    }
    let Some(owned_offset) = lower[prefix_len..].find(" owned by ") else {
        return false;
    };
    let name_ref = normalize_dotted_identifier(trimmed[prefix_len..][..owned_offset].trim());
    refs_match(&name_ref, sequence)
}

/// Normalize a possibly-schema-qualified, possibly-quoted SQL identifier such
/// as `public."My Seq"` or `t_id_seq` into `(Option<schema>, name)`. The split
/// respects `"..."` quoting so a sequence named `"my.seq"` is not chopped
/// inside its quotes; each segment is then PG-folded (unquoted to lowercase,
/// quoted preserved) so the result can be compared byte-equal against an
/// `ObjectName`-derived `NameRef`.
fn normalize_dotted_identifier(s: &str) -> NameRef {
    match rsplit_dot_outside_quotes(s) {
        Some((schema, name)) => (Some(fold_text_ident(schema)), fold_text_ident(name)),
        None => (None, fold_text_ident(s)),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use sqlparser::dialect::PostgreSqlDialect;
    use sqlparser::parser::Parser;

    /// Parse each statement individually and collect the successfully-parsed
    /// ones, mirroring how the caller will skip the unparseable
    /// `ALTER SEQUENCE ... OWNED BY` line.
    fn parse_ok(stmts: &[&str]) -> Vec<Statement> {
        let dialect = PostgreSqlDialect {};
        stmts
            .iter()
            .filter_map(|s| Parser::parse_sql(&dialect, s).ok())
            .flatten()
            .collect()
    }

    #[test]
    fn happy_path_detects_single_idiom() {
        let stmts = parse_ok(&[
            "CREATE TABLE public.t (id integer NOT NULL, x text)",
            "CREATE SEQUENCE public.t_id_seq START WITH 1 INCREMENT BY 1 CACHE 1",
            "ALTER TABLE ONLY public.t ALTER COLUMN id SET DEFAULT nextval('public.t_id_seq'::regclass)",
        ]);
        let idioms = detect_serial_idioms(&stmts);
        assert_eq!(idioms.len(), 1, "expected exactly 1 idiom: {idioms:?}");
        let i = &idioms[0];
        assert_eq!(i.table, (Some("public".to_string()), "t".to_string()));
        assert_eq!(i.column, "id");
        assert_eq!(
            i.sequence,
            (Some("public".to_string()), "t_id_seq".to_string())
        );
        assert_eq!(i.create_table_index, 0);
        // CREATE SEQUENCE at index 1, SET DEFAULT at index 2.
        assert_eq!(i.redundant_indices, vec![1, 2]);
    }

    #[test]
    fn schema_qualified_vs_unqualified_correlates() {
        // CREATE TABLE unqualified, nextval schema-qualified, sequence qualified.
        let stmts = parse_ok(&[
            "CREATE TABLE t (id integer NOT NULL, x text)",
            "CREATE SEQUENCE public.t_id_seq CACHE 1",
            "ALTER TABLE ONLY public.t ALTER COLUMN id SET DEFAULT nextval('public.t_id_seq'::regclass)",
        ]);
        let idioms = detect_serial_idioms(&stmts);
        assert_eq!(idioms.len(), 1, "expected exactly 1 idiom: {idioms:?}");
        assert_eq!(idioms[0].column, "id");
        assert_eq!(idioms[0].create_table_index, 0);
        assert_eq!(idioms[0].redundant_indices, vec![1, 2]);
    }

    #[test]
    fn free_standing_sequence_no_idiom() {
        // CREATE SEQUENCE with no matching SET DEFAULT -> nothing to collapse.
        let stmts = parse_ok(&[
            "CREATE TABLE public.t (id integer NOT NULL, x text)",
            "CREATE SEQUENCE public.t_id_seq CACHE 1",
        ]);
        let idioms = detect_serial_idioms(&stmts);
        assert_eq!(idioms.len(), 0, "expected 0 idioms: {idioms:?}");
    }

    #[test]
    fn set_default_referencing_absent_sequence_no_idiom() {
        // SET DEFAULT nextval('other_seq') but no CREATE SEQUENCE other_seq.
        let stmts = parse_ok(&[
            "CREATE TABLE public.t (id integer NOT NULL, x text)",
            "ALTER TABLE ONLY public.t ALTER COLUMN id SET DEFAULT nextval('public.other_seq'::regclass)",
        ]);
        let idioms = detect_serial_idioms(&stmts);
        assert_eq!(idioms.len(), 0, "expected 0 idioms: {idioms:?}");
    }

    #[test]
    fn set_default_not_nextval_no_idiom() {
        // SET DEFAULT 0 is not a nextval idiom, even with a sequence present.
        let stmts = parse_ok(&[
            "CREATE TABLE public.t (id integer NOT NULL, x text)",
            "CREATE SEQUENCE public.t_id_seq CACHE 1",
            "ALTER TABLE ONLY public.t ALTER COLUMN id SET DEFAULT 0",
        ]);
        let idioms = detect_serial_idioms(&stmts);
        assert_eq!(idioms.len(), 0, "expected 0 idioms: {idioms:?}");
    }

    #[test]
    fn two_tables_each_serial_detects_two() {
        let stmts = parse_ok(&[
            "CREATE TABLE public.a (id integer NOT NULL)",
            "CREATE SEQUENCE public.a_id_seq CACHE 1",
            "ALTER TABLE ONLY public.a ALTER COLUMN id SET DEFAULT nextval('public.a_id_seq'::regclass)",
            "CREATE TABLE public.b (id integer NOT NULL)",
            "CREATE SEQUENCE public.b_id_seq CACHE 1",
            "ALTER TABLE ONLY public.b ALTER COLUMN id SET DEFAULT nextval('public.b_id_seq'::regclass)",
        ]);
        let mut idioms = detect_serial_idioms(&stmts);
        assert_eq!(idioms.len(), 2, "expected 2 idioms: {idioms:?}");
        // Order by create_table_index for stable assertions.
        idioms.sort_by_key(|i| i.create_table_index);

        assert_eq!(idioms[0].table.1, "a");
        assert_eq!(idioms[0].create_table_index, 0);
        assert_eq!(idioms[0].redundant_indices, vec![1, 2]);

        assert_eq!(idioms[1].table.1, "b");
        assert_eq!(idioms[1].create_table_index, 3);
        assert_eq!(idioms[1].redundant_indices, vec![4, 5]);
    }

    /// `is_alter_sequence_owned_by` must match the OWNED BY line for the right
    /// sequence regardless of keyword case, optional `IF EXISTS`, and trailing
    /// whitespace, while ignoring lines belonging to a different sequence.
    #[test]
    fn alter_sequence_owned_by_matching() {
        let seq = (Some("public".to_string()), "t_id_seq".to_string());
        let other = (Some("public".to_string()), "u_id_seq".to_string());

        // Plain match.
        assert!(is_alter_sequence_owned_by(
            "ALTER SEQUENCE public.t_id_seq OWNED BY public.t.id;",
            &seq
        ));
        // Case-insensitive on keywords.
        assert!(is_alter_sequence_owned_by(
            "alter sequence public.t_id_seq owned by public.t.id",
            &seq
        ));
        // Mixed case + IF EXISTS variant.
        assert!(is_alter_sequence_owned_by(
            "ALTER SEQUENCE IF EXISTS public.t_id_seq OWNED BY public.t.id;",
            &seq
        ));
        assert!(is_alter_sequence_owned_by(
            "alter sequence if exists public.t_id_seq owned by public.t.id",
            &seq
        ));
        // Different sequence -> no match (don't drop unrelated lines).
        assert!(!is_alter_sequence_owned_by(
            "ALTER SEQUENCE public.u_id_seq OWNED BY public.u.id;",
            &seq
        ));
        assert!(is_alter_sequence_owned_by(
            "ALTER SEQUENCE public.u_id_seq OWNED BY public.u.id;",
            &other
        ));
        // Not an OWNED BY statement at all.
        assert!(!is_alter_sequence_owned_by(
            "ALTER SEQUENCE public.t_id_seq RESTART WITH 100;",
            &seq
        ));
        // Not an ALTER SEQUENCE.
        assert!(!is_alter_sequence_owned_by(
            "CREATE SEQUENCE public.t_id_seq",
            &seq
        ));
    }

    /// `pg_dump` (rarely) and hand-edited dumps can use the schema-qualified
    /// `pg_catalog.nextval(...)` instead of the bare `nextval(...)`. The detector
    /// should still recognize these as the SERIAL idiom.
    #[test]
    fn extract_nextval_accepts_pg_catalog_qualified_name() {
        let stmts = parse_ok(&[
            "CREATE TABLE public.t (id integer NOT NULL)",
            "CREATE SEQUENCE public.t_id_seq CACHE 1",
            "ALTER TABLE ONLY public.t ALTER COLUMN id \
             SET DEFAULT pg_catalog.nextval('public.t_id_seq'::regclass)",
        ]);
        let idioms = detect_serial_idioms(&stmts);
        assert_eq!(idioms.len(), 1, "expected exactly 1 idiom: {idioms:?}");
        assert_eq!(idioms[0].column, "id");
    }

    /// Multi-op ALTER TABLE: detector must NOT mark this idiom as collapsible —
    /// removing the whole statement would silently drop the unrelated `ADD
    /// CONSTRAINT`. The user gets the per-statement
    /// `AtUnsupportedAlterColumnSetDefault` Unfixable instead.
    #[test]
    fn multi_op_alter_table_skipped() {
        let stmts = parse_ok(&[
            "CREATE TABLE public.t (id integer NOT NULL)",
            "CREATE SEQUENCE public.t_id_seq CACHE 1",
            "ALTER TABLE ONLY public.t \
             ALTER COLUMN id SET DEFAULT nextval('public.t_id_seq'::regclass), \
             ADD CONSTRAINT t_pkey PRIMARY KEY (id)",
        ]);
        assert_eq!(detect_serial_idioms(&stmts).len(), 0);
    }

    /// Quoted mixed-case sequence inside `nextval('public."T_Id_seq"'::regclass)`
    /// must correlate with `CREATE SEQUENCE public."T_Id_seq"` (whose AST
    /// identifier value is the unquoted `T_Id_seq`).
    #[test]
    fn quoted_mixed_case_sequence_correlates() {
        let stmts = parse_ok(&[
            "CREATE TABLE public.\"T\" (\"Id\" integer NOT NULL)",
            "CREATE SEQUENCE public.\"T_Id_seq\" CACHE 1",
            "ALTER TABLE ONLY public.\"T\" ALTER COLUMN \"Id\" \
             SET DEFAULT nextval('public.\"T_Id_seq\"'::regclass)",
        ]);
        let idioms = detect_serial_idioms(&stmts);
        assert_eq!(idioms.len(), 1, "expected 1 idiom: {idioms:?}");
        assert_eq!(idioms[0].column, "Id");
        assert_eq!(idioms[0].sequence.1, "T_Id_seq");
    }

    /// PG case-folding: a `CREATE SEQUENCE My_Seq` (unquoted, mixed-case in the
    /// source but folded to `my_seq` by Postgres at parse time) must correlate
    /// with `nextval('my_seq')`. Pre-fix this failed because the comparison was
    /// byte-equal on the raw `Ident.value` string.
    #[test]
    fn unquoted_mixed_case_correlates_after_folding() {
        let stmts = parse_ok(&[
            "CREATE TABLE public.T (id integer NOT NULL)",
            "CREATE SEQUENCE public.T_Id_Seq CACHE 1",
            "ALTER TABLE ONLY public.T ALTER COLUMN id \
             SET DEFAULT nextval('public.t_id_seq'::regclass)",
        ]);
        let idioms = detect_serial_idioms(&stmts);
        assert_eq!(idioms.len(), 1, "expected 1 idiom: {idioms:?}");
        assert_eq!(
            idioms[0].sequence,
            (Some("public".into()), "t_id_seq".into())
        );
    }

    /// A QUOTED mixed-case sequence is case-sensitive in PG. `"My_Seq"` and
    /// `nextval('my_seq')` (unquoted, folds to `my_seq`) must NOT correlate.
    #[test]
    fn quoted_vs_unquoted_case_does_not_correlate() {
        let stmts = parse_ok(&[
            "CREATE TABLE public.t (id integer NOT NULL)",
            "CREATE SEQUENCE public.\"My_Seq\" CACHE 1",
            "ALTER TABLE ONLY public.t ALTER COLUMN id \
             SET DEFAULT nextval('public.my_seq'::regclass)",
        ]);
        // No matching CREATE SEQUENCE for the unquoted lowercase reference, so
        // the idiom should NOT be detected (the per-statement rules still flag
        // the SET DEFAULT separately as Unfixable).
        assert_eq!(detect_serial_idioms(&stmts).len(), 0);
    }

    /// Finding #2: when both an unqualified and a schema-qualified table with
    /// the same name exist, a SET DEFAULT naming the qualified one must
    /// correlate with the qualified table — not the unqualified wildcard match
    /// that happens to appear earlier in the statement list.
    #[test]
    fn exact_schema_match_preferred_over_wildcard() {
        let stmts = parse_ok(&[
            "CREATE TABLE t (id integer NOT NULL)",
            "CREATE TABLE other.t (id integer NOT NULL)",
            "CREATE SEQUENCE other.t_id_seq CACHE 1",
            "ALTER TABLE ONLY other.t ALTER COLUMN id \
             SET DEFAULT nextval('other.t_id_seq'::regclass)",
        ]);
        let idioms = detect_serial_idioms(&stmts);
        assert_eq!(idioms.len(), 1, "expected 1 idiom: {idioms:?}");
        // create_table_index 1 is `other.t`, NOT 0 (the unqualified `t`).
        assert_eq!(idioms[0].create_table_index, 1);
        assert_eq!(idioms[0].table, (Some("other".into()), "t".into()));
    }

    /// Finding #3: a sequence named `"my.seq"` (literal dot inside quotes)
    /// must not be mis-split by `normalize_dotted_identifier`. The whole
    /// quoted string is the name; there is no schema.
    #[test]
    fn dotted_quoted_identifier_not_mis_split() {
        let n = normalize_dotted_identifier("\"my.seq\"");
        assert_eq!(n, (None, "my.seq".to_string()));

        let n = normalize_dotted_identifier("public.\"my.seq\"");
        assert_eq!(n, (Some("public".into()), "my.seq".into()));
    }

    /// Finding #4: in fix mode the diagnostic's `statement` field must
    /// reflect the ORIGINAL CREATE TABLE text (the integer-NOT-NULL column),
    /// not the post-rewrite identity-column form. The rewrite is implied by
    /// `FixResult::FixedWithWarning`.
    #[test]
    fn fix_diagnostic_statement_is_original_text() {
        let mut parts = vec![
            (
                1,
                "CREATE TABLE public.t (id integer NOT NULL, x text)".into(),
            ),
            (2, "CREATE SEQUENCE public.t_id_seq CACHE 1".into()),
            (
                3,
                "ALTER TABLE ONLY public.t ALTER COLUMN id \
                 SET DEFAULT nextval('public.t_id_seq'::regclass)"
                    .into(),
            ),
        ];
        let mut diags = Vec::new();
        fix_serial_idioms(&mut parts, &mut diags);
        assert_eq!(diags.len(), 1, "expected one diagnostic: {diags:?}");
        // Original text mentions the INTEGER column the message describes.
        assert!(
            diags[0].statement.contains("integer NOT NULL"),
            "expected original CREATE TABLE text in diagnostic.statement, got: {}",
            diags[0].statement
        );
        // And does NOT pre-leak the rewritten identity form.
        assert!(
            !diags[0].statement.contains("IDENTITY"),
            "diagnostic.statement should not contain the rewritten IDENTITY clause: {}",
            diags[0].statement
        );
        // The rewrite still happened — parts[0] now carries the identity column.
        assert!(parts[0].1.contains("IDENTITY"));
    }
}
