-- AUTOGENERATED by tests/grammar_corpus_mirror_test.rs.
-- Mirrors a curated array in dsql-lint's integration tests. Do not edit by hand.
-- Source: tests/common/mod.rs::CLEAN_STATEMENTS

-- label: create-view
CREATE VIEW _clean_view AS SELECT 1;

-- label: alter-add-col
ALTER TABLE _clean_base ADD COLUMN description TEXT;

-- label: insert
INSERT INTO _clean_base (id, name) VALUES (1, 'test');

-- label: select
SELECT * FROM _clean_base WHERE id = 1;

-- label: update
UPDATE _clean_base SET name = 'updated' WHERE id = 1;

-- label: delete
DELETE FROM _clean_base WHERE id = 1;

-- label: begin-repeatable-read
BEGIN ISOLATION LEVEL REPEATABLE READ;

-- label: begin-plain
BEGIN;

-- label: create-view-v2
CREATE VIEW _clean_view2 AS SELECT 1;

-- label: insert-string-with-sql-keywords
INSERT INTO _clean_base (id, name) VALUES (2, 'TRUNCATE TABLE foo; CREATE TRIGGER bar');

