-- AUTOGENERATED by tests/grammar_corpus_mirror_test.rs.
-- Mirrors a curated array in dsql-lint's integration tests. Do not edit by hand.
-- Source: tests/common/mod.rs::SUPPORTED_TYPES

-- label: smallint
CREATE TABLE _t (col SMALLINT);

-- label: int2
CREATE TABLE _t (col INT2);

-- label: integer
CREATE TABLE _t (col INTEGER);

-- label: int
CREATE TABLE _t (col INT);

-- label: int4
CREATE TABLE _t (col INT4);

-- label: bigint
CREATE TABLE _t (col BIGINT);

-- label: int8
CREATE TABLE _t (col INT8);

-- label: real
CREATE TABLE _t (col REAL);

-- label: float4
CREATE TABLE _t (col FLOAT4);

-- label: double-precision
CREATE TABLE _t (col DOUBLE PRECISION);

-- label: float8
CREATE TABLE _t (col FLOAT8);

-- label: numeric
CREATE TABLE _t (col NUMERIC(10,2));

-- label: decimal
CREATE TABLE _t (col DECIMAL(18,6));

-- label: dec
CREATE TABLE _t (col DEC(5,2));

-- label: char
CREATE TABLE _t (col CHAR(10));

-- label: character
CREATE TABLE _t (col CHARACTER(20));

-- label: varchar
CREATE TABLE _t (col VARCHAR(255));

-- label: character-varying
CREATE TABLE _t (col CHARACTER VARYING(100));

-- label: text
CREATE TABLE _t (col TEXT);

-- label: bpchar
CREATE TABLE _t (col BPCHAR(50));

-- label: date
CREATE TABLE _t (col DATE);

-- label: time
CREATE TABLE _t (col TIME);

-- label: time-tz
CREATE TABLE _t (col TIME WITH TIME ZONE);

-- label: timestamp
CREATE TABLE _t (col TIMESTAMP);

-- label: timestamp-tz
CREATE TABLE _t (col TIMESTAMP WITH TIME ZONE);

-- label: interval
CREATE TABLE _t (col INTERVAL);

-- label: boolean
CREATE TABLE _t (col BOOLEAN);

-- label: bool
CREATE TABLE _t (col BOOL);

-- label: bytea
CREATE TABLE _t (col BYTEA);

-- label: uuid
CREATE TABLE _t (col UUID);

-- label: json
CREATE TABLE _t (col JSON);

-- label: jsonb
CREATE TABLE _t (col JSONB);

-- label: identity-always
CREATE TABLE _t (col BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 1));

-- label: identity-by-default
CREATE TABLE _t (col BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1));

-- label: identity-cache-65536
CREATE TABLE _t (col BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 65536));

-- label: identity-by-default-cache-65536
CREATE TABLE _t (col BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 65536));

