/// Column types that DSQL supports. Shared between unit and cluster tests
/// to keep the two lists from drifting.
///
/// Source: https://docs.aws.amazon.com/aurora-dsql/latest/userguide/
///         working-with-postgresql-compatibility-supported-data-types.html
pub const SUPPORTED_TYPES: &[(&str, &str)] = &[
    // Numeric
    ("smallint", "SMALLINT"),
    ("int2", "INT2"),
    ("integer", "INTEGER"),
    ("int", "INT"),
    ("int4", "INT4"),
    ("bigint", "BIGINT"),
    ("int8", "INT8"),
    ("real", "REAL"),
    ("float4", "FLOAT4"),
    ("double-precision", "DOUBLE PRECISION"),
    ("float8", "FLOAT8"),
    ("numeric", "NUMERIC(10,2)"),
    ("decimal", "DECIMAL(18,6)"),
    ("dec", "DEC(5,2)"),
    // Character
    ("char", "CHAR(10)"),
    ("character", "CHARACTER(20)"),
    ("varchar", "VARCHAR(255)"),
    ("character-varying", "CHARACTER VARYING(100)"),
    ("text", "TEXT"),
    ("bpchar", "BPCHAR(50)"),
    // Date/time
    ("date", "DATE"),
    ("time", "TIME"),
    ("time-tz", "TIME WITH TIME ZONE"),
    ("timestamp", "TIMESTAMP"),
    ("timestamp-tz", "TIMESTAMP WITH TIME ZONE"),
    ("interval", "INTERVAL"),
    // Miscellaneous
    ("boolean", "BOOLEAN"),
    ("bool", "BOOL"),
    ("bytea", "BYTEA"),
    ("uuid", "UUID"),
    ("json", "JSON"),
    ("jsonb", "JSONB"),
    // Identity columns
    (
        "identity-always",
        "BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 1)",
    ),
    (
        "identity-by-default",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
    ),
    (
        "identity-cache-65536",
        "BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 65536)",
    ),
    (
        "identity-by-default-cache-65536",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 65536)",
    ),
];

/// Single statements that must lint clean AND execute on a real DSQL cluster.
/// Shared between unit and cluster tests so the two lists can't drift.
///
/// Each entry: (label, sql, setup_sql, cleanup_sql).
/// - `setup_sql` / `cleanup_sql` are run before/after in cluster tests.
/// - Entries are executed sequentially, so order matters for cluster tests
///   (e.g. create a table before inserting into it).
pub const CLEAN_STATEMENTS: &[(&str, &str, &str, &str)] = &[
    (
        "create-view",
        "CREATE VIEW _clean_view AS SELECT 1;",
        "",
        "DROP VIEW IF EXISTS _clean_view;",
    ),
    (
        "alter-add-col",
        "ALTER TABLE _clean_base ADD COLUMN description TEXT;",
        "",
        "ALTER TABLE _clean_base DROP COLUMN IF EXISTS description;",
    ),
    (
        "insert",
        "INSERT INTO _clean_base (id, name) VALUES (1, 'test');",
        "",
        "",
    ),
    ("select", "SELECT * FROM _clean_base WHERE id = 1;", "", ""),
    (
        "update",
        "UPDATE _clean_base SET name = 'updated' WHERE id = 1;",
        "",
        "",
    ),
    ("delete", "DELETE FROM _clean_base WHERE id = 1;", "", ""),
    (
        "begin-repeatable-read",
        "BEGIN ISOLATION LEVEL REPEATABLE READ;",
        "",
        "ROLLBACK;",
    ),
    ("begin-plain", "BEGIN;", "", "ROLLBACK;"),
    (
        "create-view-v2",
        "CREATE VIEW _clean_view2 AS SELECT 1;",
        "",
        "DROP VIEW IF EXISTS _clean_view2;",
    ),
    (
        "insert-string-with-sql-keywords",
        "INSERT INTO _clean_base (id, name) VALUES (2, 'TRUNCATE TABLE foo; CREATE TRIGGER bar');",
        "",
        "",
    ),
];

/// Valid SQL that must NOT trigger specific rule diagnostics. Each row is
/// `(sql, unexpected_error_substring)` — the lint must not produce a
/// diagnostic whose `message` contains the substring.
///
/// Mirrored into `tests/grammar_corpus/in_tree/false_positive_cases.sql` for
/// the grammar-diff tool. The mirror is kept in sync by
/// `tests/grammar_corpus_mirror_test.rs`.
#[allow(dead_code)]
pub const FALSE_POSITIVE_CASES: &[(&str, &str)] = &[
    // Column named 'serial_number' should not trigger SERIAL rule
    (
        "CREATE TABLE t (id UUID PRIMARY KEY, serial_number VARCHAR(100));",
        "SERIAL",
    ),
    // TEXT column named 'json_data' should not trigger JSON rule
    (
        "CREATE TABLE t (id UUID PRIMARY KEY, json_data TEXT);",
        "JSON",
    ),
    // JSON column should not trigger
    ("CREATE TABLE t (id UUID PRIMARY KEY, data JSON);", "JSON"),
    // Table named 'temporary_cache' should not trigger TEMP rule
    (
        "CREATE TABLE temporary_cache (id UUID PRIMARY KEY);",
        "TEMPORARY",
    ),
    // TEXT column named 'tags' should not trigger array rule
    ("CREATE TABLE t (id UUID PRIMARY KEY, tags TEXT);", "array"),
    // Column named 'partition_key' should not trigger PARTITION rule
    (
        "CREATE TABLE t (id UUID PRIMARY KEY, partition_key VARCHAR(50));",
        "PARTITION",
    ),
    // DELETE FROM should not trigger TRUNCATE rule
    ("DELETE FROM events WHERE id = 1;", "TRUNCATE"),
    // GENERATED ALWAYS AS IDENTITY should not trigger SERIAL
    (
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY);",
        "SERIAL",
    ),
    // GENERATED BY DEFAULT AS IDENTITY should not trigger SERIAL
    (
        "CREATE TABLE t (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);",
        "SERIAL",
    ),
    // Column named 'inherits_from' should not trigger INHERITS rule
    (
        "CREATE TABLE t (id UUID PRIMARY KEY, inherits_from TEXT);",
        "INHERITS",
    ),
    // Valid index should not trigger USING, Expression, or Partial rules
    ("CREATE INDEX ASYNC idx ON t(col);", "USING"),
    ("CREATE INDEX ASYNC idx ON t(col);", "Expression"),
    ("CREATE INDEX ASYNC idx ON t(col);", "Partial"),
    // Regular CREATE VIEW should not trigger temporary or materialized view rules
    ("CREATE VIEW v AS SELECT 1;", "TEMPORARY VIEW"),
    ("CREATE VIEW v AS SELECT 1;", "MATERIALIZED VIEW"),
    // BIGINT identity columns should not trigger identity error
    (
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 1));",
        "Identity column",
    ),
    (
        "CREATE TABLE t (id BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1));",
        "Identity column",
    ),
    // Valid CREATE SEQUENCE should not trigger errors
    ("CREATE SEQUENCE s AS BIGINT CACHE 65536;", "not supported"),
    ("CREATE SEQUENCE s CACHE 1;", "invalid"),
    ("CREATE SEQUENCE s CACHE 65536;", "invalid"),
    // Schema-qualified column in index is not an expression index
    ("CREATE INDEX ASYNC idx ON t(col);", "Expression"),
    // CONCURRENTLY should only produce one error, not also an ASYNC error
    ("CREATE INDEX CONCURRENTLY idx ON t(col);", "without ASYNC"),
    // Identity column with valid CACHE should not trigger CACHE error
    (
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 65536));",
        "CACHE value",
    ),
    // CACHE 65537 is also valid
    ("CREATE SEQUENCE s CACHE 65537;", "CACHE value"),
    // Plain ROLLBACK should not trigger ROLLBACK TO SAVEPOINT rule
    ("ROLLBACK;", "SAVEPOINT"),
    // Plain ALTER TABLE ADD COLUMN should not trigger RLS or REPLICA IDENTITY rules
    ("ALTER TABLE t ADD COLUMN x TEXT;", "ROW LEVEL SECURITY"),
    ("ALTER TABLE t ADD COLUMN x TEXT;", "REPLICA IDENTITY"),
    // RENAME/OWNER should not trigger VALIDATE CONSTRAINT
    ("ALTER TABLE t OWNER TO new_owner;", "VALIDATE CONSTRAINT"),
    // Plain ALTER TABLE ADD COLUMN should not trigger RULE diagnostics
    ("ALTER TABLE t ADD COLUMN x TEXT;", "RULE"),
    // COPY FROM STDIN / COPY TO STDOUT are valid in DSQL
    ("COPY t FROM STDIN;", "COPY"),
    ("COPY t TO STDOUT;", "COPY"),
    // ALTER TABLE ADD CHECK (not USING INDEX) should not trigger USING INDEX
    (
        "ALTER TABLE t ADD CONSTRAINT c CHECK (id > 0);",
        "USING INDEX",
    ),
    // ALTER FUNCTION OWNER TO / RENAME TO / SET SCHEMA / DEPENDS ON EXTENSION are supported on DSQL
    ("ALTER FUNCTION fn() OWNER TO admin;", "ALTER FUNCTION"),
    ("ALTER FUNCTION fn() RENAME TO fn2;", "ALTER FUNCTION"),
    ("ALTER FUNCTION fn() SET SCHEMA s;", "ALTER FUNCTION"),
    (
        "ALTER FUNCTION fn() DEPENDS ON EXTENSION ext;",
        "ALTER FUNCTION",
    ),
    // ALTER ROLE RENAME TO / RESET are supported on DSQL.
    // RESET ALL and RESET <param> are distinct sqlparser AST variants
    // (ResetConfig::ALL vs ResetConfig::ConfigName); both must be pinned.
    ("ALTER ROLE r RENAME TO r2;", "ALTER ROLE"),
    ("ALTER ROLE r RESET ALL;", "ALTER ROLE"),
    ("ALTER ROLE r RESET work_mem;", "ALTER ROLE"),
    // ALTER TABLE ENABLE/DISABLE TRIGGER is supported in DSQL
    ("ALTER TABLE t ENABLE TRIGGER ALL;", "TRIGGER"),
    ("ALTER TABLE t DISABLE TRIGGER ALL;", "TRIGGER"),
    ("ALTER TABLE t ENABLE ALWAYS TRIGGER trg1;", "TRIGGER"),
    ("ALTER TABLE t ENABLE REPLICA TRIGGER trg1;", "TRIGGER"),
    // DROP VIEW (non-materialized) is supported on DSQL
    ("DROP VIEW v;", "MATERIALIZED VIEW"),
];

/// SQL that must trigger a diagnostic whose `message` contains the second
/// element. Mirror in `in_tree/error_cases.sql`; mirror guard in
/// `grammar_corpus_mirror_test.rs`.
#[allow(dead_code)]
pub const ADDITIONAL_ERROR_CASES: &[(&str, &str)] = &[
    (
        "ALTER TABLE t ADD COLUMN status VARCHAR(50) DEFAULT 'pending';",
        "ADD COLUMN",
    ),
    (
        "ALTER TABLE t ADD COLUMN status VARCHAR(50) NOT NULL;",
        "ADD COLUMN",
    ),
    // Transaction isolation level
    ("BEGIN ISOLATION LEVEL SERIALIZABLE;", "isolation level"),
    ("BEGIN ISOLATION LEVEL READ COMMITTED;", "isolation level"),
    (
        "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;",
        "SET TRANSACTION",
    ),
    // CREATE SEQUENCE without CACHE
    ("CREATE SEQUENCE s;", "CACHE"),
    ("CREATE SEQUENCE s INCREMENT 1;", "CACHE"),
    // ALTER TABLE operations
    ("ALTER TABLE t DROP COLUMN name;", "DROP COLUMN"),
    ("ALTER TABLE t ALTER COLUMN name TYPE TEXT;", "ALTER COLUMN"),
    (
        "ALTER TABLE t ALTER COLUMN name SET NOT NULL;",
        "SET NOT NULL",
    ),
    // DROP NOT NULL / SET DEFAULT / DROP DEFAULT are supported by DSQL and
    // belong in ADDITIONAL_FALSE_POSITIVES, not here.
    ("ALTER TABLE t ADD CONSTRAINT c CHECK (id > 0);", "CHECK"),
    ("ALTER TABLE t ADD CONSTRAINT c UNIQUE (name);", "UNIQUE"),
    ("ALTER TABLE t DROP CONSTRAINT c;", "DROP CONSTRAINT"),
    // Identity column without CACHE — CREATE TABLE
    (
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY);",
        "CACHE",
    ),
    (
        "CREATE TABLE t (id BIGINT GENERATED BY DEFAULT AS IDENTITY);",
        "CACHE",
    ),
    // Identity column in ALTER TABLE ADD COLUMN — not supported in DSQL
    (
        "ALTER TABLE t ADD COLUMN id BIGINT GENERATED ALWAYS AS IDENTITY;",
        "not supported in ALTER TABLE ADD COLUMN",
    ),
    (
        "ALTER TABLE t ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;",
        "not supported in ALTER TABLE ADD COLUMN",
    ),
    // ALTER COLUMN ADD GENERATED AS IDENTITY
    (
        "ALTER TABLE t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY;",
        "ADD GENERATED AS IDENTITY",
    ),
    (
        "ALTER TABLE t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;",
        "ADD GENERATED AS IDENTITY",
    ),
    (
        "ALTER TABLE t ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (CACHE 1);",
        "ADD GENERATED AS IDENTITY",
    ),
    // Pin the named-PREPARE form so a future sqlparser-dsql parse-shape change
    // (e.g. stashing the name elsewhere when `prepare: true`) doesn't silently
    // drop coverage. The no-PREPARE form is exercised by the rule fixture.
    ("DEALLOCATE PREPARE _foo;", "DEALLOCATE"),
];

/// Additional false-positive guards. Mirror in
/// `in_tree/false_positive_cases.sql` (concatenated with `FALSE_POSITIVE_CASES`).
#[allow(dead_code)]
pub const ADDITIONAL_FALSE_POSITIVES: &[(&str, &str)] = &[
    ("ALTER TABLE t ADD COLUMN status VARCHAR(50);", "ADD COLUMN"),
    // REPEATABLE READ should not error
    ("BEGIN ISOLATION LEVEL REPEATABLE READ;", "isolation"),
    // Plain BEGIN should not error about isolation
    ("BEGIN;", "isolation"),
    // SEQUENCE with CACHE should not error
    ("CREATE SEQUENCE s CACHE 1;", "CACHE clause"),
    ("CREATE SEQUENCE s CACHE 65536;", "CACHE clause"),
    // Supported ALTER TABLE operations should not error
    ("ALTER TABLE t ADD COLUMN name TEXT;", "DROP COLUMN"),
    ("ALTER TABLE t OWNER TO new_owner;", "DROP"),
    ("ALTER TABLE t RENAME COLUMN a TO b;", "ALTER COLUMN"),
    // ALTER COLUMN DROP NOT NULL / SET DEFAULT / DROP DEFAULT are now
    // supported by DSQL (verified on a live cluster) and must not be flagged.
    (
        "ALTER TABLE t ALTER COLUMN name DROP NOT NULL;",
        "DROP NOT NULL",
    ),
    (
        "ALTER TABLE t ALTER COLUMN name SET DEFAULT 'foo';",
        "SET DEFAULT",
    ),
    (
        "ALTER TABLE t ALTER COLUMN name DROP DEFAULT;",
        "DROP DEFAULT",
    ),
    // Identity column WITH CACHE should not error about missing CACHE
    (
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 1));",
        "CACHE clause",
    ),
    (
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 65536));",
        "CACHE clause",
    ),
    // ALTER TABLE ADD COLUMN identity errors about identity, not CACHE
    (
        "ALTER TABLE t ADD COLUMN id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 1);",
        "CACHE clause",
    ),
    // DEALLOCATE ALL is the one form DSQL accepts. The PREPARE-keyword variant
    // parses as `Deallocate { name: "ALL", prepare: true }`; the rule guard
    // checks only the name, so it must also pass.
    ("DEALLOCATE ALL;", "DEALLOCATE"),
    ("deallocate all;", "DEALLOCATE"),
    ("DEALLOCATE PREPARE ALL;", "DEALLOCATE"),
    // TABLESPACE-only CREATE TABLE must not double-fire as a storage-parameter
    // diagnostic — the CREATE TABLE rule in `rules/errors.rs` strips the
    // TABLESPACE option before the storage-parameter check, leaving an empty
    // opts list.
    (
        "CREATE TABLE t (id INT) TABLESPACE my_space;",
        "storage parameters",
    ),
];

use dsql_lint::LintRule;

/// One example per `LintRule` variant: SQL that triggers the rule, the
/// expected error substring, and optional setup/cleanup SQL for cluster
/// runs. Adding a new `LintRule` variant without a match arm is a compile
/// error — that's the whole guarantee. Returning `None` skips the rule
/// from BOTH unit (integration_test.rs) and cluster validation
/// (dsql_cluster_test.rs); reserve `None` for rules that can't be
/// expressed as a single statement (e.g. `ParseError`).
///
/// Cluster tests assume `_clust_base (id INT, col INT)` exists; the
/// per-rule cluster runner creates it before iteration. Setup/cleanup
/// fields are for objects beyond `_clust_base` (sequences, indexes,
/// dropped objects that need pre-existing).
#[allow(dead_code)]
#[derive(Debug, Clone, Copy)]
pub struct RuleFixture {
    pub sql: &'static str,
    pub expected_msg_substr: &'static str,
    pub setup_sql: &'static str,
    pub cleanup_sql: &'static str,
}

#[allow(dead_code)]
const fn fix(sql: &'static str, msg: &'static str) -> Option<RuleFixture> {
    Some(RuleFixture {
        sql,
        expected_msg_substr: msg,
        setup_sql: "",
        cleanup_sql: "",
    })
}

#[allow(dead_code)]
const fn fix_with(
    sql: &'static str,
    msg: &'static str,
    setup: &'static str,
    cleanup: &'static str,
) -> Option<RuleFixture> {
    Some(RuleFixture {
        sql,
        expected_msg_substr: msg,
        setup_sql: setup,
        cleanup_sql: cleanup,
    })
}

#[allow(dead_code)]
pub fn fixture_for_rule(rule: LintRule) -> Option<RuleFixture> {
    match rule {
        // ─── Single-purpose rules ─────────────────────────────────────────
        LintRule::SerialType => fix("CREATE TABLE _r (id SERIAL PRIMARY KEY);", "SERIAL"),
        LintRule::ArrayType => fix("CREATE TABLE _r (id INT, tags TEXT[]);", "array"),
        LintRule::ForeignKey => fix(
            "CREATE TABLE _r (id INT, cid INT REFERENCES _clust_base(id));",
            "FOREIGN KEY",
        ),
        LintRule::TempTable => fix("CREATE TEMP TABLE _r (id INT);", "TEMPORARY"),
        LintRule::PartitionBy => fix(
            "CREATE TABLE _r (id INT, d DATE) PARTITION BY RANGE (d);",
            "PARTITION",
        ),
        LintRule::Inherits => fix(
            "CREATE TABLE _r (extra INT) INHERITS (_clust_base);",
            "INHERITS",
        ),
        LintRule::CreateTableAs => fix("CREATE TABLE _r AS SELECT 1 AS id;", "CREATE TABLE AS"),
        LintRule::Tablespace => fix(
            "CREATE TABLE _r (id INT) TABLESPACE my_space;",
            "TABLESPACE",
        ),
        LintRule::IdentityType => fix(
            "CREATE TABLE _r (id INTEGER GENERATED ALWAYS AS IDENTITY);",
            "Identity column",
        ),
        LintRule::IdentityCache => fix(
            "CREATE TABLE _r (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 100));",
            "CACHE value",
        ),
        LintRule::IdentityCacheMissing => fix(
            "CREATE TABLE _r (id BIGINT GENERATED ALWAYS AS IDENTITY);",
            "CACHE",
        ),
        LintRule::IndexAsync => fix("CREATE INDEX _r_idx ON _clust_base(col);", "ASYNC"),
        LintRule::IndexConcurrently => fix(
            "CREATE INDEX CONCURRENTLY _r_idx ON _clust_base(col);",
            "CONCURRENTLY",
        ),
        LintRule::IndexUsing => fix(
            "CREATE INDEX ASYNC _r_idx ON _clust_base USING btree(col);",
            "USING",
        ),
        LintRule::IndexExpression => fix(
            "CREATE INDEX ASYNC _r_idx ON _clust_base(lower(col));",
            "Expression",
        ),
        LintRule::IndexPartial => fix(
            "CREATE INDEX ASYNC _r_idx ON _clust_base(col) WHERE col > 0;",
            "Partial",
        ),
        LintRule::Truncate => fix("TRUNCATE TABLE _clust_base;", "TRUNCATE"),
        LintRule::SequenceType => fix(
            "CREATE SEQUENCE _r_seq AS INTEGER CACHE 1;",
            "CREATE SEQUENCE with type",
        ),
        LintRule::SequenceCache => fix("CREATE SEQUENCE _r_seq CACHE 100;", "CACHE value"),
        LintRule::SequenceCacheMissing => fix("CREATE SEQUENCE _r_seq;", "CACHE"),
        LintRule::AddColumnConstraint => fix(
            "ALTER TABLE _clust_base ADD COLUMN status VARCHAR(50) DEFAULT 'pending';",
            "ADD COLUMN",
        ),
        LintRule::Collation => fix(
            "CREATE TABLE _r (id INT, name VARCHAR(100) COLLATE \"en_US\");",
            "COLLATE",
        ),
        LintRule::TransactionIsolation => {
            fix("BEGIN ISOLATION LEVEL SERIALIZABLE;", "isolation level")
        }
        LintRule::SetTransaction => fix(
            "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;",
            "SET TRANSACTION",
        ),
        LintRule::MultiDdlTransaction => fix(
            "BEGIN;\nCREATE TABLE _r_a (id INT);\nCREATE TABLE _r_b (id INT);\nCOMMIT;",
            "DDL statements",
        ),
        LintRule::MixedDdlDmlTransaction => fix_with(
            "BEGIN;\nCREATE TABLE _r_a (id INT);\nINSERT INTO _r_a VALUES (1);\nCOMMIT;",
            "DDL and DML",
            "",
            "DROP TABLE IF EXISTS _r_a;",
        ),

        // ─── ALTER TABLE per-arm rules ────────────────────────────────────
        LintRule::AtUnsupportedDropColumn => {
            fix("ALTER TABLE _clust_base DROP COLUMN col;", "DROP COLUMN")
        }
        LintRule::AtUnsupportedAlterColumnSetType => fix(
            "ALTER TABLE _clust_base ALTER COLUMN col TYPE TEXT;",
            "TYPE is not supported",
        ),
        LintRule::AtUnsupportedAlterColumnSetNotNull => fix(
            "ALTER TABLE _clust_base ALTER COLUMN col SET NOT NULL;",
            "SET NOT NULL",
        ),
        LintRule::AtUnsupportedAlterColumnAddGenerated => fix(
            "ALTER TABLE _clust_base ALTER COLUMN col ADD GENERATED ALWAYS AS IDENTITY;",
            "ADD GENERATED AS IDENTITY",
        ),
        LintRule::AtUnsupportedAddCheck => fix(
            "ALTER TABLE _clust_base ADD CONSTRAINT _rej_chk CHECK (id > 0);",
            "ADD CHECK",
        ),
        LintRule::AtUnsupportedAddUnique => fix(
            "ALTER TABLE _clust_base ADD CONSTRAINT _rej_uq UNIQUE (id);",
            "ADD UNIQUE",
        ),
        LintRule::AtUnsupportedAddPrimaryKey => fix(
            "ALTER TABLE _clust_base ADD CONSTRAINT _rej_pk PRIMARY KEY (id);",
            "ADD PRIMARY KEY",
        ),
        LintRule::AtUnsupportedDropConstraint => fix(
            "ALTER TABLE _clust_base DROP CONSTRAINT _rej_c;",
            "DROP CONSTRAINT",
        ),
        LintRule::AtUnsupportedPrimaryKeyUsingIndex => fix(
            "ALTER TABLE _clust_base ADD CONSTRAINT _rej_pk PRIMARY KEY USING INDEX _clust_base_pkey;",
            "PRIMARY KEY USING INDEX",
        ),
        LintRule::AtUnsupportedUniqueUsingIndex => fix(
            "ALTER TABLE _clust_base ADD CONSTRAINT _rej_u UNIQUE USING INDEX _clust_base_idx;",
            "UNIQUE USING INDEX",
        ),
        LintRule::AtUnsupportedRowLevelSecurity => fix(
            "ALTER TABLE _clust_base ENABLE ROW LEVEL SECURITY;",
            "ROW LEVEL SECURITY",
        ),
        LintRule::AtUnsupportedReplicaIdentity => fix(
            "ALTER TABLE _clust_base REPLICA IDENTITY FULL;",
            "REPLICA IDENTITY",
        ),
        LintRule::ValidateConstraintAsync => fix(
            "ALTER TABLE _clust_base VALIDATE CONSTRAINT _rej_c;",
            "VALIDATE CONSTRAINT",
        ),
        LintRule::AtUnsupportedRewriteRule => fix(
            "ALTER TABLE _clust_base DISABLE RULE _rej_rule;",
            "RULE",
        ),

        // ─── Unsupported top-level statements ─────────────────────────────
        LintRule::UnsupportedTempView => fix("CREATE TEMP VIEW _r AS SELECT 1;", "TEMPORARY"),
        LintRule::UnsupportedMaterializedView => fix_with(
            "CREATE MATERIALIZED VIEW _rej_mv AS SELECT 1 AS id;",
            "MATERIALIZED VIEW",
            "",
            "DROP MATERIALIZED VIEW IF EXISTS _rej_mv;",
        ),
        LintRule::UnsupportedCreateTrigger => fix(
            "CREATE TRIGGER _rej_trg AFTER INSERT ON _clust_base FOR EACH ROW EXECUTE FUNCTION f();",
            "TRIGGER",
        ),
        LintRule::UnsupportedCreateExtension => {
            fix("CREATE EXTENSION IF NOT EXISTS pgcrypto;", "EXTENSION")
        }
        LintRule::UnsupportedCreateFunctionNonSql => fix_with(
            "CREATE FUNCTION _rej_fn() RETURNS INT LANGUAGE plpgsql AS $$ BEGIN RETURN 1; END $$;",
            "LANGUAGE SQL",
            "",
            "DROP FUNCTION IF EXISTS _rej_fn();",
        ),
        LintRule::UnsupportedCreateProcedure => fix_with(
            "CREATE PROCEDURE _rej_proc() AS BEGIN END;",
            "PROCEDURE",
            "",
            "DROP PROCEDURE IF EXISTS _rej_proc();",
        ),
        LintRule::UnsupportedCreateDatabase => fix("CREATE DATABASE _rej_db;", "DATABASE"),
        LintRule::UnsupportedCreatePolicy => fix(
            "CREATE POLICY _rej_pol ON _clust_base USING (true);",
            "POLICY",
        ),
        LintRule::UnsupportedSavepoint => fix("SAVEPOINT sp1;", "SAVEPOINT"),
        LintRule::UnsupportedReleaseSavepoint => {
            fix("RELEASE SAVEPOINT sp1;", "RELEASE SAVEPOINT")
        }
        LintRule::UnsupportedRollbackToSavepoint => {
            fix("ROLLBACK TO SAVEPOINT sp1;", "ROLLBACK TO SAVEPOINT")
        }
        LintRule::UnsupportedDeclareCursor => {
            fix("DECLARE _rej_cur CURSOR FOR SELECT 1;", "CURSOR")
        }
        LintRule::UnsupportedCreateType => fix_with(
            "CREATE TYPE _rej_mood AS ENUM ('happy', 'sad');",
            "CREATE TYPE",
            "",
            "DROP TYPE IF EXISTS _rej_mood;",
        ),
        LintRule::UnsupportedCreateServer => fix(
            "CREATE SERVER _rej_srv FOREIGN DATA WRAPPER _rej_fdw;",
            "SERVER",
        ),
        LintRule::UnsupportedVacuum => fix("VACUUM;", "VACUUM"),
        LintRule::UnsupportedAlterIndex => {
            fix("ALTER INDEX _rej_idx RENAME TO _rej_idx2;", "ALTER INDEX")
        }
        LintRule::UnsupportedCopyFromFile => {
            fix("COPY _clust_base FROM '/tmp/x.csv';", "COPY")
        }
        LintRule::UnsupportedLockTable => fix(
            "LOCK TABLE _clust_base IN ACCESS EXCLUSIVE MODE;",
            "LOCK TABLE",
        ),
        LintRule::UnsupportedAlterAggregate => fix(
            "ALTER AGGREGATE _rej_agg(integer) RENAME TO _rej_agg2;",
            "ALTER AGGREGATE",
        ),
        LintRule::UnsupportedAlterFunctionProperty => {
            fix("ALTER FUNCTION _rej_fn() IMMUTABLE;", "ALTER FUNCTION")
        }
        LintRule::UnsupportedAlterPolicy => fix(
            "ALTER POLICY _rej_pol ON _clust_base USING (true);",
            "ALTER POLICY",
        ),
        LintRule::UnsupportedAlterType => fix(
            "ALTER TYPE _rej_mood ADD VALUE 'neutral';",
            "ALTER TYPE",
        ),
        LintRule::UnsupportedAlterRoleProperty => fix(
            "ALTER ROLE _rej_role WITH PASSWORD 'pw';",
            "ALTER ROLE",
        ),
        LintRule::UnsupportedAlterRoleSet => fix(
            "ALTER ROLE _rej_role SET work_mem = '64MB';",
            "ALTER ROLE",
        ),
        LintRule::UnsupportedAlterUser => fix(
            "ALTER USER _rej_user WITH PASSWORD 'pw';",
            "ALTER USER",
        ),
        LintRule::UnsupportedDropMaterializedView => {
            fix("DROP MATERIALIZED VIEW _rej_mv;", "MATERIALIZED VIEW")
        }
        LintRule::UnsupportedDropType => fix("DROP TYPE _rej_t;", "DROP TYPE"),
        LintRule::UnsupportedDropTrigger => fix(
            "DROP TRIGGER _rej_trg ON _clust_base;",
            "DROP TRIGGER",
        ),
        LintRule::UnsupportedDropPolicy => fix(
            "DROP POLICY _rej_pol ON _clust_base;",
            "DROP POLICY",
        ),
        LintRule::UnsupportedListen => fix("LISTEN _rej_ch;", "LISTEN"),
        LintRule::UnsupportedUnlisten => fix("UNLISTEN _rej_ch;", "UNLISTEN"),
        LintRule::UnsupportedNotify => fix("NOTIFY _rej_ch;", "NOTIFY"),
        LintRule::UnsupportedLoad => fix("LOAD 'auto_explain';", "LOAD"),
        LintRule::UnsupportedPrepare => {
            fix("PREPARE _rej_p AS SELECT 1;", "PREPARE")
        }
        LintRule::UnsupportedDeallocate => fix("DEALLOCATE _rej_p;", "DEALLOCATE"),
        LintRule::UnsupportedDiscard => fix("DISCARD ALL;", "DISCARD"),
        LintRule::UnsupportedPartitionOf => fix(
            "CREATE TABLE _rej_part PARTITION OF _clust_base FOR VALUES FROM (1) TO (100);",
            "PARTITION OF",
        ),
        LintRule::UnsupportedOnCommit => fix(
            "CREATE TABLE _rej_oc (id INT) ON COMMIT DROP;",
            "ON COMMIT",
        ),
        LintRule::UnsupportedCreateTableWithStorageParameters => fix(
            "CREATE TABLE _rej_wo (id INT) WITH (autovacuum_enabled = false);",
            "WITH",
        ),

        LintRule::SerialSequenceIdiom => fix(
            "CREATE TABLE _r (id integer NOT NULL);\n\
             CREATE SEQUENCE _r_id_seq AS integer START WITH 1 INCREMENT BY 1 CACHE 1;\n\
             ALTER SEQUENCE _r_id_seq OWNED BY _r.id;\n\
             ALTER TABLE ONLY _r ALTER COLUMN id SET DEFAULT nextval('_r_id_seq'::regclass);",
            "is populated by a sequence",
        ),
        LintRule::AlterAddUniqueCollapse => fix(
            "CREATE TABLE _r (id integer NOT NULL, email text NOT NULL);\n\
             ALTER TABLE ONLY _r ADD CONSTRAINT _r_email_key UNIQUE (email);",
            "ALTER TABLE ADD CONSTRAINT",
        ),
        LintRule::AlterAddPrimaryKeyCollapse => fix(
            "CREATE TABLE _r (id integer NOT NULL, email text NOT NULL);\n\
             ALTER TABLE ONLY _r ADD CONSTRAINT _r_pkey PRIMARY KEY (id);",
            "ALTER TABLE ADD CONSTRAINT",
        ),
        // No cluster reject-fixture: this is a collapse *fix* (folds the
        // ALTER ... ADD GENERATED into the CREATE TABLE), not an unsupported-op
        // rejection, so the harness's "unfixed input must be rejected" check
        // does not apply. Collapse behavior is covered by unit tests in
        // `rules::identity_idiom`.
        LintRule::IdentityAddGeneratedCollapse => None,
        LintRule::AlterColumnSetCompressionStrip => fix(
            "CREATE TABLE _r (id bigint NOT NULL, payload text);\n\
             ALTER TABLE ONLY _r ALTER COLUMN payload SET COMPRESSION lz4;",
            "SET COMPRESSION is not supported",
        ),
        LintRule::ParseError => None,
        // MySQL-translation warnings are emitted only by `fix_sql_mysql` on
        // MySQL-dialect input; the PG-dialect fixture harness can't exercise
        // them, and they carry no standalone unfixed→rejected fixture.
        LintRule::MysqlUnsignedWidened
        | LintRule::MysqlEnumToVarchar
        | LintRule::MysqlSetToText
        | LintRule::MysqlAutoIncrementToIdentity
        | LintRule::MysqlOnUpdateDropped
        | LintRule::MysqlInvalidDefaultDropped
        | LintRule::MysqlIndexPrefixDropped => None,
    }
}

/// Multi-statement SQL that must lint clean AND execute on a real DSQL cluster.
/// Shared between unit and cluster tests so both validate the same cases.
///
/// Each entry: (label, sql, cleanup_sql).
/// - `sql` is executed via `run_sql_file` in cluster tests (multi-statement).
/// - `cleanup_sql` tears down objects created by the test case.
#[allow(dead_code)] // only used by tests/dsql_cluster_test.rs (cfg=dsql_cluster)
pub const CLEAN_MULTI_STATEMENT_CASES: &[(&str, &str, &str)] = &[
    (
        "single-ddl-in-txn",
        "CREATE TABLE _clust_txn_a (id INT);\nBEGIN;\nCREATE TABLE _clust_txn_b (id INT);\nCOMMIT;",
        "DROP TABLE IF EXISTS _clust_txn_a; DROP TABLE IF EXISTS _clust_txn_b;",
    ),
    (
        "bare-ddl-no-txn",
        "CREATE TABLE _clust_txn_c (id INT);\nCREATE TABLE _clust_txn_d (id INT);",
        "DROP TABLE IF EXISTS _clust_txn_c; DROP TABLE IF EXISTS _clust_txn_d;",
    ),
    (
        "dml-only-in-txn",
        "BEGIN;\nSELECT 1;\nCOMMIT;",
        "",
    ),
    (
        "ddl-plus-dml-in-txn",
        "CREATE TABLE _clust_txn_e (id INT);\nBEGIN;\nINSERT INTO _clust_txn_e VALUES (1);\nCOMMIT;",
        "DROP TABLE IF EXISTS _clust_txn_e;",
    ),
    (
        "empty-txn",
        "BEGIN;\nCOMMIT;",
        "",
    ),
    (
        "separate-single-ddl-txns",
        "BEGIN;\nCREATE TABLE _clust_txn_g (id INT);\nCOMMIT;\nBEGIN;\nCREATE TABLE _clust_txn_h (id INT);\nCOMMIT;",
        "DROP TABLE IF EXISTS _clust_txn_g; DROP TABLE IF EXISTS _clust_txn_h;",
    ),
];
