/// Column types that DSQL supports. Shared between unit and cluster tests
/// to keep the two lists from drifting.
///
/// Source: https://docs.aws.amazon.com/aurora-dsql/latest/userguide/
///         working-with-postgresql-compatibility-supported-data-types.html
pub const SUPPORTED_TYPES: &[(&str, &str)] = &[
    // Numeric
    ("smallint", "SMALLINT"),
    ("int2", "INT2"),
    ("integer", "INTEGER"),
    ("int", "INT"),
    ("int4", "INT4"),
    ("bigint", "BIGINT"),
    ("int8", "INT8"),
    ("real", "REAL"),
    ("float4", "FLOAT4"),
    ("double-precision", "DOUBLE PRECISION"),
    ("float8", "FLOAT8"),
    ("numeric", "NUMERIC(10,2)"),
    ("decimal", "DECIMAL(18,6)"),
    ("dec", "DEC(5,2)"),
    // Character
    ("char", "CHAR(10)"),
    ("character", "CHARACTER(20)"),
    ("varchar", "VARCHAR(255)"),
    ("character-varying", "CHARACTER VARYING(100)"),
    ("text", "TEXT"),
    ("bpchar", "BPCHAR(50)"),
    // Date/time
    ("date", "DATE"),
    ("time", "TIME"),
    ("time-tz", "TIME WITH TIME ZONE"),
    ("timestamp", "TIMESTAMP"),
    ("timestamp-tz", "TIMESTAMP WITH TIME ZONE"),
    ("interval", "INTERVAL"),
    // Miscellaneous
    ("boolean", "BOOLEAN"),
    ("bool", "BOOL"),
    ("bytea", "BYTEA"),
    ("uuid", "UUID"),
    // Identity columns
    (
        "identity-always",
        "BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 1)",
    ),
    (
        "identity-by-default",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
    ),
    (
        "identity-cache-65536",
        "BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 65536)",
    ),
    (
        "identity-by-default-cache-65536",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 65536)",
    ),
];
