/// Column types that DSQL supports. Shared between unit and cluster tests
/// to keep the two lists from drifting.
///
/// Source: https://docs.aws.amazon.com/aurora-dsql/latest/userguide/
///         working-with-postgresql-compatibility-supported-data-types.html
pub const SUPPORTED_TYPES: &[(&str, &str)] = &[
    // Numeric
    ("smallint", "SMALLINT"),
    ("int2", "INT2"),
    ("integer", "INTEGER"),
    ("int", "INT"),
    ("int4", "INT4"),
    ("bigint", "BIGINT"),
    ("int8", "INT8"),
    ("real", "REAL"),
    ("float4", "FLOAT4"),
    ("double-precision", "DOUBLE PRECISION"),
    ("float8", "FLOAT8"),
    ("numeric", "NUMERIC(10,2)"),
    ("decimal", "DECIMAL(18,6)"),
    ("dec", "DEC(5,2)"),
    // Character
    ("char", "CHAR(10)"),
    ("character", "CHARACTER(20)"),
    ("varchar", "VARCHAR(255)"),
    ("character-varying", "CHARACTER VARYING(100)"),
    ("text", "TEXT"),
    ("bpchar", "BPCHAR(50)"),
    // Date/time
    ("date", "DATE"),
    ("time", "TIME"),
    ("time-tz", "TIME WITH TIME ZONE"),
    ("timestamp", "TIMESTAMP"),
    ("timestamp-tz", "TIMESTAMP WITH TIME ZONE"),
    ("interval", "INTERVAL"),
    // Miscellaneous
    ("boolean", "BOOLEAN"),
    ("bool", "BOOL"),
    ("bytea", "BYTEA"),
    ("uuid", "UUID"),
    // Identity columns
    (
        "identity-always",
        "BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 1)",
    ),
    (
        "identity-by-default",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
    ),
    (
        "identity-cache-65536",
        "BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 65536)",
    ),
    (
        "identity-by-default-cache-65536",
        "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 65536)",
    ),
];

/// Multi-statement SQL that the linter should pass as clean (no DDL transaction errors).
/// Shared between unit and cluster tests so both validate the same cases.
///
/// Each entry: (label, sql, cleanup_sql).
/// - `sql` is executed via `run_sql_file` in cluster tests (multi-statement).
/// - `cleanup_sql` tears down objects created by the test case.
pub const CLEAN_MULTI_STATEMENT_CASES: &[(&str, &str, &str)] = &[
    (
        "single-ddl-in-txn",
        "CREATE TABLE _clust_txn_a (id INT);\nBEGIN;\nCREATE TABLE _clust_txn_b (id INT);\nCOMMIT;",
        "DROP TABLE IF EXISTS _clust_txn_a; DROP TABLE IF EXISTS _clust_txn_b;",
    ),
    (
        "bare-ddl-no-txn",
        "CREATE TABLE _clust_txn_c (id INT);\nCREATE TABLE _clust_txn_d (id INT);",
        "DROP TABLE IF EXISTS _clust_txn_c; DROP TABLE IF EXISTS _clust_txn_d;",
    ),
    (
        "dml-only-in-txn",
        "BEGIN;\nSELECT 1;\nCOMMIT;",
        "",
    ),
    (
        "ddl-plus-dml-in-txn",
        "CREATE TABLE _clust_txn_e (id INT);\nBEGIN;\nCREATE TABLE _clust_txn_f (id INT);\nINSERT INTO _clust_txn_e VALUES (1);\nCOMMIT;",
        "DROP TABLE IF EXISTS _clust_txn_e; DROP TABLE IF EXISTS _clust_txn_f;",
    ),
    (
        "empty-txn",
        "BEGIN;\nCOMMIT;",
        "",
    ),
    (
        "separate-single-ddl-txns",
        "BEGIN;\nCREATE TABLE _clust_txn_g (id INT);\nCOMMIT;\nBEGIN;\nCREATE TABLE _clust_txn_h (id INT);\nCOMMIT;",
        "DROP TABLE IF EXISTS _clust_txn_g; DROP TABLE IF EXISTS _clust_txn_h;",
    ),
];
