use dsql_lint::{fix_sql, FixResult};

// ═══════════════════════════════════════════════════════════════════════
// FIX TIER MATRIX
// ═══════════════════════════════════════════════════════════════════════
// Every fixable rule must emit the correct FixResult variant.
// Adding a new fix rule = add one row here. The three matrix tests below
// will automatically cover: tier, roundtrip re-lint, and (if snapshot is
// provided) exact output.
//
// (label, sql, expected_tier)

const FIX_TIER_CASES: &[(&str, &str, &str)] = &[
    // ── Tier 1: Fixed ─────────────────────────────────────────────────
    ("json", "CREATE TABLE t (id INT, data JSON);", "Fixed"),
    ("jsonb", "CREATE TABLE t (id INT, data JSONB);", "Fixed"),
    ("index-async", "CREATE INDEX idx ON t(col);", "Fixed"),
    (
        "index-concurrently",
        "CREATE INDEX CONCURRENTLY idx ON t(col);",
        "Fixed",
    ),
    (
        "index-using-btree",
        "CREATE INDEX ASYNC idx ON t USING btree(col);",
        "Fixed",
    ),
    ("seq-type", "CREATE SEQUENCE s AS INTEGER CACHE 1;", "Fixed"),
    ("seq-missing-cache", "CREATE SEQUENCE s;", "Fixed"),
    (
        "identity-missing-cache",
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY);",
        "Fixed",
    ),
    ("isolation", "BEGIN ISOLATION LEVEL SERIALIZABLE;", "Fixed"),
    (
        "isolation-read-committed",
        "BEGIN ISOLATION LEVEL READ COMMITTED;",
        "Fixed",
    ),
    (
        "alter-add-col-json",
        "ALTER TABLE t ADD COLUMN data JSON;",
        "Fixed",
    ),
    // ── Tier 2: FixedWithWarning ──────────────────────────────────────
    (
        "serial",
        "CREATE TABLE t (id SERIAL PRIMARY KEY);",
        "FixedWithWarning",
    ),
    (
        "bigserial",
        "CREATE TABLE t (id BIGSERIAL PRIMARY KEY);",
        "FixedWithWarning",
    ),
    (
        "serial4",
        "CREATE TABLE t (id SERIAL4 PRIMARY KEY);",
        "FixedWithWarning",
    ),
    (
        "serial8",
        "CREATE TABLE t (id SERIAL8 PRIMARY KEY);",
        "FixedWithWarning",
    ),
    (
        "smallserial",
        "CREATE TABLE t (id SMALLSERIAL PRIMARY KEY);",
        "FixedWithWarning",
    ),
    (
        "serial2",
        "CREATE TABLE t (id SERIAL2 PRIMARY KEY);",
        "FixedWithWarning",
    ),
    (
        "column-fk",
        "CREATE TABLE t (id INT, cid INT REFERENCES c(id));",
        "FixedWithWarning",
    ),
    (
        "table-fk",
        "CREATE TABLE t (id INT, cid INT, FOREIGN KEY (cid) REFERENCES c(id));",
        "FixedWithWarning",
    ),
    (
        "alter-fk",
        "ALTER TABLE t ADD CONSTRAINT fk_c FOREIGN KEY (cid) REFERENCES c(id);",
        "FixedWithWarning",
    ),
    (
        "temp-table",
        "CREATE TEMP TABLE t (id INT);",
        "FixedWithWarning",
    ),
    (
        "tablespace",
        "CREATE TABLE t (id INT) TABLESPACE my_space;",
        "FixedWithWarning",
    ),
    (
        "partition-by",
        "CREATE TABLE t (id INT) PARTITION BY RANGE (id);",
        "FixedWithWarning",
    ),
    (
        "inherits",
        "CREATE TABLE child (extra INT) INHERITS (parent);",
        "FixedWithWarning",
    ),
    (
        "temp-view",
        "CREATE TEMP VIEW v AS SELECT 1;",
        "FixedWithWarning",
    ),
    (
        "identity-type",
        "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY (CACHE 1));",
        "FixedWithWarning",
    ),
    (
        "identity-type-smallint",
        "CREATE TABLE t (id SMALLINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1));",
        "FixedWithWarning",
    ),
    (
        "index-using-gin",
        "CREATE INDEX ASYNC idx ON t USING gin(col);",
        "FixedWithWarning",
    ),
    (
        "index-using-hash",
        "CREATE INDEX ASYNC idx ON t USING hash(col);",
        "FixedWithWarning",
    ),
    (
        "seq-bad-cache",
        "CREATE SEQUENCE s CACHE 100;",
        "FixedWithWarning",
    ),
    (
        "identity-bad-cache",
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 100));",
        "FixedWithWarning",
    ),
    (
        "alter-add-col-fk",
        "ALTER TABLE t ADD COLUMN cid INT REFERENCES c(id);",
        "FixedWithWarning",
    ),
    // ── Unfixable ─────────────────────────────────────────────────────
    (
        "alter-add-col-serial",
        "ALTER TABLE t ADD COLUMN id SERIAL;",
        "Unfixable",
    ),
    (
        "alter-add-col-identity",
        "ALTER TABLE t ADD COLUMN id BIGINT GENERATED ALWAYS AS IDENTITY;",
        "Unfixable",
    ),
    (
        "alter-add-col-identity-non-bigint",
        "ALTER TABLE t ADD COLUMN id INT GENERATED ALWAYS AS IDENTITY (CACHE 1);",
        "Unfixable",
    ),
    (
        "alter-add-col-identity-bad-cache",
        "ALTER TABLE t ADD COLUMN id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 100);",
        "Unfixable",
    ),
    (
        "set-transaction",
        "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;",
        "Unfixable",
    ),
];

#[test]
fn fix_tier_matrix() {
    for (label, sql, expected_tier) in FIX_TIER_CASES {
        let result = fix_sql(sql);
        let has_expected = result.diagnostics.iter().any(|d| match &d.fix_result {
            FixResult::Fixed(_) => *expected_tier == "Fixed",
            FixResult::FixedWithWarning(_) => *expected_tier == "FixedWithWarning",
            FixResult::Unfixable => *expected_tier == "Unfixable",
        });
        assert!(
            has_expected,
            "[{label}] Expected {expected_tier} for:\n  {sql}\n  Got: {:?}",
            result
                .diagnostics
                .iter()
                .map(|d| &d.fix_result)
                .collect::<Vec<_>>()
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════
// ROUNDTRIP MATRIX
// ═══════════════════════════════════════════════════════════════════════
// Every Fixed/FixedWithWarning case: fix → re-lint → must produce zero errors.
// Unfixable cases are skipped (they'd re-lint with the same errors).

#[test]
fn fix_roundtrip_matrix() {
    for (label, sql, tier) in FIX_TIER_CASES {
        if *tier == "Unfixable" {
            continue;
        }
        let result = fix_sql(sql);
        let re_lint = dsql_lint::lint_sql(&result.sql);
        assert!(
            re_lint.is_empty(),
            "[{label}] Fixed SQL still has errors:\n  Input: {sql}\n  Fixed: {}\n  Errors: {re_lint:?}",
            result.sql
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════
// SNAPSHOT MATRIX
// ═══════════════════════════════════════════════════════════════════════
// Exact output verification for each fix type. Catches regressions in
// AST mutation or sqlparser serialization.
//
// (label, input, expected_output)

const SNAPSHOT_CASES: &[(&str, &str, &str)] = &[
    // Column fixes
    (
        "serial",
        "CREATE TABLE t (id SERIAL PRIMARY KEY);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "bigserial",
        "CREATE TABLE t (id BIGSERIAL PRIMARY KEY);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "serial4",
        "CREATE TABLE t (id SERIAL4 PRIMARY KEY);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "serial8",
        "CREATE TABLE t (id SERIAL8 PRIMARY KEY);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "smallserial",
        "CREATE TABLE t (id SMALLSERIAL PRIMARY KEY);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "serial2",
        "CREATE TABLE t (id SERIAL2 PRIMARY KEY);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "json",
        "CREATE TABLE t (id INT, data JSON);",
        "CREATE TABLE t (\n  id INT,\n  data TEXT  \n);\n",
    ),
    (
        "jsonb",
        "CREATE TABLE t (id INT, data JSONB);",
        "CREATE TABLE t (\n  id INT,\n  data TEXT  \n);\n",
    ),
    // Index fixes
    (
        "index-async",
        "CREATE INDEX idx ON t(col);",
        "CREATE INDEX ASYNC idx ON t(col);\n",
    ),
    (
        "index-concurrently",
        "CREATE INDEX CONCURRENTLY idx ON t(col);",
        "CREATE INDEX ASYNC idx ON t(col);\n",
    ),
    (
        "index-using-btree",
        "CREATE INDEX ASYNC idx ON t USING btree(col);",
        "CREATE INDEX ASYNC idx ON t(col);\n",
    ),
    (
        "index-using-gin",
        "CREATE INDEX ASYNC idx ON t USING gin(col);",
        "CREATE INDEX ASYNC idx ON t(col);\n",
    ),
    // Sequence fixes
    (
        "seq-type",
        "CREATE SEQUENCE s AS INTEGER CACHE 1;",
        "CREATE SEQUENCE s AS BIGINT CACHE 1;\n",
    ),
    (
        "seq-add-cache",
        "CREATE SEQUENCE s;",
        "CREATE SEQUENCE s CACHE 1;\n",
    ),
    (
        "seq-fix-cache",
        "CREATE SEQUENCE s CACHE 100;",
        "CREATE SEQUENCE s CACHE 1;\n",
    ),
    // Identity fixes
    (
        "identity-type-to-bigint",
        "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY (CACHE 1));",
        "CREATE TABLE t (\n  id BIGINT GENERATED ALWAYS AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "identity-add-cache",
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY);",
        "CREATE TABLE t (\n  id BIGINT GENERATED ALWAYS AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "identity-fix-cache",
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 100));",
        "CREATE TABLE t (\n  id BIGINT GENERATED ALWAYS AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    // Transaction isolation
    (
        "isolation",
        "BEGIN ISOLATION LEVEL SERIALIZABLE;",
        "BEGIN ISOLATION LEVEL REPEATABLE READ;\n",
    ),
    // FK removal
    (
        "column-fk",
        "CREATE TABLE t (id INT, cid INT REFERENCES c(id));",
        "CREATE TABLE t (\n  id INT,\n  cid INT  \n);\n",
    ),
    (
        "table-fk",
        "CREATE TABLE t (id INT, cid INT, FOREIGN KEY (cid) REFERENCES c(id));",
        "CREATE TABLE t (\n  id INT,\n  cid INT  \n);\n",
    ),
    // Clause removal
    (
        "partition-by",
        "CREATE TABLE t (id INT) PARTITION BY RANGE (id);",
        "CREATE TABLE t (\n  id INT  \n);\n",
    ),
    (
        "inherits",
        "CREATE TABLE child (extra INT) INHERITS (parent);",
        "CREATE TABLE child (\n  extra INT  \n);\n",
    ),
    (
        "temp-view",
        "CREATE TEMP VIEW v AS SELECT 1;",
        "CREATE VIEW v AS\nSELECT\n  1;\n",
    ),
    (
        "temp-table",
        "CREATE TEMP TABLE t (id INT);",
        "CREATE TABLE t (\n  id INT  \n);\n",
    ),
    (
        "tablespace",
        "CREATE TABLE t (id INT) TABLESPACE my_space;",
        "CREATE TABLE t (\n  id INT  \n) ;\n",
    ),
    // ALTER TABLE column fixes
    (
        "alter-add-col-json",
        "ALTER TABLE t ADD COLUMN data JSON;",
        "ALTER TABLE t ADD COLUMN data TEXT;\n",
    ),
    (
        "alter-add-col-fk",
        "ALTER TABLE t ADD COLUMN cid INT REFERENCES c(id);",
        "ALTER TABLE t ADD COLUMN cid INT;\n",
    ),
    // Mixed ALTER TABLE: FK removed, other ops kept
    (
        "alter-mixed-fk-col",
        "ALTER TABLE t ADD CONSTRAINT fk_c FOREIGN KEY (cid) REFERENCES c(id), ADD COLUMN x INT;",
        "ALTER TABLE t ADD COLUMN x INT;\n",
    ),
    // Multi-fix on one statement
    (
        "serial-plus-fk",
        "CREATE TABLE t (id SERIAL PRIMARY KEY, cid INT REFERENCES c(id));",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 ),\n  cid INT  \n);\n",
    ),
    // Multi-statement
    (
        "multi-statement",
        "CREATE TABLE t (id SERIAL PRIMARY KEY);\nCREATE INDEX idx ON t(id);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n\nCREATE INDEX ASYNC idx ON t(id);\n",
    ),
    // Clean passthrough
    (
        "clean-passthrough",
        "CREATE TABLE t (id UUID PRIMARY KEY, amount DECIMAL(10,2));",
        "CREATE TABLE t (id UUID PRIMARY KEY, amount DECIMAL(10,2));\n",
    ),
];

#[test]
fn fix_snapshot_matrix() {
    for (label, input, expected) in SNAPSHOT_CASES {
        let result = fix_sql(input);
        assert_eq!(
            result.sql, *expected,
            "[{label}]\n--- Input ---\n{input}\n--- Expected ---\n{expected}\n--- Got ---\n{}",
            result.sql
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════
// STANDALONE TESTS
// ═══════════════════════════════════════════════════════════════════════
// Cases with bespoke assertions that don't fit a matrix row.

#[test]
fn fix_alter_fk_removed_entirely() {
    let result = fix_sql("ALTER TABLE t ADD CONSTRAINT fk_c FOREIGN KEY (cid) REFERENCES c(id);");
    assert_eq!(
        result.sql, "",
        "ALTER TABLE with only FK should produce empty output"
    );
    assert_eq!(result.diagnostics.len(), 1);
}

#[test]
fn fix_clean_statement_verbatim() {
    let sql = "CREATE TABLE orders (id UUID PRIMARY KEY, amount DECIMAL(10,2))";
    let result = fix_sql(sql);
    assert_eq!(result.sql.trim(), format!("{sql};"));
    assert!(result.diagnostics.is_empty());
}

// ═══════════════════════════════════════════════════════════════════════
// FIXTURE TESTS
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn fix_sample_migration_reduces_errors() {
    let sql = include_str!("fixtures/sample_migration.sql");
    let original_diags = dsql_lint::lint_sql(sql);

    let result = dsql_lint::fix_sql(sql);
    let re_lint = dsql_lint::lint_sql(&result.sql);

    assert!(
        re_lint.len() < original_diags.len(),
        "Expected fewer errors after fix.\n  Before: {}\n  After: {}",
        original_diags.len(),
        re_lint.len()
    );

    let fixable_patterns = ["SERIAL", "ASYNC", "FOREIGN KEY", "TEMPORARY tables"];
    for pattern in fixable_patterns {
        assert!(
            !re_lint.iter().any(|d| d.message.contains(pattern)),
            "Fixed output still contains fixable error: {pattern}\n  Errors: {re_lint:?}"
        );
    }
}

#[test]
fn fix_clean_file_is_verbatim() {
    let sql = include_str!("fixtures/clean_all_types.sql");
    let result = dsql_lint::fix_sql(sql);
    assert!(
        result.diagnostics.is_empty(),
        "Clean file should produce no diagnostics, got: {:?}",
        result.diagnostics
    );
    let re_lint = dsql_lint::lint_sql(&result.sql);
    assert!(
        re_lint.is_empty(),
        "Re-linting fixed output of clean file produced errors: {re_lint:?}"
    );
}
