use dsql_lint::{fix_sql, FixResult, LintRule};

// ═══════════════════════════════════════════════════════════════════════
// FIX TIER MATRIX
// ═══════════════════════════════════════════════════════════════════════
// Every fixable rule must emit the correct FixResult variant.
// Adding a new fix rule = add one row here. The three matrix tests below
// will automatically cover: tier, roundtrip re-lint, and (if snapshot is
// provided) exact output.
//
// (label, sql, expected_tier)

const FIX_TIER_CASES: &[(&str, &str, &str)] = &[
    // ── Tier 1: Fixed ─────────────────────────────────────────────────
    (
        "index-using-btree",
        "CREATE INDEX ASYNC idx ON t USING btree(col);",
        "Fixed",
    ),
    ("seq-missing-cache", "CREATE SEQUENCE s;", "Fixed"),
    (
        "identity-missing-cache",
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY);",
        "Fixed",
    ),
    (
        "collate-c",
        "CREATE TABLE t (name VARCHAR(100) COLLATE \"C\");",
        "Fixed",
    ),
    (
        "collate-c-lowercase",
        "CREATE TABLE t (name VARCHAR(100) COLLATE \"c\");",
        "Fixed",
    ),
    (
        "collate-posix",
        "CREATE TABLE t (name VARCHAR(100) COLLATE \"POSIX\");",
        "Fixed",
    ),
    (
        "collate-pg-catalog-c",
        "CREATE TABLE t (name VARCHAR(100) COLLATE pg_catalog.\"C\");",
        "Fixed",
    ),
    // ── Tier 2: FixedWithWarning ──────────────────────────────────────
    // Async index builds change timing semantics (index not ready on return).
    (
        "index-async",
        "CREATE INDEX idx ON t(col);",
        "FixedWithWarning",
    ),
    (
        "index-concurrently",
        "CREATE INDEX CONCURRENTLY idx ON t(col);",
        "FixedWithWarning",
    ),
    // Sequence widening to BIGINT changes the consumable range.
    (
        "seq-type",
        "CREATE SEQUENCE s AS INTEGER CACHE 1;",
        "FixedWithWarning",
    ),
    // Isolation downgrade changes concurrency semantics.
    (
        "isolation",
        "BEGIN ISOLATION LEVEL SERIALIZABLE;",
        "FixedWithWarning",
    ),
    (
        "isolation-read-committed",
        "BEGIN ISOLATION LEVEL READ COMMITTED;",
        "FixedWithWarning",
    ),
    (
        "serial",
        "CREATE TABLE t (id SERIAL PRIMARY KEY);",
        "FixedWithWarning",
    ),
    (
        "bigserial",
        "CREATE TABLE t (id BIGSERIAL PRIMARY KEY);",
        "FixedWithWarning",
    ),
    (
        "serial4",
        "CREATE TABLE t (id SERIAL4 PRIMARY KEY);",
        "FixedWithWarning",
    ),
    (
        "serial8",
        "CREATE TABLE t (id SERIAL8 PRIMARY KEY);",
        "FixedWithWarning",
    ),
    (
        "smallserial",
        "CREATE TABLE t (id SMALLSERIAL PRIMARY KEY);",
        "FixedWithWarning",
    ),
    (
        "serial2",
        "CREATE TABLE t (id SERIAL2 PRIMARY KEY);",
        "FixedWithWarning",
    ),
    (
        "column-fk",
        "CREATE TABLE t (id INT, cid INT REFERENCES c(id));",
        "FixedWithWarning",
    ),
    (
        "table-fk",
        "CREATE TABLE t (id INT, cid INT, FOREIGN KEY (cid) REFERENCES c(id));",
        "FixedWithWarning",
    ),
    (
        "alter-fk",
        "ALTER TABLE t ADD CONSTRAINT fk_c FOREIGN KEY (cid) REFERENCES c(id);",
        "FixedWithWarning",
    ),
    (
        "temp-table",
        "CREATE TEMP TABLE t (id INT);",
        "FixedWithWarning",
    ),
    (
        "tablespace",
        "CREATE TABLE t (id INT) TABLESPACE my_space;",
        "FixedWithWarning",
    ),
    (
        "partition-by",
        "CREATE TABLE t (id INT) PARTITION BY RANGE (id);",
        "FixedWithWarning",
    ),
    (
        "inherits",
        "CREATE TABLE child (extra INT) INHERITS (parent);",
        "FixedWithWarning",
    ),
    (
        "temp-view",
        "CREATE TEMP VIEW v AS SELECT 1;",
        "FixedWithWarning",
    ),
    (
        "identity-type",
        "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY (CACHE 1));",
        "FixedWithWarning",
    ),
    (
        "identity-type-smallint",
        "CREATE TABLE t (id SMALLINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1));",
        "FixedWithWarning",
    ),
    (
        "index-using-gin",
        "CREATE INDEX ASYNC idx ON t USING gin(col);",
        "FixedWithWarning",
    ),
    (
        "index-using-hash",
        "CREATE INDEX ASYNC idx ON t USING hash(col);",
        "FixedWithWarning",
    ),
    (
        "index-using-btree-after-cols",
        "CREATE INDEX ASYNC idx ON t(col) USING btree;",
        "Fixed",
    ),
    (
        "index-using-hash-after-cols",
        "CREATE INDEX ASYNC idx ON t(col) USING hash;",
        "FixedWithWarning",
    ),
    (
        "seq-bad-cache",
        "CREATE SEQUENCE s CACHE 100;",
        "FixedWithWarning",
    ),
    (
        "identity-bad-cache",
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 100));",
        "FixedWithWarning",
    ),
    (
        "alter-add-col-fk",
        "ALTER TABLE t ADD COLUMN cid INT REFERENCES c(id);",
        "FixedWithWarning",
    ),
    (
        "collate-en-us",
        "CREATE TABLE t (name VARCHAR(100) COLLATE \"en_US\");",
        "FixedWithWarning",
    ),
    (
        "collate-default",
        "CREATE TABLE t (name VARCHAR(100) COLLATE \"default\");",
        "FixedWithWarning",
    ),
    (
        "alter-add-col-collate-c",
        "ALTER TABLE t ADD COLUMN name VARCHAR(100) COLLATE \"C\";",
        "Fixed",
    ),
    (
        "alter-add-col-collate-en-us",
        "ALTER TABLE t ADD COLUMN name VARCHAR(100) COLLATE \"en_US\";",
        "FixedWithWarning",
    ),
    (
        "serial-idiom",
        "CREATE TABLE public.t (id integer NOT NULL);\
         CREATE SEQUENCE public.t_id_seq CACHE 1;\
         ALTER SEQUENCE public.t_id_seq OWNED BY public.t.id;\
         ALTER TABLE ONLY public.t ALTER COLUMN id SET DEFAULT nextval('public.t_id_seq'::regclass);",
        "FixedWithWarning",
    ),
    (
        "unique-collapse",
        "CREATE TABLE t (id integer NOT NULL, email text NOT NULL);\nALTER TABLE ONLY t ADD CONSTRAINT t_email_key UNIQUE (email);",
        "Fixed",
    ),
    (
        "primary-key-collapse",
        "CREATE TABLE t (id integer NOT NULL, email text NOT NULL);\nALTER TABLE ONLY t ADD CONSTRAINT t_pkey PRIMARY KEY (id);",
        "Fixed",
    ),
    (
        "primary-key-collapse-with-include",
        "CREATE TABLE t (id integer NOT NULL, payload text);\nALTER TABLE ONLY t ADD CONSTRAINT t_pkey PRIMARY KEY (id) INCLUDE (payload);",
        "Fixed",
    ),
    (
        "unique-collapse-with-include",
        "CREATE TABLE t (id integer NOT NULL, email text NOT NULL, payload text);\nALTER TABLE ONLY t ADD CONSTRAINT t_uk UNIQUE (email) INCLUDE (payload);",
        "Fixed",
    ),
    // ── Unfixable ─────────────────────────────────────────────────────
    (
        "alter-add-col-serial",
        "ALTER TABLE t ADD COLUMN id SERIAL;",
        "Unfixable",
    ),
    (
        "alter-add-col-identity",
        "ALTER TABLE t ADD COLUMN id BIGINT GENERATED ALWAYS AS IDENTITY;",
        "Unfixable",
    ),
    (
        "alter-add-col-identity-non-bigint",
        "ALTER TABLE t ADD COLUMN id INT GENERATED ALWAYS AS IDENTITY (CACHE 1);",
        "Unfixable",
    ),
    (
        "alter-add-col-identity-bad-cache",
        "ALTER TABLE t ADD COLUMN id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 100);",
        "Unfixable",
    ),
    (
        "set-transaction",
        "SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;",
        "Unfixable",
    ),
];

#[test]
fn fix_tier_matrix() {
    for (label, sql, expected_tier) in FIX_TIER_CASES {
        let result = fix_sql(sql);
        let has_expected = result.diagnostics.iter().any(|d| match &d.fix_result {
            FixResult::Fixed(_) => *expected_tier == "Fixed",
            FixResult::FixedWithWarning(_) => *expected_tier == "FixedWithWarning",
            FixResult::Unfixable => *expected_tier == "Unfixable",
        });
        assert!(
            has_expected,
            "[{label}] Expected {expected_tier} for:\n  {sql}\n  Got: {:?}",
            result
                .diagnostics
                .iter()
                .map(|d| &d.fix_result)
                .collect::<Vec<_>>()
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════
// ROUNDTRIP MATRIX
// ═══════════════════════════════════════════════════════════════════════
// Every Fixed/FixedWithWarning case: fix → re-lint → must produce zero errors.
// Unfixable cases are skipped (they'd re-lint with the same errors).

#[test]
fn fix_roundtrip_matrix() {
    for (label, sql, tier) in FIX_TIER_CASES {
        if *tier == "Unfixable" {
            continue;
        }
        let result = fix_sql(sql);
        let re_lint = dsql_lint::lint_sql(&result.sql);
        assert!(
            re_lint.is_empty(),
            "[{label}] Fixed SQL still has errors:\n  Input: {sql}\n  Fixed: {}\n  Errors: {re_lint:?}",
            result.sql
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════
// SNAPSHOT MATRIX
// ═══════════════════════════════════════════════════════════════════════
// Exact output verification for each fix type. Catches regressions in
// AST mutation or sqlparser serialization.
//
// (label, input, expected_output)

const SNAPSHOT_CASES: &[(&str, &str, &str)] = &[
    // Column fixes
    (
        "serial",
        "CREATE TABLE t (id SERIAL PRIMARY KEY);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "bigserial",
        "CREATE TABLE t (id BIGSERIAL PRIMARY KEY);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "serial4",
        "CREATE TABLE t (id SERIAL4 PRIMARY KEY);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "serial8",
        "CREATE TABLE t (id SERIAL8 PRIMARY KEY);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "smallserial",
        "CREATE TABLE t (id SMALLSERIAL PRIMARY KEY);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "serial2",
        "CREATE TABLE t (id SERIAL2 PRIMARY KEY);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    // Index fixes
    (
        "index-async",
        "CREATE INDEX idx ON t(col);",
        "CREATE INDEX ASYNC idx ON t(col);\n",
    ),
    (
        "index-concurrently",
        "CREATE INDEX CONCURRENTLY idx ON t(col);",
        "CREATE INDEX ASYNC idx ON t(col);\n",
    ),
    (
        "index-using-btree",
        "CREATE INDEX ASYNC idx ON t USING btree(col);",
        "CREATE INDEX ASYNC idx ON t(col);\n",
    ),
    (
        "index-using-gin",
        "CREATE INDEX ASYNC idx ON t USING gin(col);",
        "CREATE INDEX ASYNC idx ON t(col);\n",
    ),
    (
        "index-using-btree-after-cols",
        "CREATE INDEX ASYNC idx ON t(col) USING btree;",
        "CREATE INDEX ASYNC idx ON t(col);\n",
    ),
    (
        "index-using-hash-after-cols",
        "CREATE INDEX ASYNC idx ON t(col) USING hash;",
        "CREATE INDEX ASYNC idx ON t(col);\n",
    ),
    (
        "index-using-no-async-after-cols",
        "CREATE INDEX idx ON t(col) USING btree;",
        "CREATE INDEX ASYNC idx ON t(col);\n",
    ),
    // Sequence fixes
    (
        "seq-type",
        "CREATE SEQUENCE s AS INTEGER CACHE 1;",
        "CREATE SEQUENCE s AS BIGINT CACHE 1;\n",
    ),
    (
        "seq-add-cache",
        "CREATE SEQUENCE s;",
        "CREATE SEQUENCE s CACHE 1;\n",
    ),
    (
        "seq-fix-cache",
        "CREATE SEQUENCE s CACHE 100;",
        "CREATE SEQUENCE s CACHE 1;\n",
    ),
    // Identity fixes
    (
        "identity-type-to-bigint",
        "CREATE TABLE t (id INT GENERATED ALWAYS AS IDENTITY (CACHE 1));",
        "CREATE TABLE t (\n  id BIGINT GENERATED ALWAYS AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "identity-add-cache",
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY);",
        "CREATE TABLE t (\n  id BIGINT GENERATED ALWAYS AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    (
        "identity-fix-cache",
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 100));",
        "CREATE TABLE t (\n  id BIGINT GENERATED ALWAYS AS IDENTITY ( CACHE 1 )  \n);\n",
    ),
    // Transaction isolation
    (
        "isolation",
        "BEGIN ISOLATION LEVEL SERIALIZABLE;",
        "BEGIN ISOLATION LEVEL REPEATABLE READ;\n",
    ),
    // FK removal
    (
        "column-fk",
        "CREATE TABLE t (id INT, cid INT REFERENCES c(id));",
        "CREATE TABLE t (\n  id INT,\n  cid INT  \n);\n",
    ),
    (
        "table-fk",
        "CREATE TABLE t (id INT, cid INT, FOREIGN KEY (cid) REFERENCES c(id));",
        "CREATE TABLE t (\n  id INT,\n  cid INT  \n);\n",
    ),
    // Clause removal
    (
        "partition-by",
        "CREATE TABLE t (id INT) PARTITION BY RANGE (id);",
        "CREATE TABLE t (\n  id INT  \n);\n",
    ),
    (
        "inherits",
        "CREATE TABLE child (extra INT) INHERITS (parent);",
        "CREATE TABLE child (\n  extra INT  \n);\n",
    ),
    (
        "temp-view",
        "CREATE TEMP VIEW v AS SELECT 1;",
        "CREATE VIEW v AS\nSELECT\n  1;\n",
    ),
    (
        "temp-table",
        "CREATE TEMP TABLE t (id INT);",
        "CREATE TABLE t (\n  id INT  \n);\n",
    ),
    (
        "tablespace",
        "CREATE TABLE t (id INT) TABLESPACE my_space;",
        "CREATE TABLE t (\n  id INT  \n) ;\n",
    ),
    // ALTER TABLE column fixes
    (
        "alter-add-col-fk",
        "ALTER TABLE t ADD COLUMN cid INT REFERENCES c(id);",
        "ALTER TABLE t ADD COLUMN cid INT;\n",
    ),
    (
        "alter-add-col-collate",
        "ALTER TABLE t ADD COLUMN name VARCHAR(100) COLLATE \"en_US\";",
        "ALTER TABLE t ADD COLUMN name VARCHAR(100);\n",
    ),
    // COLLATE clause removal
    (
        "collate-c",
        "CREATE TABLE t (name VARCHAR(100) COLLATE \"C\");",
        "CREATE TABLE t (\n  name VARCHAR(100)  \n);\n",
    ),
    (
        "collate-en-us",
        "CREATE TABLE t (name VARCHAR(100) COLLATE \"en_US\");",
        "CREATE TABLE t (\n  name VARCHAR(100)  \n);\n",
    ),
    (
        "collate-pg-catalog-c",
        "CREATE TABLE t (name VARCHAR(100) COLLATE pg_catalog.\"C\");",
        "CREATE TABLE t (\n  name VARCHAR(100)  \n);\n",
    ),
    (
        "collate-multi-column",
        "CREATE TABLE t (\n  name VARCHAR(100) COLLATE \"C\",\n  city VARCHAR(50) COLLATE \"en_US\",\n  notes TEXT COLLATE \"en_US.utf8\"\n);",
        "CREATE TABLE t (\n  name VARCHAR(100),\n  city VARCHAR(50),\n  notes TEXT  \n);\n",
    ),
    // Mixed ALTER TABLE: FK removed, other ops kept
    (
        "alter-mixed-fk-col",
        "ALTER TABLE t ADD CONSTRAINT fk_c FOREIGN KEY (cid) REFERENCES c(id), ADD COLUMN x INT;",
        "ALTER TABLE t ADD COLUMN x INT;\n",
    ),
    // Multi-fix on one statement
    (
        "serial-plus-fk",
        "CREATE TABLE t (id SERIAL PRIMARY KEY, cid INT REFERENCES c(id));",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 ),\n  cid INT  \n);\n",
    ),
    // Whole-list collapse rules — pin the rendered text so a sqlparser
    // Display regression that silently drops INCLUDE (still valid SQL,
    // would re-lint clean and pass on a real cluster) is caught here.
    (
        "primary-key-collapse",
        "CREATE TABLE t (id integer NOT NULL, email text NOT NULL);\nALTER TABLE ONLY t ADD CONSTRAINT t_pkey PRIMARY KEY (id);",
        "CREATE TABLE t (\n  id INTEGER NOT NULL,\n  email TEXT NOT NULL,\n  CONSTRAINT t_pkey PRIMARY KEY (id)\n);\n",
    ),
    (
        "primary-key-collapse-with-include",
        "CREATE TABLE t (id integer NOT NULL, payload text);\nALTER TABLE ONLY t ADD CONSTRAINT t_pkey PRIMARY KEY (id) INCLUDE (payload);",
        "CREATE TABLE t (\n  id INTEGER NOT NULL,\n  payload TEXT,\n  CONSTRAINT t_pkey PRIMARY KEY (id) INCLUDE (payload)\n);\n",
    ),
    (
        "unique-collapse-with-include",
        "CREATE TABLE t (id integer NOT NULL, email text NOT NULL, payload text);\nALTER TABLE ONLY t ADD CONSTRAINT t_uk UNIQUE (email) INCLUDE (payload);",
        "CREATE TABLE t (\n  id INTEGER NOT NULL,\n  email TEXT NOT NULL,\n  payload TEXT,\n  CONSTRAINT t_uk UNIQUE (email) INCLUDE (payload)\n);\n",
    ),
    // Multi-statement
    (
        "multi-statement",
        "CREATE TABLE t (id SERIAL PRIMARY KEY);\nCREATE INDEX idx ON t(id);",
        "CREATE TABLE t (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n\nCREATE INDEX ASYNC idx ON t(id);\n",
    ),
    // Clean passthrough
    (
        "clean-passthrough",
        "CREATE TABLE t (id UUID PRIMARY KEY, amount DECIMAL(10,2));",
        "CREATE TABLE t (id UUID PRIMARY KEY, amount DECIMAL(10,2));\n",
    ),
    // DDL transaction splitting
    (
        "txn-two-ddl",
        "BEGIN;\nCREATE TABLE a (id INT);\nCREATE TABLE b (id INT);\nCOMMIT;",
        "BEGIN;\n\nCREATE TABLE a (id INT);\n\nCOMMIT;\n\nBEGIN;\n\nCREATE TABLE b (id INT);\n\nCOMMIT;\n",
    ),
    (
        "txn-three-ddl",
        "BEGIN;\nCREATE TABLE a (id INT);\nCREATE TABLE b (id INT);\nCREATE INDEX ASYNC idx ON a(id);\nCOMMIT;",
        "BEGIN;\n\nCREATE TABLE a (id INT);\n\nCOMMIT;\n\nBEGIN;\n\nCREATE TABLE b (id INT);\n\nCOMMIT;\n\nBEGIN;\n\nCREATE INDEX ASYNC idx ON a(id);\n\nCOMMIT;\n",
    ),
    (
        "txn-single-ddl-passthrough",
        "BEGIN;\nCREATE TABLE a (id INT);\nCOMMIT;",
        "BEGIN;\n\nCREATE TABLE a (id INT);\n\nCOMMIT;\n",
    ),
    (
        "txn-ddl-with-dml",
        "BEGIN;\nCREATE TABLE a (id INT);\nINSERT INTO a VALUES (1);\nCREATE TABLE b (id INT);\nCOMMIT;",
        "BEGIN;\n\nCREATE TABLE a (id INT);\n\nCOMMIT;\n\nBEGIN;\n\nINSERT INTO a VALUES (1);\n\nCOMMIT;\n\nBEGIN;\n\nCREATE TABLE b (id INT);\n\nCOMMIT;\n",
    ),
    (
        "txn-serial-fix-plus-split",
        "BEGIN;\nCREATE TABLE a (id SERIAL PRIMARY KEY);\nCREATE TABLE b (id INT);\nCOMMIT;",
        "BEGIN;\n\nCREATE TABLE a (\n  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY ( CACHE 1 )  \n);\n\nCOMMIT;\n\nBEGIN;\n\nCREATE TABLE b (id INT);\n\nCOMMIT;\n",
    ),
    (
        "txn-isolation-level-preserved",
        "BEGIN ISOLATION LEVEL REPEATABLE READ;\nCREATE TABLE a (id INT);\nCREATE TABLE b (id INT);\nCOMMIT;",
        "BEGIN ISOLATION LEVEL REPEATABLE READ;\n\nCREATE TABLE a (id INT);\n\nCOMMIT;\n\nBEGIN ISOLATION LEVEL REPEATABLE READ;\n\nCREATE TABLE b (id INT);\n\nCOMMIT;\n",
    ),
    (
        "txn-two-separate-txns",
        "BEGIN;\nCREATE TABLE a (id INT);\nCREATE TABLE b (id INT);\nCOMMIT;\nBEGIN;\nCREATE TABLE c (id INT);\nCOMMIT;",
        "BEGIN;\n\nCREATE TABLE a (id INT);\n\nCOMMIT;\n\nBEGIN;\n\nCREATE TABLE b (id INT);\n\nCOMMIT;\n\nBEGIN;\n\nCREATE TABLE c (id INT);\n\nCOMMIT;\n",
    ),
    (
        "txn-trailing-dml",
        "BEGIN;\nCREATE TABLE a (id INT);\nCREATE TABLE b (id INT);\nINSERT INTO a VALUES (1);\nCOMMIT;",
        "BEGIN;\n\nCREATE TABLE a (id INT);\n\nCOMMIT;\n\nBEGIN;\n\nCREATE TABLE b (id INT);\n\nCOMMIT;\n\nBEGIN;\n\nINSERT INTO a VALUES (1);\n\nCOMMIT;\n",
    ),
    (
        "txn-leading-dml",
        "BEGIN;\nINSERT INTO a VALUES (1);\nCREATE TABLE a (id INT);\nCREATE TABLE b (id INT);\nCOMMIT;",
        "BEGIN;\n\nINSERT INTO a VALUES (1);\n\nCOMMIT;\n\nBEGIN;\n\nCREATE TABLE a (id INT);\n\nCOMMIT;\n\nBEGIN;\n\nCREATE TABLE b (id INT);\n\nCOMMIT;\n",
    ),
    (
        "txn-nested-begin-stripped",
        "BEGIN;\nCREATE TABLE a (id INT);\nBEGIN;\nCREATE TABLE b (id INT);\nCOMMIT;",
        "BEGIN;\n\nCREATE TABLE a (id INT);\n\nCOMMIT;\n\nBEGIN;\n\nCREATE TABLE b (id INT);\n\nCOMMIT;\n",
    ),
];

#[test]
fn fix_snapshot_matrix() {
    for (label, input, expected) in SNAPSHOT_CASES {
        let result = fix_sql(input);
        assert_eq!(
            result.sql, *expected,
            "[{label}]\n--- Input ---\n{input}\n--- Expected ---\n{expected}\n--- Got ---\n{}",
            result.sql
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════
// DDL TRANSACTION FIX TESTS
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn fix_multi_ddl_emits_diagnostic() {
    let sql = "BEGIN;\nCREATE TABLE a (id INT);\nCREATE TABLE b (id INT);\nCOMMIT;";
    let result = fix_sql(sql);
    assert!(
        result
            .diagnostics
            .iter()
            .any(|d| d.message.contains("2 DDL statements")),
        "Should report multi-DDL diagnostic: {:?}",
        result.diagnostics
    );
}

#[test]
fn fix_multi_ddl_roundtrip_clean() {
    let sql = "BEGIN;\nCREATE TABLE a (id INT);\nCREATE TABLE b (id INT);\nCOMMIT;";
    let result = fix_sql(sql);
    let re_lint = dsql_lint::lint_sql(&result.sql);
    let ddl_txn_errors: Vec<_> = re_lint
        .iter()
        .filter(|d| d.message.contains("DDL statements"))
        .collect();
    assert!(
        ddl_txn_errors.is_empty(),
        "Fixed output should have no DDL transaction errors:\n  Fixed SQL: {}\n  Errors: {ddl_txn_errors:?}",
        result.sql
    );
}

#[test]
fn fix_rollback_transaction_not_split() {
    let sql = "BEGIN;\nCREATE TABLE a (id INT);\nCREATE TABLE b (id INT);\nROLLBACK;";
    let result = fix_sql(sql);
    assert!(
        !result
            .diagnostics
            .iter()
            .any(|d| d.message.contains("Split multi-DDL")),
        "ROLLBACK-terminated transaction should not be split: {:?}",
        result.diagnostics
    );
    assert!(
        result.sql.contains("ROLLBACK"),
        "ROLLBACK should be preserved in output, got: {}",
        result.sql
    );
    assert_eq!(
        result.sql.matches("BEGIN").count(),
        1,
        "Should not introduce extra BEGIN blocks for ROLLBACK txn, got: {}",
        result.sql
    );
}

/// End-to-end on the DDL a REAL `pg_dump` of an Aurora DSQL cluster emits for
/// an identity-PK table with a UNIQUE, a JSON column (lz4-compressed by DSQL),
/// and a covering PK. Captured verbatim from a live cluster. Every construct
/// must collapse/strip cleanly: zero ParseError/Unfixable, identity inline on
/// the CREATE TABLE, and the trailing `setval` left intact (it lands on the
/// inline identity's implicit sequence, which PostgreSQL auto-names
/// `<table>_<column>_seq` — the same name pg_dump's setval targets).
#[test]
fn fix_real_dsql_dump_round_trips_clean() {
    let ddl = "\
CREATE TABLE public.t (
    id bigint NOT NULL,
    email text NOT NULL,
    payload json
);
ALTER TABLE ONLY public.t ALTER COLUMN payload SET COMPRESSION lz4;
ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
SELECT pg_catalog.setval('public.t_id_seq', 2, true);
ALTER TABLE ONLY public.t
    ADD CONSTRAINT t_email_key UNIQUE (email);
ALTER TABLE ONLY public.t
    ADD CONSTRAINT t_pkey PRIMARY KEY (id) INCLUDE (email, payload);
";
    let result = fix_sql(ddl);

    // No unfixable diagnostics — the whole DSQL-native dump is handled.
    let unfixable: Vec<_> = result
        .diagnostics
        .iter()
        .filter(|d| matches!(d.fix_result, FixResult::Unfixable))
        .collect();
    assert!(
        unfixable.is_empty(),
        "real DSQL dump must fix cleanly, got unfixable: {unfixable:?}"
    );

    let upper = result.sql.to_uppercase();
    // Identity folded inline; standalone ADD GENERATED gone.
    assert!(
        upper.contains("GENERATED BY DEFAULT AS IDENTITY"),
        "identity must be inline, got:\n{}",
        result.sql
    );
    assert!(
        !upper.contains("ADD GENERATED"),
        "standalone ADD GENERATED must be removed, got:\n{}",
        result.sql
    );
    // SET COMPRESSION stripped.
    assert!(
        !upper.contains("SET COMPRESSION"),
        "SET COMPRESSION must be stripped, got:\n{}",
        result.sql
    );
    // setval preserved — it advances the inline identity's implicit sequence.
    assert!(
        result.sql.contains("setval"),
        "trailing setval must be preserved, got:\n{}",
        result.sql
    );
    // PK/UNIQUE folded onto the CREATE TABLE (existing collapse rules).
    assert!(
        upper.matches("CONSTRAINT").count() >= 2,
        "PK + UNIQUE must fold into the CREATE TABLE, got:\n{}",
        result.sql
    );

    // Re-lint the fixed SQL: must be free of ParseError now.
    let re = dsql_lint::lint_sql(&result.sql);
    assert!(
        !re.iter().any(|d| matches!(d.rule, LintRule::ParseError)),
        "fixed SQL must re-lint without ParseError, got: {re:?}"
    );
}

/// L1 end-to-end: a tuned `CACHE 65536` survives the collapse and re-lints
/// clean (DSQL accepts `CACHE >= 65536`), rather than being downgraded to 1.
#[test]
fn fix_real_dsql_dump_preserves_tuned_cache() {
    let ddl = "\
CREATE TABLE public.t (id bigint NOT NULL);
ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 65536
);
";
    let result = fix_sql(ddl);
    assert!(
        result.sql.contains("65536"),
        "tuned CACHE 65536 must be preserved, got:\n{}",
        result.sql
    );
    let re = dsql_lint::lint_sql(&result.sql);
    assert!(
        !re.iter()
            .any(|d| matches!(d.rule, LintRule::ParseError | LintRule::IdentityCache)),
        "fixed SQL with CACHE 65536 must re-lint clean, got: {re:?}"
    );
}

/// L1 end-to-end: an out-of-range source cache is preserved through the
/// identity collapse and then clamped to 1 "for free" by the downstream CACHE
/// validation when the rewritten CREATE TABLE is re-checked — emitting an
/// `IdentityCache` `FixedWithWarning`. Guards the cross-pass coupling the PR
/// relies on (fold preserves CACHE n -> per-statement re-lint clamps it).
#[test]
fn fix_out_of_range_identity_cache_is_clamped_with_warning() {
    let ddl = "\
CREATE TABLE public.t (id bigint NOT NULL);
ALTER TABLE public.t ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.t_id_seq CACHE 100
);
";
    let result = fix_sql(ddl);
    let upper = result.sql.to_uppercase();
    // `contains("CACHE 1")` alone is satisfied by un-clamped `CACHE 100`; assert
    // the value is actually 1 by requiring the closing paren and rejecting 100.
    assert!(
        upper.contains("CACHE 1 )") || upper.contains("CACHE 1)"),
        "out-of-range CACHE 100 must be clamped to CACHE 1, got:\n{}",
        result.sql
    );
    assert!(
        !upper.contains("CACHE 100"),
        "clamped output must not retain CACHE 100, got:\n{}",
        result.sql
    );
    let warned = result.diagnostics.iter().any(|d| {
        d.rule == LintRule::IdentityCache && matches!(d.fix_result, FixResult::FixedWithWarning(_))
    });
    assert!(
        warned,
        "clamp must surface an IdentityCache FixedWithWarning, got: {:?}",
        result.diagnostics
    );
}

#[test]
fn fix_unclosed_multi_ddl_transaction_unchanged() {
    let sql = "BEGIN;\nCREATE TABLE a (id INT);\nCREATE TABLE b (id INT);";
    let result = fix_sql(sql);
    assert_eq!(
        result.sql.matches("BEGIN").count(),
        1,
        "Unclosed transaction should not be split, got: {}",
        result.sql
    );
}

#[test]
fn fix_ddl_with_dml_roundtrip_clean() {
    let sql = "BEGIN;\nCREATE TABLE a (id INT);\nINSERT INTO a VALUES (1);\nCREATE TABLE b (id INT);\nCOMMIT;";
    let result = fix_sql(sql);
    let re_lint = dsql_lint::lint_sql(&result.sql);
    let txn_errors: Vec<_> = re_lint
        .iter()
        .filter(|d| {
            matches!(
                d.rule,
                LintRule::MultiDdlTransaction | LintRule::MixedDdlDmlTransaction
            )
        })
        .collect();
    assert!(
        txn_errors.is_empty(),
        "Fixed DDL+DML output should have no DDL transaction errors:\n  Fixed SQL: {}\n  Errors: {txn_errors:?}",
        result.sql
    );
}

#[test]
fn rollback_terminated_mixed_txn_does_not_emit_mixed_diagnostic() {
    // ROLLBACK never commits, so DSQL never sees the violation.
    let sql = "BEGIN;\nCREATE TABLE z (id INT);\nINSERT INTO z VALUES (1);\nROLLBACK;";
    let diags = dsql_lint::lint_sql(sql);
    assert!(
        !diags
            .iter()
            .any(|d| d.rule == LintRule::MixedDdlDmlTransaction),
        "ROLLBACK-terminated mixed txn should not emit MixedDdlDmlTransaction: {diags:?}"
    );
}

#[test]
fn unclosed_mixed_txn_does_not_emit_mixed_diagnostic() {
    // No COMMIT seen → analyzer cannot conclude the txn would have violated.
    let sql = "BEGIN;\nCREATE TABLE z (id INT);\nINSERT INTO z VALUES (1);";
    let diags = dsql_lint::lint_sql(sql);
    assert!(
        !diags
            .iter()
            .any(|d| d.rule == LintRule::MixedDdlDmlTransaction),
        "Unclosed mixed txn should not emit MixedDdlDmlTransaction: {diags:?}"
    );
}

#[test]
fn dml_then_ddl_in_txn_still_emits_mixed_diagnostic() {
    // Order-invariance: the analyzer must flag the violation regardless
    // of which side of the transaction the DDL appears on.
    let sql = "BEGIN;\nINSERT INTO z VALUES (1);\nCREATE TABLE z (id INT);\nCOMMIT;";
    let diags = dsql_lint::lint_sql(sql);
    assert!(
        diags
            .iter()
            .any(|d| d.rule == LintRule::MixedDdlDmlTransaction),
        "DML-then-DDL ordering should still emit MixedDdlDmlTransaction: {diags:?}"
    );
}

#[test]
fn savepoint_inside_mixed_txn_still_flagged_at_commit() {
    let sql = "BEGIN;\nCREATE TABLE z (id INT);\nSAVEPOINT sp;\nINSERT INTO z VALUES (1);\nCOMMIT;";
    let diags = dsql_lint::lint_sql(sql);
    assert!(
        diags
            .iter()
            .any(|d| d.rule == LintRule::MixedDdlDmlTransaction),
        "SAVEPOINT inside mixed txn should not suppress MixedDdlDmlTransaction at COMMIT: {diags:?}"
    );
}

#[test]
fn two_transactions_only_mixed_one_flagged() {
    let sql = "BEGIN;\nINSERT INTO existing VALUES (1);\nCOMMIT;\n\
               BEGIN;\nCREATE TABLE z (id INT);\nINSERT INTO z VALUES (1);\nCOMMIT;";
    let diags = dsql_lint::lint_sql(sql);
    let mixed: Vec<_> = diags
        .iter()
        .filter(|d| d.rule == LintRule::MixedDdlDmlTransaction)
        .collect();
    assert_eq!(
        mixed.len(),
        1,
        "Only the mixed transaction should be flagged, got: {mixed:?}"
    );
}

#[test]
fn fix_single_ddl_plus_dml_in_txn_emits_diagnostic_and_splits() {
    let sql = "BEGIN;\nCREATE TABLE z (id INT);\nINSERT INTO z VALUES (1);\nCOMMIT;";
    let result = fix_sql(sql);
    assert!(
        result
            .diagnostics
            .iter()
            .any(|d| d.rule == LintRule::MixedDdlDmlTransaction),
        "Single-DDL + DML in same txn should emit MixedDdlDmlTransaction: {:?}",
        result.diagnostics
    );
    let re_lint = dsql_lint::lint_sql(&result.sql);
    assert!(
        !re_lint
            .iter()
            .any(|d| d.rule == LintRule::MixedDdlDmlTransaction),
        "Fixed output should re-lint clean:\n  Fixed: {}\n  Re-lint: {re_lint:?}",
        result.sql
    );
}

// ═══════════════════════════════════════════════════════════════════════
// STANDALONE TESTS
// ═══════════════════════════════════════════════════════════════════════
// Cases with bespoke assertions that don't fit a matrix row.

#[test]
fn fix_alter_fk_removed_entirely() {
    let result = fix_sql("ALTER TABLE t ADD CONSTRAINT fk_c FOREIGN KEY (cid) REFERENCES c(id);");
    assert_eq!(
        result.sql, "",
        "ALTER TABLE with only FK should produce empty output"
    );
    assert_eq!(result.diagnostics.len(), 1);
}

#[test]
fn fix_clean_statement_verbatim() {
    let sql = "CREATE TABLE orders (id UUID PRIMARY KEY, amount DECIMAL(10,2))";
    let result = fix_sql(sql);
    assert_eq!(result.sql.trim(), format!("{sql};"));
    assert!(result.diagnostics.is_empty());
}

#[test]
fn fix_collate_multi_column_tiers_and_line_numbers() {
    // Three COLLATE columns on three separate source lines exercise:
    //   - per-column line attribution (each diagnostic points at its column)
    //   - tier classification per column (`C` -> Fixed, others -> FixedWithWarning)
    //   - the multi-segment ObjectName path (`pg_catalog."C"` is C-equivalent)
    let sql = "CREATE TABLE t (\n  \
               name VARCHAR(100) COLLATE \"C\",\n  \
               city VARCHAR(50) COLLATE pg_catalog.\"C\",\n  \
               notes TEXT COLLATE \"en_US\"\n\
               );";
    let result = fix_sql(sql);
    let collate_diags: Vec<_> = result
        .diagnostics
        .iter()
        .filter(|d| d.rule == LintRule::Collation)
        .collect();
    assert_eq!(
        collate_diags.len(),
        3,
        "expected 3 Collation diagnostics, got: {:?}",
        result.diagnostics
    );
    assert_eq!(
        collate_diags.iter().map(|d| d.line).collect::<Vec<_>>(),
        vec![2, 3, 4],
        "expected per-column line attribution"
    );
    assert!(matches!(collate_diags[0].fix_result, FixResult::Fixed(_)));
    assert!(matches!(collate_diags[1].fix_result, FixResult::Fixed(_)));
    assert!(matches!(
        collate_diags[2].fix_result,
        FixResult::FixedWithWarning(_)
    ));
}

// ═══════════════════════════════════════════════════════════════════════
// FIXTURE TESTS
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn fix_sample_migration_reduces_errors() {
    let sql = include_str!("fixtures/sample_migration.sql");
    let original_diags = dsql_lint::lint_sql(sql);

    let result = dsql_lint::fix_sql(sql);
    let re_lint = dsql_lint::lint_sql(&result.sql);

    assert!(
        re_lint.len() < original_diags.len(),
        "Expected fewer errors after fix.\n  Before: {}\n  After: {}",
        original_diags.len(),
        re_lint.len()
    );

    let fixable_patterns = ["SERIAL", "ASYNC", "FOREIGN KEY", "TEMPORARY tables"];
    for pattern in fixable_patterns {
        assert!(
            !re_lint.iter().any(|d| d.message.contains(pattern)),
            "Fixed output still contains fixable error: {pattern}\n  Errors: {re_lint:?}"
        );
    }
}

#[test]
fn fix_clean_file_is_verbatim() {
    let sql = include_str!("fixtures/clean_all_types.sql");
    let result = dsql_lint::fix_sql(sql);
    assert!(
        result.diagnostics.is_empty(),
        "Clean file should produce no diagnostics, got: {:?}",
        result.diagnostics
    );
    let re_lint = dsql_lint::lint_sql(&result.sql);
    assert!(
        re_lint.is_empty(),
        "Re-linting fixed output of clean file produced errors: {re_lint:?}"
    );
}
