//! Verifies the in-tree corpus matches the curated arrays in
//! `tests/common/mod.rs`. With `BLESS_MIRROR=1`, regenerates and rewrites
//! the files; without, fails with a diff.

#![cfg(feature = "grammar-diff")]

mod common;

use std::path::PathBuf;

const HEADER_PREFIX: &str = "-- AUTOGENERATED by tests/grammar_corpus_mirror_test.rs.\n-- Mirrors a curated array in dsql-lint's integration tests. Do not edit by hand.\n";

fn corpus_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/grammar_corpus/in_tree")
}

fn expected_files() -> Vec<(&'static str, String)> {
    vec![
        ("supported_types.sql", build_supported_types()),
        ("clean_statements.sql", build_clean_statements()),
        ("error_cases.sql", build_error_cases()),
        ("false_positive_cases.sql", build_false_positive_cases()),
        ("source.sql", build_source_pointer()),
    ]
}

fn build_supported_types() -> String {
    let mut out = String::from(HEADER_PREFIX);
    out.push_str("-- Source: tests/common/mod.rs::SUPPORTED_TYPES\n\n");
    for (label, sql_type) in common::SUPPORTED_TYPES {
        out.push_str(&format!("-- label: {label}\n"));
        out.push_str(&format!("CREATE TABLE _t (col {sql_type});\n\n"));
    }
    out
}

fn build_clean_statements() -> String {
    let mut out = String::from(HEADER_PREFIX);
    out.push_str("-- Source: tests/common/mod.rs::CLEAN_STATEMENTS\n\n");
    for (label, sql, _setup, _cleanup) in common::CLEAN_STATEMENTS {
        out.push_str(&format!("-- label: {label}\n"));
        out.push_str(sql);
        if !sql.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    out
}

fn build_error_cases() -> String {
    let mut out = String::from(HEADER_PREFIX);
    out.push_str("-- Source: tests/common/mod.rs::ADDITIONAL_ERROR_CASES\n\n");
    for (sql, key) in common::ADDITIONAL_ERROR_CASES {
        out.push_str(&format!("-- label: {key}\n"));
        out.push_str(sql);
        if !sql.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    out
}

fn build_false_positive_cases() -> String {
    let mut out = String::from(HEADER_PREFIX);
    out.push_str(
        "-- Source: tests/common/mod.rs::FALSE_POSITIVE_CASES + ADDITIONAL_FALSE_POSITIVES\n\n",
    );
    for (sql, key) in common::FALSE_POSITIVE_CASES
        .iter()
        .chain(common::ADDITIONAL_FALSE_POSITIVES.iter())
    {
        out.push_str(&format!("-- label: {key}\n"));
        out.push_str(sql);
        if !sql.ends_with('\n') {
            out.push('\n');
        }
        out.push('\n');
    }
    out
}

fn build_source_pointer() -> String {
    String::from(
        "-- AUTOGENERATED by tests/grammar_corpus_mirror_test.rs.\n\
         -- This directory mirrors curated SQL from tests/common/mod.rs:\n\
         --   SUPPORTED_TYPES, CLEAN_STATEMENTS, ADDITIONAL_ERROR_CASES,\n\
         --   FALSE_POSITIVE_CASES, ADDITIONAL_FALSE_POSITIVES.\n\
         --\n\
         -- Refresh: BLESS_MIRROR=1 cargo test --features grammar-diff \\\n\
         --             --test grammar_corpus_mirror_test\n",
    )
}

#[test]
fn mirror_matches_source() {
    let dir = corpus_dir();
    std::fs::create_dir_all(&dir).expect("create in_tree dir");

    let files = expected_files();
    let bless = std::env::var_os("BLESS_MIRROR").is_some();

    let mut diffs = Vec::new();
    for (name, expected) in &files {
        let path = dir.join(name);
        let actual = std::fs::read_to_string(&path).unwrap_or_default();
        if actual != *expected {
            diffs.push((path.clone(), actual, expected.clone(), name.to_string()));
        }
    }

    if diffs.is_empty() {
        return;
    }

    // Print the diff before any rewrite so blessing isn't blind.
    for (path, actual, expected, _name) in &diffs {
        eprintln!("--- {} (vendored) ---", path.display());
        eprintln!("+++ expected (regenerated from source arrays) +++");
        let actual_lines: Vec<&str> = actual.lines().collect();
        let expected_lines: Vec<&str> = expected.lines().collect();
        let max = actual_lines.len().max(expected_lines.len());
        for i in 0..max {
            let a = actual_lines.get(i).copied().unwrap_or("");
            let e = expected_lines.get(i).copied().unwrap_or("");
            if a != e {
                if !a.is_empty() {
                    eprintln!("- {a}");
                }
                if !e.is_empty() {
                    eprintln!("+ {e}");
                }
            }
        }
        eprintln!();
    }

    if bless {
        for (path, _actual, expected, _name) in &diffs {
            std::fs::write(path, expected).expect("write mirror file");
            eprintln!("blessed: {}", path.display());
        }
    } else {
        eprintln!("Mirror is out of sync with the source const arrays in tests/common/mod.rs.");
        eprintln!("Refresh with:");
        eprintln!(
            "  BLESS_MIRROR=1 cargo test --features grammar-diff --test grammar_corpus_mirror_test"
        );
        panic!("in-tree corpus mirror is stale");
    }
}
