//! Integration tests for dsql-lint.
//!
//! Matrix-driven test groups:
//!   1. Supported types — every DSQL type must lint clean
//!   2. Error detection — every unsupported pattern must be caught
//!   3. Suggestion validity — every suggested replacement must itself be valid
//!   4. False positives — valid SQL must not trigger errors
//!   5. Warning detection — warnings and their false positives
//!   6. Fixtures — realistic multi-statement SQL files

use dsql_lint::lint::{lint_sql, Severity};

// ═══════════════════════════════════════════════════════════════════════
// 1. SUPPORTED TYPES MATRIX
// ═══════════════════════════════════════════════════════════════════════
// Every DSQL-supported column type. The test wraps each in a CREATE TABLE
// and asserts zero errors. If a new lint rule false-positives on a valid
// type, this catches it.
//
// Source: https://docs.aws.amazon.com/aurora-dsql/latest/userguide/
//         working-with-postgresql-compatibility-supported-data-types.html

const SUPPORTED_TYPES: &[&str] = &[
    // Numeric
    "SMALLINT",
    "INT2",
    "INTEGER",
    "INT",
    "INT4",
    "BIGINT",
    "INT8",
    "REAL",
    "FLOAT4",
    "DOUBLE PRECISION",
    "FLOAT8",
    "NUMERIC(10,2)",
    "DECIMAL(18,6)",
    "DEC(5,2)",
    // Character
    "CHAR(10)",
    "CHARACTER(20)",
    "VARCHAR(255)",
    "CHARACTER VARYING(100)",
    "TEXT",
    "BPCHAR(50)",
    // Date/time
    "DATE",
    "TIME",
    "TIME WITH TIME ZONE",
    "TIMESTAMP",
    "TIMESTAMP WITH TIME ZONE",
    "INTERVAL",
    // Miscellaneous
    "BOOLEAN",
    "BOOL",
    "BYTEA",
    "UUID",
    // Identity columns
    "BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 1)",
    "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)",
    "BIGINT GENERATED ALWAYS AS IDENTITY (CACHE 65536)",
    "BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 65536)",
];

#[test]
fn supported_types_produce_zero_errors() {
    for col_type in SUPPORTED_TYPES {
        let sql = format!("CREATE TABLE _type_test (col {col_type});");
        let diags = lint_sql(&sql);
        let errors: Vec<_> = diags
            .iter()
            .filter(|d| d.severity == Severity::Error)
            .collect();
        assert!(
            errors.is_empty(),
            "Supported type `{col_type}` triggered errors:\n  SQL: {sql}\n  Errors: {errors:?}"
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════
// 2. ERROR DETECTION MATRIX
// ═══════════════════════════════════════════════════════════════════════
// Every unsupported pattern the linter should catch, tested through the
// full lint_sql pipeline (statement splitting + parsing + all rules).
// (category, sql, expected message substring)

const ERROR_CASES: &[(&str, &str, &str)] = &[
    // SERIAL variants — all aliases
    (
        "serial",
        "CREATE TABLE t (id SERIAL PRIMARY KEY);",
        "SERIAL",
    ),
    (
        "serial",
        "CREATE TABLE t (id SERIAL4 PRIMARY KEY);",
        "SERIAL4",
    ),
    (
        "serial",
        "CREATE TABLE t (id BIGSERIAL PRIMARY KEY);",
        "BIGSERIAL",
    ),
    (
        "serial",
        "CREATE TABLE t (id SERIAL8 PRIMARY KEY);",
        "SERIAL8",
    ),
    (
        "serial",
        "CREATE TABLE t (id SMALLSERIAL PRIMARY KEY);",
        "SMALLSERIAL",
    ),
    (
        "serial",
        "CREATE TABLE t (id SERIAL2 PRIMARY KEY);",
        "SERIAL2",
    ),
    // JSON / JSONB
    ("json", "CREATE TABLE t (id INT, data JSON);", "JSON"),
    ("json", "CREATE TABLE t (id INT, data JSONB);", "JSONB"),
    // Foreign keys — column-level and table-level
    (
        "fk",
        "CREATE TABLE t (id INT, cid INT REFERENCES c(id));",
        "FOREIGN KEY",
    ),
    (
        "fk",
        "CREATE TABLE t (id INT, cid INT, FOREIGN KEY (cid) REFERENCES c(id));",
        "FOREIGN KEY",
    ),
    // Temp tables
    ("temp", "CREATE TEMP TABLE t (id INT);", "TEMPORARY"),
    ("temp", "CREATE TEMPORARY TABLE t (id INT);", "TEMPORARY"),
    // Array types
    ("array", "CREATE TABLE t (id INT, tags TEXT[]);", "array"),
    ("array", "CREATE TABLE t (id INT, scores INT[]);", "array"),
    // Partition
    (
        "partition",
        "CREATE TABLE t (id INT, d DATE) PARTITION BY RANGE (d);",
        "PARTITION",
    ),
    // Truncate
    ("truncate", "TRUNCATE TABLE orders;", "TRUNCATE"),
    // Trigger
    (
        "trigger",
        "CREATE TRIGGER trg AFTER INSERT ON t FOR EACH ROW EXECUTE FUNCTION f();",
        "TRIGGER",
    ),
    // Extension
    (
        "extension",
        "CREATE EXTENSION IF NOT EXISTS pgcrypto;",
        "EXTENSION",
    ),
    // Index without ASYNC
    ("index", "CREATE INDEX idx_foo ON t(col);", "ASYNC"),
    ("index", "CREATE UNIQUE INDEX idx_bar ON t(col);", "ASYNC"),
    // ALTER TABLE — same checks as CREATE TABLE
    (
        "alter-serial",
        "ALTER TABLE t ADD COLUMN id SERIAL;",
        "SERIAL",
    ),
    ("alter-json", "ALTER TABLE t ADD COLUMN data JSON;", "JSON"),
    (
        "alter-array",
        "ALTER TABLE t ADD COLUMN tags TEXT[];",
        "array",
    ),
    (
        "alter-fk-column",
        "ALTER TABLE t ADD COLUMN cid INT REFERENCES c(id);",
        "FOREIGN KEY",
    ),
    (
        "alter-fk-constraint",
        "ALTER TABLE t ADD CONSTRAINT fk_c FOREIGN KEY (cid) REFERENCES c(id);",
        "FOREIGN KEY",
    ),
];

#[test]
fn error_detection_matrix() {
    for (category, sql, expected) in ERROR_CASES {
        let diags = lint_sql(sql);
        assert!(
            diags
                .iter()
                .any(|d| d.severity == Severity::Error && d.message.contains(expected)),
            "[{category}] Expected error containing {expected:?} for:\n  {sql}\n  got: {diags:?}"
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════
// 3. SUGGESTION VALIDITY MATRIX
// ═══════════════════════════════════════════════════════════════════════
// Every SQL replacement the linter suggests must itself be valid DSQL.
// Column-type suggestions are wrapped in CREATE TABLE; command suggestions
// are tested directly.

const SUGGESTED_COLUMN_TYPES: &[&str] = &["BIGINT GENERATED BY DEFAULT AS IDENTITY (CACHE 1)"];

#[test]
fn suggested_column_types_are_dsql_valid() {
    for col_type in SUGGESTED_COLUMN_TYPES {
        let sql = format!("CREATE TABLE _test (id {col_type} PRIMARY KEY);");
        let diags = lint_sql(&sql);
        let errors: Vec<_> = diags
            .iter()
            .filter(|d| d.severity == Severity::Error)
            .collect();
        assert!(
            errors.is_empty(),
            "Suggested type `{col_type}` triggers errors:\n  SQL: {sql}\n  Errors: {errors:?}"
        );
    }
}

#[test]
fn suggested_async_index_is_valid() {
    let sql = "CREATE INDEX ASYNC idx_test ON t(col);";
    let diags = lint_sql(sql);
    assert!(
        !diags.iter().any(|d| d.message.contains("not supported")),
        "CREATE INDEX ASYNC should be valid, got: {diags:?}"
    );
}

// ═══════════════════════════════════════════════════════════════════════
// 4. FALSE-POSITIVE MATRIX
// ═══════════════════════════════════════════════════════════════════════
// Valid SQL that must NOT trigger any errors. Each row targets a specific
// rule to verify it doesn't over-match.

const FALSE_POSITIVE_CASES: &[(&str, &str)] = &[
    // Column named 'serial_number' should not trigger SERIAL rule
    (
        "CREATE TABLE t (id UUID PRIMARY KEY, serial_number VARCHAR(100));",
        "SERIAL",
    ),
    // TEXT column named 'json_data' should not trigger JSON rule
    (
        "CREATE TABLE t (id UUID PRIMARY KEY, json_data TEXT);",
        "JSON",
    ),
    // Table named 'temporary_cache' should not trigger TEMP rule
    (
        "CREATE TABLE temporary_cache (id UUID PRIMARY KEY);",
        "TEMPORARY",
    ),
    // TEXT column named 'tags' should not trigger array rule
    ("CREATE TABLE t (id UUID PRIMARY KEY, tags TEXT);", "array"),
    // Column named 'partition_key' should not trigger PARTITION rule
    (
        "CREATE TABLE t (id UUID PRIMARY KEY, partition_key VARCHAR(50));",
        "PARTITION",
    ),
    // DELETE FROM should not trigger TRUNCATE rule
    ("DELETE FROM events WHERE id = 1;", "TRUNCATE"),
    // GENERATED ALWAYS AS IDENTITY should not trigger SERIAL
    (
        "CREATE TABLE t (id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY);",
        "SERIAL",
    ),
    // GENERATED BY DEFAULT AS IDENTITY should not trigger SERIAL
    (
        "CREATE TABLE t (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);",
        "SERIAL",
    ),
];

/// Valid SQL that must produce zero errors, period. No substring matching —
/// these statements are entirely clean and should never trigger anything.
const CLEAN_STATEMENTS: &[&str] = &[
    "CREATE VIEW v AS SELECT 1;",
    "ALTER TABLE t ADD COLUMN description TEXT;",
    "INSERT INTO t (data) VALUES ('TRUNCATE TABLE foo; CREATE TRIGGER bar');",
    "SELECT * FROM t WHERE id = 1;",
    "UPDATE t SET name = 'foo' WHERE id = 1;",
    "DELETE FROM t WHERE id = 1;",
];

#[test]
fn false_positive_matrix() {
    for (sql, unexpected) in FALSE_POSITIVE_CASES {
        let diags = lint_sql(sql);
        let errors: Vec<_> = diags
            .iter()
            .filter(|d| d.severity == Severity::Error)
            .collect();
        assert!(
            !errors.iter().any(|d| d.message.contains(unexpected)),
            "False positive! `{unexpected}` found in errors for:\n  {sql}\n  Errors: {errors:?}"
        );
    }
}

#[test]
fn clean_statements_produce_zero_errors() {
    for sql in CLEAN_STATEMENTS {
        let diags = lint_sql(sql);
        let errors: Vec<_> = diags
            .iter()
            .filter(|d| d.severity == Severity::Error)
            .collect();
        assert!(
            errors.is_empty(),
            "Clean SQL triggered errors:\n  SQL: {sql}\n  Errors: {errors:?}"
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════
// 5. WARNING DETECTION MATRIX
// ═══════════════════════════════════════════════════════════════════════

const WARNING_CASES: &[(&str, &str)] = &[
    (
        "ALTER TABLE t ADD COLUMN status VARCHAR(50) DEFAULT 'pending';",
        "ADD COLUMN",
    ),
    (
        "ALTER TABLE t ADD COLUMN status VARCHAR(50) NOT NULL;",
        "ADD COLUMN",
    ),
];

const WARNING_FALSE_POSITIVES: &[(&str, &str)] =
    &[("ALTER TABLE t ADD COLUMN status VARCHAR(50);", "ADD COLUMN")];

#[test]
fn warning_detection_matrix() {
    for (sql, expected) in WARNING_CASES {
        let diags = lint_sql(sql);
        assert!(
            diags
                .iter()
                .any(|d| d.severity == Severity::Warning && d.message.contains(expected)),
            "Expected warning containing {expected:?} for:\n  {sql}\n  got: {diags:?}"
        );
    }
}

#[test]
fn warning_false_positive_matrix() {
    for (sql, unexpected) in WARNING_FALSE_POSITIVES {
        let diags = lint_sql(sql);
        assert!(
            !diags
                .iter()
                .any(|d| d.severity == Severity::Warning && d.message.contains(unexpected)),
            "Unexpected warning containing {unexpected:?} for:\n  {sql}\n  got: {diags:?}"
        );
    }
}

// ═══════════════════════════════════════════════════════════════════════
// 6. FIXTURE-BASED TESTS
// ═══════════════════════════════════════════════════════════════════════

/// Every supported DSQL type, constraint, and valid DDL pattern in one file.
/// Must produce zero errors.
#[test]
fn fixture_clean_all_types() {
    let sql = include_str!("fixtures/clean_all_types.sql");
    let diags = lint_sql(sql);
    let errors: Vec<_> = diags
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .collect();
    assert!(
        errors.is_empty(),
        "clean_all_types.sql should have zero errors, got:\n{errors:#?}"
    );
}

/// Realistic migration with known incompatibilities — verify each is caught.
#[test]
fn fixture_sample_migration() {
    let sql = include_str!("fixtures/sample_migration.sql");
    let diags = lint_sql(sql);
    let errors: Vec<_> = diags
        .iter()
        .filter(|d| d.severity == Severity::Error)
        .collect();

    let expected = &[
        "SERIAL",
        "FOREIGN KEY",
        "JSON",
        "TRUNCATE",
        "TEMPORARY",
        "array",
        "ASYNC",
    ];
    for msg in expected {
        assert!(
            errors.iter().any(|d| d.message.contains(msg)),
            "sample_migration.sql: missing expected error containing {msg:?}\n  got: {errors:#?}"
        );
    }

    // Valid DML in the fixture should not produce errors
    assert!(
        !errors.iter().any(|d| d.message.contains("INSERT")
            || d.message.contains("SELECT")
            || d.message.contains("DELETE")),
        "DML should not produce errors: {errors:#?}"
    );
}
